# 20.7) Apriori - Regras de associação

Dados de mercado

In [12]:
#!pip install apyori

In [13]:
import pandas as pd
from apyori import apriori

## Base de dados mercado 1

In [14]:
base_mercado1 = pd.read_csv('mercado.csv', header = None) # regra sem título nas colunas header = None
base_mercado1

          0        1         2         3
0     leite  cerveja       pao  manteiga
1      cafe      pao  manteiga       NaN
2      cafe      pao  manteiga       NaN
3     leite     cafe       pao  manteiga
4   cerveja      NaN       NaN       NaN
5  manteiga      NaN       NaN       NaN
6       pao      NaN       NaN       NaN
7    feijao      NaN       NaN       NaN
8     arroz   feijao       NaN       NaN
9     arroz      NaN       NaN       NaN

cada linha da tabela equivale a uma transação de compra. 

colocaremos os dados em formato de lista agora

In [15]:
transacoes = []
print('shape coluna')
print(base_mercado1.shape[1])
for i in range(len(base_mercado1)):
  print(i)
  print(base_mercado1.values[i, 0]) # acessar cada um desses elementos [linha, coluna]  
  # colocar em string str e no formato de lista como []
  transacoes.append([str(base_mercado1.values[i, j]) for j in range(base_mercado1.shape[1])])

shape coluna
4
0
leite
1
cafe
2
cafe
3
leite
4
cerveja
5
manteiga
6
pao
7
feijao
8
arroz
9
arroz

In [16]:
transacoes

[['leite', 'cerveja', 'pao', 'manteiga'],
 ['cafe', 'pao', 'manteiga', 'nan'],
 ['cafe', 'pao', 'manteiga', 'nan'],
 ['leite', 'cafe', 'pao', 'manteiga'],
 ['cerveja', 'nan', 'nan', 'nan'],
 ['manteiga', 'nan', 'nan', 'nan'],
 ['pao', 'nan', 'nan', 'nan'],
 ['feijao', 'nan', 'nan', 'nan'],
 ['arroz', 'feijao', 'nan', 'nan'],
 ['arroz', 'nan', 'nan', 'nan']]

In [17]:
base_mercado1.shape #linha, colunas

(10, 4)

In [19]:
type(transacoes) # formato de lista

list

# 20.8) Regra de associação 2

apriori(df, min_support=0.5, use_colnames=True): Esta função identifica conjuntos de itens no DataFrame dfque aparecem juntos com frequência.

dfé o DataFrame de entrada onde cada linha representa uma transação e cada coluna representa um item.

min_support=0.5especifica que apenas conjuntos de itens com suporte de pelo menos 50% devem ser considerados frequentes. Suporte é a proporção de transações que contêm o conjunto de itens.

use_colnames=Truegarante que a saída use os nomes de colunas reais dfem vez dos índices de colunas.




O objetivo deste código é encontrar combinações de itens que frequentemente ocorrem juntos no conjunto de dados, o que é útil para tarefas como análise de cesta de compras.

https://www.datacamp.com/tutorial/apriori-algorithm

In [22]:
# chamando a função apriori, coletando as listas: transacoes
regras = apriori(transacoes)
resultados = list(regras)
# aparece as regras de associação geradas
resultados

[RelationRecord(items=frozenset({'arroz'}), support=0.2, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'arroz'}), confidence=0.2, lift=1.0)]),
 RelationRecord(items=frozenset({'cafe'}), support=0.3, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'cafe'}), confidence=0.3, lift=1.0)]),
 RelationRecord(items=frozenset({'cerveja'}), support=0.2, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'cerveja'}), confidence=0.2, lift=1.0)]),
 RelationRecord(items=frozenset({'feijao'}), support=0.2, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'feijao'}), confidence=0.2, lift=1.0)]),
 RelationRecord(items=frozenset({'leite'}), support=0.2, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'leite'}), confidence=0.2, lift=1.0)]),
 RelationRecord(items=frozenset({'manteiga'}), support=0.5, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'manteiga'}), confidence=0.5, lift=1.0)]),
 RelationRecord(items=frozenset({'nan'}), support=0.8, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'nan'}), confidence=0.8, lift=1.0)]),
 RelationRecord(items=frozenset({'pao'}), support=0.5, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'pao'}), confidence=0.5, lift=1.0)]),
 RelationRecord(items=frozenset({'feijao', 'arroz'}), support=0.1, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'feijao', 'arroz'}), confidence=0.1, lift=1.0), OrderedStatistic(items_base=frozenset({'arroz'}), items_add=frozenset({'feijao'}), confidence=0.5, lift=2.5), OrderedStatistic(items_base=frozenset({'feijao'}), items_add=frozenset({'arroz'}), confidence=0.5, lift=2.5)]),
 RelationRecord(items=frozenset({'arroz', 'nan'}), support=0.2, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'arroz', 'nan'}), confidence=0.2, lift=1.0), OrderedStatistic(items_base=frozenset({'arroz'}), items_add=frozenset({'nan'}), confidence=1.0, lift=1.25), OrderedStatistic(items_base=frozenset({'nan'}), items_add=frozenset({'arroz'}), confidence=0.25, lift=1.25)]),
 RelationRecord(items=frozenset({'leite', 'cafe'}), support=0.1, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'leite', 'cafe'}), confidence=0.1, lift=1.0), OrderedStatistic(items_base=frozenset({'cafe'}), items_add=frozenset({'leite'}), confidence=0.33333333333333337, lift=1.6666666666666667), OrderedStatistic(items_base=frozenset({'leite'}), items_add=frozenset({'cafe'}), confidence=0.5, lift=1.6666666666666667)]),
 RelationRecord(items=frozenset({'cafe', 'manteiga'}), support=0.3, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'cafe', 'manteiga'}), confidence=0.3, lift=1.0), OrderedStatistic(items_base=frozenset({'cafe'}), items_add=frozenset({'manteiga'}), confidence=1.0, lift=2.0), OrderedStatistic(items_base=frozenset({'manteiga'}), items_add=frozenset({'cafe'}), confidence=0.6, lift=2.0)]),
 RelationRecord(items=frozenset({'cafe', 'nan'}), support=0.2, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'cafe', 'nan'}), confidence=0.2, lift=1.0), OrderedStatistic(items_base=frozenset({'cafe'}), items_add=frozenset({'nan'}), confidence=0.6666666666666667, lift=0.8333333333333334), OrderedStatistic(items_base=frozenset({'nan'}), items_add=frozenset({'cafe'}), confidence=0.25, lift=0.8333333333333334)]),
 RelationRecord(items=frozenset({'pao', 'cafe'}), support=0.3, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'pao', 'cafe'}), confidence=0.3, lift=1.0), OrderedStatistic(items_base=frozenset({'cafe'}), items_add=frozenset({'pao'}), confidence=1.0, lift=2.0), OrderedStatistic(items_base=frozenset({'pao'}), items_add=frozenset({'cafe'}), confidence=0.6, lift=2.0)]),
 RelationRecord(items=frozenset({'leite', 'cerveja'}), support=0.1, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'leite', 'cerveja'}), confidence=0.1, lift=1.0), OrderedStatistic(items_base=frozenset({'cerveja'}), items_add=frozenset({'leite'}), confidence=0.5, lift=2.5), OrderedStatistic(items_base=frozenset({'leite'}), items_add=frozenset({'cerveja'}), confidence=0.5, lift=2.5)]),
 RelationRecord(items=frozenset({'cerveja', 'manteiga'}), support=0.1, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'cerveja', 'manteiga'}), confidence=0.1, lift=1.0), OrderedStatistic(items_base=frozenset({'cerveja'}), items_add=frozenset({'manteiga'}), confidence=0.5, lift=1.0), OrderedStatistic(items_base=frozenset({'manteiga'}), items_add=frozenset({'cerveja'}), confidence=0.2, lift=1.0)]),
 RelationRecord(items=frozenset({'cerveja', 'nan'}), support=0.1, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'cerveja', 'nan'}), confidence=0.1, lift=1.0), OrderedStatistic(items_base=frozenset({'cerveja'}), items_add=frozenset({'nan'}), confidence=0.5, lift=0.625), OrderedStatistic(items_base=frozenset({'nan'}), items_add=frozenset({'cerveja'}), confidence=0.125, lift=0.625)]),
 RelationRecord(items=frozenset({'pao', 'cerveja'}), support=0.1, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'pao', 'cerveja'}), confidence=0.1, lift=1.0), OrderedStatistic(items_base=frozenset({'cerveja'}), items_add=frozenset({'pao'}), confidence=0.5, lift=1.0), OrderedStatistic(items_base=frozenset({'pao'}), items_add=frozenset({'cerveja'}), confidence=0.2, lift=1.0)]),
 RelationRecord(items=frozenset({'feijao', 'nan'}), support=0.2, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'feijao', 'nan'}), confidence=0.2, lift=1.0), OrderedStatistic(items_base=frozenset({'feijao'}), items_add=frozenset({'nan'}), confidence=1.0, lift=1.25), OrderedStatistic(items_base=frozenset({'nan'}), items_add=frozenset({'feijao'}), confidence=0.25, lift=1.25)]),
 RelationRecord(items=frozenset({'leite', 'manteiga'}), support=0.2, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'leite', 'manteiga'}), confidence=0.2, lift=1.0), OrderedStatistic(items_base=frozenset({'leite'}), items_add=frozenset({'manteiga'}), confidence=1.0, lift=2.0), OrderedStatistic(items_base=frozenset({'manteiga'}), items_add=frozenset({'leite'}), confidence=0.4, lift=2.0)]),
 RelationRecord(items=frozenset({'leite', 'pao'}), support=0.2, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'leite', 'pao'}), confidence=0.2, lift=1.0), OrderedStatistic(items_base=frozenset({'leite'}), items_add=frozenset({'pao'}), confidence=1.0, lift=2.0), OrderedStatistic(items_base=frozenset({'pao'}), items_add=frozenset({'leite'}), confidence=0.4, lift=2.0)]),
 RelationRecord(items=frozenset({'manteiga', 'nan'}), support=0.3, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'manteiga', 'nan'}), confidence=0.3, lift=1.0), OrderedStatistic(items_base=frozenset({'manteiga'}), items_add=frozenset({'nan'}), confidence=0.6, lift=0.7499999999999999), OrderedStatistic(items_base=frozenset({'nan'}), items_add=frozenset({'manteiga'}), confidence=0.37499999999999994, lift=0.7499999999999999)]),
 RelationRecord(items=frozenset({'pao', 'manteiga'}), support=0.4, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'pao', 'manteiga'}), confidence=0.4, lift=1.0), OrderedStatistic(items_base=frozenset({'manteiga'}), items_add=frozenset({'pao'}), confidence=0.8, lift=1.6), OrderedStatistic(items_base=frozenset({'pao'}), items_add=frozenset({'manteiga'}), confidence=0.8, lift=1.6)]),
 RelationRecord(items=frozenset({'pao', 'nan'}), support=0.3, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'pao', 'nan'}), confidence=0.3, lift=1.0), OrderedStatistic(items_base=frozenset({'nan'}), items_add=frozenset({'pao'}), confidence=0.37499999999999994, lift=0.7499999999999999), OrderedStatistic(items_base=frozenset({'pao'}), items_add=frozenset({'nan'}), confidence=0.6, lift=0.7499999999999999)]),
 RelationRecord(items=frozenset({'feijao', 'arroz', 'nan'}), support=0.1, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'feijao', 'arroz', 'nan'}), confidence=0.1, lift=1.0), OrderedStatistic(items_base=frozenset({'arroz'}), items_add=frozenset({'feijao', 'nan'}), confidence=0.5, lift=2.5), OrderedStatistic(items_base=frozenset({'feijao'}), items_add=frozenset({'arroz', 'nan'}), confidence=0.5, lift=2.5), OrderedStatistic(items_base=frozenset({'nan'}), items_add=frozenset({'feijao', 'arroz'}), confidence=0.125, lift=1.25), OrderedStatistic(items_base=frozenset({'feijao', 'arroz'}), items_add=frozenset({'nan'}), confidence=1.0, lift=1.25), OrderedStatistic(items_base=frozenset({'arroz', 'nan'}), items_add=frozenset({'feijao'}), confidence=0.5, lift=2.5), OrderedStatistic(items_base=frozenset({'feijao', 'nan'}), items_add=frozenset({'arroz'}), confidence=0.5, lift=2.5)]),
 RelationRecord(items=frozenset({'leite', 'cafe', 'manteiga'}), support=0.1, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'leite', 'cafe', 'manteiga'}), confidence=0.1, lift=1.0), OrderedStatistic(items_base=frozenset({'cafe'}), items_add=frozenset({'leite', 'manteiga'}), confidence=0.33333333333333337, lift=1.6666666666666667), OrderedStatistic(items_base=frozenset({'leite'}), items_add=frozenset({'cafe', 'manteiga'}), confidence=0.5, lift=1.6666666666666667), OrderedStatistic(items_base=frozenset({'manteiga'}), items_add=frozenset({'leite', 'cafe'}), confidence=0.2, lift=2.0), OrderedStatistic(items_base=frozenset({'leite', 'cafe'}), items_add=frozenset({'manteiga'}), confidence=1.0, lift=2.0), OrderedStatistic(items_base=frozenset({'cafe', 'manteiga'}), items_add=frozenset({'leite'}), confidence=0.33333333333333337, lift=1.6666666666666667), OrderedStatistic(items_base=frozenset({'leite', 'manteiga'}), items_add=frozenset({'cafe'}), confidence=0.5, lift=1.6666666666666667)]),
 RelationRecord(items=frozenset({'leite', 'cafe', 'pao'}), support=0.1, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'leite', 'cafe', 'pao'}), confidence=0.1, lift=1.0), OrderedStatistic(items_base=frozenset({'cafe'}), items_add=frozenset({'leite', 'pao'}), confidence=0.33333333333333337, lift=1.6666666666666667), OrderedStatistic(items_base=frozenset({'leite'}), items_add=frozenset({'pao', 'cafe'}), confidence=0.5, lift=1.6666666666666667), OrderedStatistic(items_base=frozenset({'pao'}), items_add=frozenset({'leite', 'cafe'}), confidence=0.2, lift=2.0), OrderedStatistic(items_base=frozenset({'leite', 'cafe'}), items_add=frozenset({'pao'}), confidence=1.0, lift=2.0), OrderedStatistic(items_base=frozenset({'pao', 'cafe'}), items_add=frozenset({'leite'}), confidence=0.33333333333333337, lift=1.6666666666666667), OrderedStatistic(items_base=frozenset({'leite', 'pao'}), items_add=frozenset({'cafe'}), confidence=0.5, lift=1.6666666666666667)]),
 RelationRecord(items=frozenset({'cafe', 'manteiga', 'nan'}), support=0.2, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'cafe', 'manteiga', 'nan'}), confidence=0.2, lift=1.0), OrderedStatistic(items_base=frozenset({'cafe'}), items_add=frozenset({'manteiga', 'nan'}), confidence=0.6666666666666667, lift=2.2222222222222228), OrderedStatistic(items_base=frozenset({'manteiga'}), items_add=frozenset({'cafe', 'nan'}), confidence=0.4, lift=2.0), OrderedStatistic(items_base=frozenset({'nan'}), items_add=frozenset({'cafe', 'manteiga'}), confidence=0.25, lift=0.8333333333333334), OrderedStatistic(items_base=frozenset({'cafe', 'manteiga'}), items_add=frozenset({'nan'}), confidence=0.6666666666666667, lift=0.8333333333333334), OrderedStatistic(items_base=frozenset({'cafe', 'nan'}), items_add=frozenset({'manteiga'}), confidence=1.0, lift=2.0), OrderedStatistic(items_base=frozenset({'manteiga', 'nan'}), items_add=frozenset({'cafe'}), confidence=0.6666666666666667, lift=2.2222222222222228)]),
 RelationRecord(items=frozenset({'pao', 'cafe', 'manteiga'}), support=0.3, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'pao', 'cafe', 'manteiga'}), confidence=0.3, lift=1.0), OrderedStatistic(items_base=frozenset({'cafe'}), items_add=frozenset({'pao', 'manteiga'}), confidence=1.0, lift=2.5), OrderedStatistic(items_base=frozenset({'manteiga'}), items_add=frozenset({'pao', 'cafe'}), confidence=0.6, lift=2.0), OrderedStatistic(items_base=frozenset({'pao'}), items_add=frozenset({'cafe', 'manteiga'}), confidence=0.6, lift=2.0), OrderedStatistic(items_base=frozenset({'cafe', 'manteiga'}), items_add=frozenset({'pao'}), confidence=1.0, lift=2.0), OrderedStatistic(items_base=frozenset({'pao', 'cafe'}), items_add=frozenset({'manteiga'}), confidence=1.0, lift=2.0), OrderedStatistic(items_base=frozenset({'pao', 'manteiga'}), items_add=frozenset({'cafe'}), confidence=0.7499999999999999, lift=2.4999999999999996)]),
 RelationRecord(items=frozenset({'pao', 'cafe', 'nan'}), support=0.2, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'pao', 'cafe', 'nan'}), confidence=0.2, lift=1.0), OrderedStatistic(items_base=frozenset({'cafe'}), items_add=frozenset({'pao', 'nan'}), confidence=0.6666666666666667, lift=2.2222222222222228), OrderedStatistic(items_base=frozenset({'nan'}), items_add=frozenset({'pao', 'cafe'}), confidence=0.25, lift=0.8333333333333334), OrderedStatistic(items_base=frozenset({'pao'}), items_add=frozenset({'cafe', 'nan'}), confidence=0.4, lift=2.0), OrderedStatistic(items_base=frozenset({'cafe', 'nan'}), items_add=frozenset({'pao'}), confidence=1.0, lift=2.0), OrderedStatistic(items_base=frozenset({'pao', 'cafe'}), items_add=frozenset({'nan'}), confidence=0.6666666666666667, lift=0.8333333333333334), OrderedStatistic(items_base=frozenset({'pao', 'nan'}), items_add=frozenset({'cafe'}), confidence=0.6666666666666667, lift=2.2222222222222228)]),
 RelationRecord(items=frozenset({'leite', 'cerveja', 'manteiga'}), support=0.1, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'leite', 'cerveja', 'manteiga'}), confidence=0.1, lift=1.0), OrderedStatistic(items_base=frozenset({'cerveja'}), items_add=frozenset({'leite', 'manteiga'}), confidence=0.5, lift=2.5), OrderedStatistic(items_base=frozenset({'leite'}), items_add=frozenset({'cerveja', 'manteiga'}), confidence=0.5, lift=5.0), OrderedStatistic(items_base=frozenset({'manteiga'}), items_add=frozenset({'leite', 'cerveja'}), confidence=0.2, lift=2.0), OrderedStatistic(items_base=frozenset({'leite', 'cerveja'}), items_add=frozenset({'manteiga'}), confidence=1.0, lift=2.0), OrderedStatistic(items_base=frozenset({'cerveja', 'manteiga'}), items_add=frozenset({'leite'}), confidence=1.0, lift=5.0), OrderedStatistic(items_base=frozenset({'leite', 'manteiga'}), items_add=frozenset({'cerveja'}), confidence=0.5, lift=2.5)]),
 RelationRecord(items=frozenset({'leite', 'pao', 'cerveja'}), support=0.1, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'leite', 'pao', 'cerveja'}), confidence=0.1, lift=1.0), OrderedStatistic(items_base=frozenset({'cerveja'}), items_add=frozenset({'leite', 'pao'}), confidence=0.5, lift=2.5), OrderedStatistic(items_base=frozenset({'leite'}), items_add=frozenset({'pao', 'cerveja'}), confidence=0.5, lift=5.0), OrderedStatistic(items_base=frozenset({'pao'}), items_add=frozenset({'leite', 'cerveja'}), confidence=0.2, lift=2.0), OrderedStatistic(items_base=frozenset({'leite', 'cerveja'}), items_add=frozenset({'pao'}), confidence=1.0, lift=2.0), OrderedStatistic(items_base=frozenset({'pao', 'cerveja'}), items_add=frozenset({'leite'}), confidence=1.0, lift=5.0), OrderedStatistic(items_base=frozenset({'leite', 'pao'}), items_add=frozenset({'cerveja'}), confidence=0.5, lift=2.5)]),
 RelationRecord(items=frozenset({'pao', 'cerveja', 'manteiga'}), support=0.1, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'pao', 'cerveja', 'manteiga'}), confidence=0.1, lift=1.0), OrderedStatistic(items_base=frozenset({'cerveja'}), items_add=frozenset({'pao', 'manteiga'}), confidence=0.5, lift=1.25), OrderedStatistic(items_base=frozenset({'manteiga'}), items_add=frozenset({'pao', 'cerveja'}), confidence=0.2, lift=2.0), OrderedStatistic(items_base=frozenset({'pao'}), items_add=frozenset({'cerveja', 'manteiga'}), confidence=0.2, lift=2.0), OrderedStatistic(items_base=frozenset({'cerveja', 'manteiga'}), items_add=frozenset({'pao'}), confidence=1.0, lift=2.0), OrderedStatistic(items_base=frozenset({'pao', 'cerveja'}), items_add=frozenset({'manteiga'}), confidence=1.0, lift=2.0), OrderedStatistic(items_base=frozenset({'pao', 'manteiga'}), items_add=frozenset({'cerveja'}), confidence=0.25, lift=1.25)]),
 RelationRecord(items=frozenset({'leite', 'pao', 'manteiga'}), support=0.2, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'leite', 'pao', 'manteiga'}), confidence=0.2, lift=1.0), OrderedStatistic(items_base=frozenset({'leite'}), items_add=frozenset({'pao', 'manteiga'}), confidence=1.0, lift=2.5), OrderedStatistic(items_base=frozenset({'manteiga'}), items_add=frozenset({'leite', 'pao'}), confidence=0.4, lift=2.0), OrderedStatistic(items_base=frozenset({'pao'}), items_add=frozenset({'leite', 'manteiga'}), confidence=0.4, lift=2.0), OrderedStatistic(items_base=frozenset({'leite', 'manteiga'}), items_add=frozenset({'pao'}), confidence=1.0, lift=2.0), OrderedStatistic(items_base=frozenset({'leite', 'pao'}), items_add=frozenset({'manteiga'}), confidence=1.0, lift=2.0), OrderedStatistic(items_base=frozenset({'pao', 'manteiga'}), items_add=frozenset({'leite'}), confidence=0.5, lift=2.5)]),
 RelationRecord(items=frozenset({'pao', 'manteiga', 'nan'}), support=0.2, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'pao', 'manteiga', 'nan'}), confidence=0.2, lift=1.0), OrderedStatistic(items_base=frozenset({'manteiga'}), items_add=frozenset({'pao', 'nan'}), confidence=0.4, lift=1.3333333333333335), OrderedStatistic(items_base=frozenset({'nan'}), items_add=frozenset({'pao', 'manteiga'}), confidence=0.25, lift=0.625), OrderedStatistic(items_base=frozenset({'pao'}), items_add=frozenset({'manteiga', 'nan'}), confidence=0.4, lift=1.3333333333333335), OrderedStatistic(items_base=frozenset({'manteiga', 'nan'}), items_add=frozenset({'pao'}), confidence=0.6666666666666667, lift=1.3333333333333335), OrderedStatistic(items_base=frozenset({'pao', 'manteiga'}), items_add=frozenset({'nan'}), confidence=0.5, lift=0.625), OrderedStatistic(items_base=frozenset({'pao', 'nan'}), items_add=frozenset({'manteiga'}), confidence=0.6666666666666667, lift=1.3333333333333335)]),

In [26]:
len(resultados) # tamanho dos resultados, muito alto, as regras estão dentro da função: ordered_statistics

# também há os support

38

In [30]:
# chamando a função apriori, coletando as listas: transacoes

# vamos configurar melhor os parâmetros
# min_support mínimo suporte de 0,3
# min_confidence, valor da confiança será 0,8
# 
regras = apriori(transacoes, min_support = 0.3, min_confidence = 0.8)
resultados = list(regras)
print(resultados)
print('\nquantidade de dados:', len(resultados)) # quantidade de dados diminuiram

[RelationRecord(items=frozenset({'nan'}), support=0.8, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'nan'}), confidence=0.8, lift=1.0)]), RelationRecord(items=frozenset({'cafe', 'manteiga'}), support=0.3, ordered_statistics=[OrderedStatistic(items_base=frozenset({'cafe'}), items_add=frozenset({'manteiga'}), confidence=1.0, lift=2.0)]), RelationRecord(items=frozenset({'pao', 'cafe'}), support=0.3, ordered_statistics=[OrderedStatistic(items_base=frozenset({'cafe'}), items_add=frozenset({'pao'}), confidence=1.0, lift=2.0)]), RelationRecord(items=frozenset({'pao', 'manteiga'}), support=0.4, ordered_statistics=[OrderedStatistic(items_base=frozenset({'manteiga'}), items_add=frozenset({'pao'}), confidence=0.8, lift=1.6), OrderedStatistic(items_base=frozenset({'pao'}), items_add=frozenset({'manteiga'}), confidence=0.8, lift=1.6)]), RelationRecord(items=frozenset({'pao', 'cafe', 'manteiga'}), support=0.3, ordered_statistics=[OrderedStatistic(items_base=frozenset({'cafe'}), items_add=frozenset({'pao', 'manteiga'}), confidence=1.0, lift=2.5), OrderedStatistic(items_base=frozenset({'cafe', 'manteiga'}), items_add=frozenset({'pao'}), confidence=1.0, lift=2.0), OrderedStatistic(items_base=frozenset({'pao', 'cafe'}), items_add=frozenset({'manteiga'}), confidence=1.0, lift=2.0)])]

quantidade de dados: 5

In [36]:
#!pip install prettyprinter

In [31]:
# o ideal será só os produtos, não o nan

In [37]:
# chamando a função apriori, coletando as listas: transacoes

# vamos configurar os parâmetros
# min_support mínimo suporte de 0,3
# min_confidence, valor da confiança será 0,8
# min_lift, definir o quanto os produtos se associam, sem regras que não são relevantes, são 2 produtos ou mais pelo lift.

regras = apriori(transacoes, min_support = 0.3, min_confidence = 0.8, min_lift = 2)
resultados = list(regras)
import prettyprinter as pp
pp.pprint(resultados)
print('\nquantidade de dados:', len(resultados)) # quantidade de dados diminuiram

[
    apyori.RelationRecord(
        items=frozenset(['cafe', 'manteiga']),
        support=0.3,
        ordered_statistics=[
            apyori.OrderedStatistic(
                items_base=frozenset(['cafe']),
                items_add=frozenset(['manteiga']),
                confidence=1.0,
                lift=2.0
            )
        ]
    ),
    apyori.RelationRecord(
        items=frozenset(['pao', 'cafe']),
        support=0.3,
        ordered_statistics=[
            apyori.OrderedStatistic(
                items_base=frozenset(['cafe']),
                items_add=frozenset(['pao']),
                confidence=1.0,
                lift=2.0
            )
        ]
    ),
    apyori.RelationRecord(
        items=frozenset(['pao', 'cafe', 'manteiga']),
        support=0.3,
        ordered_statistics=[
            apyori.OrderedStatistic(
                items_base=frozenset(['cafe']),
                items_add=frozenset(['pao', 'manteiga']),
                confidence=1.0,
                lift=2.5
            ),
            apyori.OrderedStatistic(
                items_base=frozenset(['cafe', 'manteiga']),
                items_add=frozenset(['pao']),
                confidence=1.0,
                lift=2.0
            ),
            apyori.OrderedStatistic(
                items_base=frozenset(['pao', 'cafe']),
                items_add=frozenset(['manteiga']),
                confidence=1.0,
                lift=2.0
            )
        ]
    )
]

quantidade de dados: 3

In [38]:
resultados[0]

RelationRecord(items=frozenset({'cafe', 'manteiga'}), support=0.3, ordered_statistics=[OrderedStatistic(items_base=frozenset({'cafe'}), items_add=frozenset({'manteiga'}), confidence=1.0, lift=2.0)])

In [39]:
resultados[1]

RelationRecord(items=frozenset({'pao', 'cafe'}), support=0.3, ordered_statistics=[OrderedStatistic(items_base=frozenset({'cafe'}), items_add=frozenset({'pao'}), confidence=1.0, lift=2.0)])

In [40]:
resultados[2]

RelationRecord(items=frozenset({'pao', 'cafe', 'manteiga'}), support=0.3, ordered_statistics=[OrderedStatistic(items_base=frozenset({'cafe'}), items_add=frozenset({'pao', 'manteiga'}), confidence=1.0, lift=2.5), OrderedStatistic(items_base=frozenset({'cafe', 'manteiga'}), items_add=frozenset({'pao'}), confidence=1.0, lift=2.0), OrderedStatistic(items_base=frozenset({'pao', 'cafe'}), items_add=frozenset({'manteiga'}), confidence=1.0, lift=2.0)])

Itens selecionados:
items=frozenset(['pao', 'cafe', 'manteiga']),

suporte: 

support=0.3, aparece em 30% das transações os 3 itens.

ordered_statistics= onde há as regras

com instância de 3 regras

café => manteiga e pão |
confiança 1, lift =>2,5

café e manteiga => pão |
confiança 1 e lift 2

café e pão => manteiga |
confiança 1 e lift 2

Criaremos um dataframe

In [41]:
resultados[2][0]

frozenset({'cafe', 'manteiga', 'pao'})

In [43]:
resultados[2][1] # suporte, 30% pelo menos de frequência

0.3

In [44]:
r = resultados[2][2]
r # resultados com todas as regras

[OrderedStatistic(items_base=frozenset({'cafe'}), items_add=frozenset({'pao', 'manteiga'}), confidence=1.0, lift=2.5),
 OrderedStatistic(items_base=frozenset({'cafe', 'manteiga'}), items_add=frozenset({'pao'}), confidence=1.0, lift=2.0),
 OrderedStatistic(items_base=frozenset({'pao', 'cafe'}), items_add=frozenset({'manteiga'}), confidence=1.0, lift=2.0)]

acessar item a item

In [45]:
len(r)

3

In [47]:
for a in range(len(r)):
    print(r[a])
    print()

OrderedStatistic(items_base=frozenset({'cafe'}), items_add=frozenset({'pao', 'manteiga'}), confidence=1.0, lift=2.5)

OrderedStatistic(items_base=frozenset({'cafe', 'manteiga'}), items_add=frozenset({'pao'}), confidence=1.0, lift=2.0)

OrderedStatistic(items_base=frozenset({'pao', 'cafe'}), items_add=frozenset({'manteiga'}), confidence=1.0, lift=2.0)

In [48]:
r[2]

OrderedStatistic(items_base=frozenset({'pao', 'cafe'}), items_add=frozenset({'manteiga'}), confidence=1.0, lift=2.0)

In [49]:
r[2][0] # primeira regra "se"

frozenset({'cafe', 'pao'})

In [51]:
r[2][1] # regra depois do "então"

frozenset({'manteiga'})

In [52]:
r[2][2] # confiança

1.0

In [53]:
r[2][3] # valores do lift

2.0

# 20.9) Codificar para extrair todas as regras de associação

Visualização das regras

In [56]:
for resultado in resultados:
  #print(resultado)
  s = resultado[1] # posição 1
  print(s) # dados de suporte
  result_rules = resultado[2] # posição 2 all rules
  print(result_rules)

0.3
[OrderedStatistic(items_base=frozenset({'cafe'}), items_add=frozenset({'manteiga'}), confidence=1.0, lift=2.0)]
0.3
[OrderedStatistic(items_base=frozenset({'cafe'}), items_add=frozenset({'pao'}), confidence=1.0, lift=2.0)]
0.3
[OrderedStatistic(items_base=frozenset({'cafe'}), items_add=frozenset({'pao', 'manteiga'}), confidence=1.0, lift=2.5), OrderedStatistic(items_base=frozenset({'cafe', 'manteiga'}), items_add=frozenset({'pao'}), confidence=1.0, lift=2.0), OrderedStatistic(items_base=frozenset({'pao', 'cafe'}), items_add=frozenset({'manteiga'}), confidence=1.0, lift=2.0)]

In [57]:

for resultado in resultados:
  #print(resultado)
  s = resultado[1] # posição 1
  #print(s) # dados de suporte
  result_rules = resultado[2] # posição 2 todas as regras
  #print(result_rule) #linha da regra
  for result_rule in result_rules:
    print(result_rule)

OrderedStatistic(items_base=frozenset({'cafe'}), items_add=frozenset({'manteiga'}), confidence=1.0, lift=2.0)
OrderedStatistic(items_base=frozenset({'cafe'}), items_add=frozenset({'pao'}), confidence=1.0, lift=2.0)
OrderedStatistic(items_base=frozenset({'cafe'}), items_add=frozenset({'pao', 'manteiga'}), confidence=1.0, lift=2.5)
OrderedStatistic(items_base=frozenset({'cafe', 'manteiga'}), items_add=frozenset({'pao'}), confidence=1.0, lift=2.0)
OrderedStatistic(items_base=frozenset({'pao', 'cafe'}), items_add=frozenset({'manteiga'}), confidence=1.0, lift=2.0)

In [59]:


A = [] # "regra se"
B = [] # "regra então"
# 3 métricas abaixo
suporte = []
confianca = []
lift = []

for resultado in resultados:
  #print(resultado)
  s = resultado[1] # posição 1
  #print(s) # dados de suporte
  result_rules = resultado[2] # posição 2 todas as regras
  #print(result_rule) #linha da regra 
  for result_rule in result_rules: 
    #print(result_rule) # percorrendo as regras
    a = list(result_rule[0])
    b = list(result_rule[1])
    c = result_rule[2]
    l = result_rule[3]
    print(a, ' - ', b, ' - ', c, ' - ', l)
    A.append(a) # se
    B.append(b) # então
    suporte.append(s) # suporte geral 30%
    confianca.append(c) # confiança
    lift.append(l) # lift

['cafe']  -  ['manteiga']  -  1.0  -  2.0
['cafe']  -  ['pao']  -  1.0  -  2.0
['cafe']  -  ['pao', 'manteiga']  -  1.0  -  2.5
['cafe', 'manteiga']  -  ['pao']  -  1.0  -  2.0
['pao', 'cafe']  -  ['manteiga']  -  1.0  -  2.0

In [60]:
A

[['cafe'], ['cafe'], ['cafe'], ['cafe', 'manteiga'], ['pao', 'cafe']]

In [61]:
B

[['manteiga'], ['pao'], ['pao', 'manteiga'], ['pao'], ['manteiga']]

In [62]:
s

0.3

In [63]:
confianca

[1.0, 1.0, 1.0, 1.0, 1.0]

In [64]:
lift

[2.0, 2.0, 2.5, 2.0, 2.0]

In [65]:
rules_df = pd.DataFrame({'A': A, 'B': B, 'suporte': suporte, 'confianca': confianca, 'lift': lift})

In [66]:
display(rules_df)

                  A                B  suporte  confianca  lift
0            [cafe]       [manteiga]      0.3        1.0   2.0
1            [cafe]            [pao]      0.3        1.0   2.0
2            [cafe]  [pao, manteiga]      0.3        1.0   2.5
3  [cafe, manteiga]            [pao]      0.3        1.0   2.0
4       [pao, cafe]       [manteiga]      0.3        1.0   2.0

In [68]:
rules_df.sort_values(by = 'lift', ascending = False) # ordenação correta pelo lift.

                  A                B  suporte  confianca  lift
2            [cafe]  [pao, manteiga]      0.3        1.0   2.5
0            [cafe]       [manteiga]      0.3        1.0   2.0
1            [cafe]            [pao]      0.3        1.0   2.0
3  [cafe, manteiga]            [pao]      0.3        1.0   2.0
4       [pao, cafe]       [manteiga]      0.3        1.0   2.0