# 1) Exercício: Regra de Associação Algoritmo Apriori

In [60]:
#Instalado já a biblioteca 

#!pip install apyori
import os
import pandas as pd

from apyori import apriori

In [61]:
#!pip install kagglehub

In [62]:

# para acessar os dados da kaggle
import kagglehub

# Base de dados Market Basket Analysis

## Download e preparação dos dados

Desta vez, você vai utilizar uma base de dados disponível no Kaggle, que contém um histórico de aquisição de itens em uma loja. Cada linha representa a transação de um item, com o ID da compra, quantidade, data, preço, ID do cliente e país.

https://www.kaggle.com/datasets/aslanahmedov/market-basket-analysis

> * Número de Linhas: 522065
> * Número de Atributos: 7
>   * BillNo: Número de 6 dígitos atribuído a cada transação. Nominal.
>   * Itemname: Nome do produto. Nominal.
>   * Quantity: As quantidades de cada produto por transação. Numérico.
>   * Date: O dia e a hora em que cada transação foi gerada. Numérico.
>   * Price: Preço do produto. Numérico.
>   * CustomerID: Número de 5 dígitos atribuído a cada cliente. Nominal.
>   * Country: Nome do país onde cada cliente reside. Nominal.

In [63]:
path = kagglehub.dataset_download("aslanahmedov/market-basket-analysis")
# acesso a base de dados.
print("Path to dataset files:", path)

Path to dataset files: /home/fabiene/.cache/kagglehub/datasets/aslanahmedov/market-basket-analysis/versions/2

In [64]:
!ls {path}

Assignment-1_Data.csv  Assignment-1_Data.xlsx

no linux:

(base) :~/.cache/kagglehub/datasets/aslanahmedov/market-basket-analysis$ ls -ltr

total 4
drwxrwxr-x 3 fabiene fabiene 4096 ago 10 16:48 versions

-rw-rw-r-- 1 fabiene fabiene    0 ago 10 16:48 2.complete

(base) :~/.cache/kagglehub/datasets/aslanahmedov/market-basket-analysis$

no linux

(base) fabiene@xxxxx:~/.cache/kagglehub/datasets/aslanahmedov/market-basket-analysis/versions/2$ ls -ltr

total 57968

-rw-rw-r-- 1 fabiene fabiene 41204583 ago 10 16:48 Assignment-1_Data.csv

-rw-rw-r-- 1 fabiene fabiene 18146884 ago 10 16:48 Assignment-1_Data.xlsx

(base) fabiene@xxxxxx:~/.cache/kagglehub/datasets/aslanahmedov/market-basket-analysis/versions/2$

O dataset é fornecido em formato `csv` e `xlsx` (Excel). Nós vamos utilizar o arquivo `csv`, então vamos inspecionar suas primeiras linhas.

In [65]:
# ecolhido coletar os dados em .csv
!head {path}/Assignment-1_Data.csv

﻿BillNo;Itemname;Quantity;Date;Price;CustomerID;Country
536365;WHITE HANGING HEART T-LIGHT HOLDER;6;01.12.2010 08:26;2,55;17850;United Kingdom
536365;WHITE METAL LANTERN;6;01.12.2010 08:26;3,39;17850;United Kingdom
536365;CREAM CUPID HEARTS COAT HANGER;8;01.12.2010 08:26;2,75;17850;United Kingdom
536365;KNITTED UNION FLAG HOT WATER BOTTLE;6;01.12.2010 08:26;3,39;17850;United Kingdom
536365;RED WOOLLY HOTTIE WHITE HEART.;6;01.12.2010 08:26;3,39;17850;United Kingdom
536365;SET 7 BABUSHKA NESTING BOXES;2;01.12.2010 08:26;7,65;17850;United Kingdom
536365;GLASS STAR FROSTED T-LIGHT HOLDER;6;01.12.2010 08:26;4,25;17850;United Kingdom
536366;HAND WARMER UNION JACK;6;01.12.2010 08:28;1,85;17850;United Kingdom
536366;HAND WARMER RED POLKA DOT;6;01.12.2010 08:28;1,85;17850;United Kingdom

O arquivo contém um cabeçalho, e os campos são separados por `;`. Então, vamos carregar no Python levando isso em consideração.

In [66]:
mba = pd.read_csv(os.path.join(path, "Assignment-1_Data.csv"), delimiter=";")
mba.tail()

/tmp/ipykernel_5959/156717607.py:1: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  mba = pd.read_csv(os.path.join(path, "Assignment-1_Data.csv"), delimiter=";")

,BillNo,Itemname,Quantity,Date,Price,CustomerID,Country
522059,581587,PACK OF 20 SPACEBOY NAPKINS,12,09.12.2011 12:50,"0,85",12680.0,France
522060,581587,CHILDREN'S APRON DOLLY GIRL,6,09.12.2011 12:50,"2,1",12680.0,France
522061,581587,CHILDRENS CUTLERY DOLLY GIRL,4,09.12.2011 12:50,"4,15",12680.0,France
522062,581587,CHILDRENS CUTLERY CIRCUS PARADE,4,09.12.2011 12:50,"4,15",12680.0,France
522063,581587,BAKING SET 9 PIECE RETROSPOT,3,09.12.2011 12:50,"4,95",12680.0,France

Perceba que são mais de 500 mil transações.

a coluna Itemname é a lista dos produtos

In [67]:
list(mba['Itemname'].unique())

['WHITE HANGING HEART T-LIGHT HOLDER',
 'WHITE METAL LANTERN',
 'CREAM CUPID HEARTS COAT HANGER',
 'KNITTED UNION FLAG HOT WATER BOTTLE',
 'RED WOOLLY HOTTIE WHITE HEART.',
 'SET 7 BABUSHKA NESTING BOXES',
 'GLASS STAR FROSTED T-LIGHT HOLDER',
 'HAND WARMER UNION JACK',
 'HAND WARMER RED POLKA DOT',
 'ASSORTED COLOUR BIRD ORNAMENT',
 "POPPY'S PLAYHOUSE BEDROOM",
 "POPPY'S PLAYHOUSE KITCHEN",
 'FELTCRAFT PRINCESS CHARLOTTE DOLL',
 'IVORY KNITTED MUG COSY',
 'BOX OF 6 ASSORTED COLOUR TEASPOONS',
 'BOX OF VINTAGE JIGSAW BLOCKS',
 'BOX OF VINTAGE ALPHABET BLOCKS',
 'HOME BUILDING BLOCK WORD',
 'LOVE BUILDING BLOCK WORD',
 'RECIPE BOX WITH METAL HEART',
 'DOORMAT NEW ENGLAND',
 'JAM MAKING SET WITH JARS',
 'RED COAT RACK PARIS FASHION',
 'YELLOW COAT RACK PARIS FASHION',
 'BLUE COAT RACK PARIS FASHION',
 'BATH BUILDING BLOCK WORD',
 'ALARM CLOCK BAKELIKE PINK',
 'ALARM CLOCK BAKELIKE RED',
 'ALARM CLOCK BAKELIKE GREEN',
 'PANDA AND BUNNIES STICKER SHEET',
 'STARS GIFT TAPE',
 'INFLATABLE POLITICAL GLOBE',
 'VINTAGE HEADS AND TAILS CARD GAME',
 'SET/2 RED RETROSPOT TEA TOWELS',
 'ROUND SNACK BOXES SET OF4 WOODLAND',
 'SPACEBOY LUNCH BOX',
 'LUNCH BOX I LOVE LONDON',
 'CIRCUS PARADE LUNCH BOX',
 'CHARLOTTE BAG DOLLY GIRL DESIGN',
 'RED TOADSTOOL LED NIGHT LIGHT',
 'SET 2 TEA TOWELS I LOVE LONDON',
 'VINTAGE SEASIDE JIGSAW PUZZLES',
 'MINI JIGSAW CIRCUS PARADE',
 'MINI JIGSAW SPACEBOY',
 'MINI PAINT SET VINTAGE',
 'POSTAGE',
 "PAPER CHAIN KIT 50'S CHRISTMAS",
 'EDWARDIAN PARASOL RED',
 'RETRO COFFEE MUGS ASSORTED',
 'SAVE THE PLANET MUG',
 'VINTAGE BILLBOARD DRINK ME MUG',
 'VINTAGE BILLBOARD LOVE/HATE MUG',
 'WOOD 2 DRAWER CABINET WHITE FINISH',
 'WOOD S/3 CABINET ANT WHITE FINISH',
 'WOODEN PICTURE FRAME WHITE FINISH',
 'WOODEN FRAME ANTIQUE WHITE',
 'VICTORIAN SEWING BOX LARGE',
 'HOT WATER BOTTLE TEA AND SYMPATHY',
 'RED HANGING HEART T-LIGHT HOLDER',
 'JUMBO BAG PINK POLKADOT',
 'JUMBO  BAG BAROQUE BLACK WHITE',
 'JUMBO BAG CHARLIE AND LOLA TOYS',
 'STRAWBERRY CHARLOTTE BAG',
 'RED 3 PIECE RETROSPOT CUTLERY SET',
 'BLUE 3 PIECE POLKADOT CUTLERY SET',
 'SET/6 RED SPOTTY PAPER PLATES',
 'LUNCH BAG RED RETROSPOT',
 'STRAWBERRY LUNCH BOX WITH CUTLERY',
 'LUNCH BOX WITH CUTLERY RETROSPOT',
 'PACK OF 72 RETROSPOT CAKE CASES',
 'PACK OF 60 DINOSAUR CAKE CASES',
 'PACK OF 60 PINK PAISLEY CAKE CASES',
 '60 TEATIME FAIRY CAKE CASES',
 'TOMATO CHARLIE+LOLA COASTER SET',
 'CHARLIE & LOLA WASTEPAPER BIN FLORA',
 'RED CHARLIE+LOLA PERSONAL DOORSIGN',
 'JUMBO STORAGE BAG SUKI',
 'JUMBO BAG PINK VINTAGE PAISLEY',
 'JAM MAKING SET PRINTED',
 'RETROSPOT TEA SET CERAMIC 11 PC',
 'GIRLY PINK TOOL SET',
 'JUMBO SHOPPER VINTAGE RED PAISLEY',
 'AIRLINE LOUNGE,METAL SIGN',
 'WHITE SPOT RED CERAMIC DRAWER KNOB',
 'RED DRAWER KNOB ACRYLIC EDWARDIAN',
 'CLEAR DRAWER KNOB ACRYLIC EDWARDIAN',
 'PHOTO CLIP LINE',
 'FELT EGG COSY CHICKEN',
 'PIGGY BANK RETROSPOT',
 'SKULL SHOULDER BAG',
 "YOU'RE CONFUSING ME METAL SIGN",
 'COOK WITH WINE METAL SIGN',
 'GIN + TONIC DIET METAL SIGN',
 'YELLOW BREAKFAST CUP AND SAUCER',
 'PINK BREAKFAST CUP AND SAUCER',
 'PAPER CHAIN KIT RETROSPOT',
 'SMALL HEART FLOWERS HOOK',
 'TEA TIME DES TEA COSY',
 'FELT EGG COSY WHITE RABBIT',
 'ZINC WILLIE WINKIE  CANDLE STICK',
 'CERAMIC CHERRY CAKE MONEY BANK',
 'RETROSPOT LARGE MILK JUG',
 'SET OF 6 FUNKY BEAKERS',
 'EDWARDIAN PARASOL BLACK',
 'EDWARDIAN PARASOL NATURAL',
 'CERAMIC STRAWBERRY CAKE MONEY BANK',
 'BLUE OWL SOFT TOY',
 'BALLOON ART MAKE YOUR OWN FLOWERS',
 'GLASS CLOCHE SMALL',
 'GUMBALL MONOCHROME COAT RACK',
 'DOORMAT FANCY FONT HOME SWEET HOME',
 'VINTAGE SNAKES & LADDERS',
 'CHOCOLATE CALCULATOR',
 'RECYCLING BAG RETROSPOT',
 'TOY TIDY PINK POLKADOT',
 'ANTIQUE GLASS DRESSING TABLE POT',
 'IVORY GIANT GARDEN THERMOMETER',
 '3 TIER CAKE TIN GREEN AND CREAM',
 '3 TIER CAKE TIN RED AND CREAM',
 'SET 3 WICKER OVAL BASKETS W LIDS',
 'WOOD BLACK BOARD ANT WHITE FINISH',
 'COLOUR GLASS T-LIGHT HOLDER HANGING',
 'HANGING METAL HEART LANTERN',
 'HANGING MEDINA LANTERN SMALL',
 'NATURAL SLATE HEART CHALKBOARD',
 'HEART OF WICKER SMALL',
 'HEART OF WICKER LARGE',
 'WHITE LOVEBIRD LANTERN',
 'CLASSIC METAL BIRDCAGE PLANT HOLDER',
 'CREAM HEART CARD HOLDER',
 'ENAMEL FLOWER JUG CREAM',
 'ENAMEL FIRE BUCKET CREAM',
 'ENAMEL BREAD BIN CREAM',
 'JUMBO BAG DOLLY GIRL DESIGN',
 'TRADITIONAL CHRISTMAS RIBBONS',
 'ORGANISER WOOD ANTIQUE WHITE',
 'LUNCH BAG DOLLY GIRL DESIGN',
 'WHITE WIRE EGG HOLDER',
 'JUMBO BAG RED RETROSPOT',
 'CHILLI LIGHTS',
 'LIGHT GARLAND BUTTERFILES PINK',
 'WOODEN OWLS LIGHT GARLAND',
 'FAIRY TALE COTTAGE NIGHTLIGHT',
 'HOME SMALL WOOD LETTERS',
 'GINGHAM HEART  DOORSTOP RED',
 'FIVE HEART HANGING DECORATION',
 'ASSORTED BOTTLE TOP  MAGNETS',
 'FRIDGE MAGNETS US DINER ASSORTED',
 'HOMEMADE JAM SCENTED CANDLES',
 'FRIDGE MAGNETS LES ENFANTS ASSORTED',
 'ROSE CARAVAN DOORSTOP',
 '5 HOOK HANGER MAGIC TOADSTOOL',
 'CHRISTMAS LIGHTS 10 REINDEER',
 'VINTAGE UNION JACK CUSHION COVER',
 'SET OF 3 COLOURED  FLYING DUCKS',
 'SET OF 3 GOLD FLYING DUCKS',
 'RED RETROSPOT UMBRELLA',
 'BLACK/BLUE POLKADOT UMBRELLA',
 'RED DINER WALL CLOCK',
 'BLUE DINER WALL CLOCK',
 'IVORY DINER WALL CLOCK',
 'LARGE HEART MEASURING SPOONS',
 'SMALL HEART MEASURING SPOONS',
 'JAM JAR WITH PINK LID',
 'JAM JAR WITH GREEN LID',
 'ROSE COTTAGE KEEPSAKE BOX',
 'HANGING HEART ZINC T-LIGHT HOLDER',
 'PAPER CHAIN KIT VINTAGE CHRISTMAS',
 'DISCO BALL CHRISTMAS DECORATION',
 'SMALL POPCORN HOLDER',
 'LARGE POPCORN HOLDER',
 'SET/20 RED RETROSPOT PAPER NAPKINS',
 'SET/6 RED SPOTTY PAPER CUPS',
 'POLKADOT RAIN HAT',
 'DELUXE SEWING KIT',
 'RETROSPOT HEART HOT WATER BOTTLE',
 'ENGLISH ROSE HOT WATER BOTTLE',
 'PHOTO CUBE',
 '3 STRIPEY MICE FELTCRAFT',
 'SET OF 6 SOLDIER SKITTLES',
 'TRADITIONAL WOODEN SKIPPING ROPE',
 'WOODEN BOX OF DOMINOES',
 'RUSTIC  SEVENTEEN DRAWER SIDEBOARD',
 'PARTY CONES CARNIVAL ASSORTED',
 'PARTY CONES CANDY ASSORTED',
 'PICNIC BASKET WICKER SMALL',
 'STAR DECORATION PAINTED ZINC',
 'RETROSPOT LAMP',
 'FANCY FONT BIRTHDAY CARD,',
 'HAND WARMER SCOTTY DOG DESIGN',
 'HAND WARMER OWL DESIGN',
 'HAND WARMER RED RETROSPOT',
 'DOG BOWL CHASING BALL DESIGN',
 'CLOTHES PEGS RETROSPOT PACK 24',
 'HAND OVER THE CHOCOLATE   SIGN',
 'TRAVEL SEWING KIT',
 'BLACK HEART CARD HOLDER',
 'CHICK GREY HOT WATER BOTTLE',
 'SMALL GLASS HEART TRINKET POT',
 'ALARM CLOCK BAKELIKE IVORY',
 'ALARM CLOCK BAKELIKE ORANGE',
 'HAND WARMER BIRD DESIGN',
 'IVORY EMBROIDERED QUILT',
 'SET OF 3 BLACK FLYING DUCKS',
 'PACK OF 12 RED RETROSPOT TISSUES',
 'RED RETROSPOT MUG',
 'BABUSHKA LIGHTS STRING OF 10',
 'DOORMAT FAIRY CAKE',
 'STRAWBERRY CERAMIC TRINKET BOX',
 'PINK DOUGHNUT TRINKET POT',
 'SILK PURSE BABUSHKA PINK',
 'HOT WATER BOTTLE I AM SO POORLY',
 'CHOCOLATE HOT WATER BOTTLE',
 'WHITE SKULL HOT WATER BOTTLE',
 'SCOTTIE DOG HOT WATER BOTTLE',
 'BIRD HOUSE HOT WATER BOTTLE',
 'BOUDOIR SQUARE TISSUE BOX',
 'SKULLS SQUARE TISSUE BOX',
 'PHOTO FRAME CORNICE',
 'SILK PURSE BABUSHKA RED',
 'PICTURE DOMINOES',
 'S/6 SEW ON CROCHET FLOWERS',
 'SCANDINAVIAN REDS RIBBONS',
 'BALLOONS  WRITING SET',
 'LAVENDER INCENSE IN TIN',
 'TV DINNER TRAY VINTAGE PAISLEY',
 'SET OF 4 ENGLISH ROSE PLACEMATS',
 'SET OF 4 ENGLISH ROSE COASTERS',
 'TRIPLE PHOTO FRAME CORNICE',
 'FAMILY PHOTO FRAME CORNICE',
 'MIRRORED DISCO BALL',
 'DISCO BALL ROTATOR BATTERY OPERATED',
 'SILVER LOOKING MIRROR',
 'LADIES & GENTLEMEN METAL SIGN',
 'METAL SIGN HER DINNER IS SERVED',
 'DOORMAT TOPIARY',
 'BATHROOM METAL SIGN',
 'KITCHEN METAL SIGN',
 'TOILET METAL SIGN',
 'METAL SIGN TAKE IT OR LEAVE IT',
 "I'M ON HOLIDAY METAL SIGN",
 'GROW YOUR OWN BASIL IN ENAMEL MUG',
 'SET/10 PINK POLKADOT PARTY CANDLES',
 'SET 20 NAPKINS FAIRY CAKES DESIGN',
 'SET OF 6 T-LIGHTS SNOWMEN',
 'SET OF 6 T-LIGHTS SANTA',
 'SET OF 9 HEART SHAPED BALLOONS',
 'SANDWICH BATH SPONGE',
 'APPLE BATH SPONGE',
 'STRAWBERRY BATH SPONGE',
 'BLACK PIRATE TREASURE CHEST',
 'STAR PORTABLE TABLE LIGHT',
 'SNOWFLAKE PORTABLE TABLE LIGHT',
 'PINK OVAL JEWELLED MIRROR',
 'RETROSPOT CIGAR BOX MATCHES',
 'COSY HOUR GIANT TUBE MATCHES',
 'JAZZ HEARTS PURSE NOTEBOOK',
 'CANDLEHOLDER PINK HANGING HEART',
 'ASSORTED COLOUR MINI CASES',
 'LUNCH BAG SPACEBOY DESIGN',
 'LUNCH BAG WOODLAND',
 'LUNCH BAG PINK POLKADOT',
 'GUMBALL COAT RACK',
 'BLUE NEW BAROQUE CANDLESTICK CANDLE',
 'PINK NEW BAROQUECANDLESTICK CANDLE',
 'FAIRY CAKE FLANNEL ASSORTED COLOUR',
 'BREAD BIN DINER STYLE PINK',
 'TEA TIME TABLE CLOTH',
 'HOT WATER BOTTLE BABUSHKA',
 'HEART IVORY TRELLIS SMALL',
 'PINK DRAWER KNOB ACRYLIC EDWARDIAN',
 'GREEN DRAWER KNOB ACRYLIC EDWARDIAN',
 'BLUE DRAWER KNOB ACRYLIC EDWARDIAN',
 'SET 6 FOOTBALL CELEBRATION CANDLES',
 'SET OF 6 GIRLS CELEBRATION CANDLES',
 'ROMANTIC PINKS RIBBONS',
 'BRIGHT BLUES RIBBONS',
 'CHOCOLATE BOX RIBBONS',
 'PARTY INVITES FOOTBALL',
 'PARTY INVITES JAZZ HEARTS',
 'PARTY INVITES SPACEMAN',
 'SET OF 3 BUTTERFLY COOKIE CUTTERS',
 'SET OF 3 HEART COOKIE CUTTERS',
 '3 PIECE SPACEBOY COOKIE CUTTER SET',
 'PACK OF 72 SKULL CAKE CASES',
 'PACK OF 60 SPACEBOY CAKE CASES',
 '72 SWEETHEART FAIRY CAKE CASES',
 'LUNCH BAG SUKI  DESIGN',
 'LUNCH BAG CARS BLUE',
 'LUNCH BAG  BLACK SKULL.',
 'HEART IVORY TRELLIS LARGE',
 'SET/5 RED RETROSPOT LID GLASS BOWLS',
 'MAGIC DRAWING SLATE DINOSAUR',
 'MAGIC DRAWING SLATE BAKE A CAKE',
 '12 PENCILS TALL TUBE SKULLS',
 'RED  HARMONICA IN BOX',
 'BLUE HARMONICA IN BOX',
 'SKULLS  WATER TRANSFER TATTOOS',
 'PACK 3 BOXES BIRD PANNETONE',
 'SET OF 20 KIDS COOKIE CUTTERS',
 '10 COLOUR SPACEBOY PEN',
 'VICTORIAN GLASS HANGING T-LIGHT',
 'SINGLE HEART ZINC T-LIGHT HOLDER',
 'HANGING METAL STAR LANTERN',
 'SILVER HANGING T-LIGHT HOLDER',
 'DOORMAT RED RETROSPOT',
 'DOORMAT HEARTS',
 'NATURAL SLATE RECTANGLE CHALKBOARD',
 'LOVEBIRD HANGING DECORATION WHITE',
 'PENS ASSORTED FUNNY FACE',
 'CARD CIRCUS PARADE',
 'WRAP COWBOYS',
 'AIRLINE BAG VINTAGE TOKYO 78',
 'SET OF 72 RETROSPOT PAPER  DOILIES',
 'PLASTERS IN TIN SKULLS',
 'SLEEPING CAT ERASERS',
 'CARD BIRTHDAY COWBOY',
 'PACK 3 BOXES CHRISTMAS PANNETONE',
 'ROTATING SILVER ANGELS T-LIGHT HLDR',
 'RIBBON REEL MAKING SNOWMEN',
 '4 TRADITIONAL SPINNING TOPS',
 'BAG 500g SWIRLY MARBLES',
 '5 STRAND GLASS NECKLACE CRYSTAL',
 'SQUARECUSHION COVER PINK UNION FLAG',
 'SPACEBOY CHILDRENS EGG CUP',
 "CHILDREN'S SPACEBOY MUG",
 'FELTCRAFT CUSHION OWL',
 'BLACK CANDELABRA T-LIGHT HOLDER',
 'TOY TIDY DOLLY GIRL DESIGN',
 'SET 12 LAVENDER  BOTANICAL T-LIGHTS',
 'UNION JACK FLAG LUGGAGE TAG',
 'RED HEART LUGGAGE TAG',
 'RED GLASS TASSLE BAG CHARM',
 'CLEAR ACRYLIC FACETED BANGLE',
 'DOORMAT UNION JACK GUNS AND ROSES',
 'VANILLA SCENT CANDLE JEWELLED BOX',
 'FULL ENGLISH BREAKFAST PLATE',
 'MAGIC DRAWING SLATE CIRCUS PARADE',
 'CHRISTMAS HANGING HEART WITH BELL',
 'CAKE STAND VICTORIAN FILIGREE MED',
 'PAISLEY PATTERN  STICKERS',
 'FLOWERS  STICKERS',
 'BLACK LOVE BIRD CANDLE',
 'PARTY TIME PENCIL ERASERS',
 "PINK B'FLY C/COVER W BOBBLES",
 'PINK UNION JACK  LUGGAGE TAG',
 '6 RIBBONS ELEGANT CHRISTMAS',
 'AGED GLASS SILVER T-LIGHT HOLDER',
 'BOOM BOX SPEAKER GIRLS',
 '6 RIBBONS SHIMMERING PINKS',
 'JUMBO BAG OWLS',
 'OWL DOORSTOP',
 'PAINTED METAL STAR WITH HOLLY BELLS',
 'PAINTED METAL HEART WITH HOLLY BELL',
 'ANGEL DECORATION STARS ON DRESS',
 'JUMBO BAG STRAWBERRY',
 'STRAWBERRY SHOPPER BAG',
 'ROUND SNACK BOXES SET OF 4 FRUITS',
 'ROUND SNACK BOXES SET OF 4 SKULLS',
 'DOLLY GIRL LUNCH BOX',
 'GREEN POLKADOT PLATE',
 'BLUE POLKADOT PLATE',
 'RED RETROSPOT PLATE',
 'PINK  POLKADOT PLATE',
 'FELTCRAFT DOLL MOLLY',
 'FELTCRAFT CHRISTMAS FAIRY',
 'SET OF 3 NOTEBOOKS IN PARCEL',
 'RED RETROSPOT TAPE',
 'COSY SLIPPER SHOES SMALL  RED',
 '6 RIBBONS RUSTIC CHARM',
 '12 DAISY PEGS IN WOOD BOX',
 '5 HOOK HANGER RED MAGIC TOADSTOOL',
 'CHRISTMAS CRAFT TREE TOP ANGEL',
 'CHRISTMAS CRAFT LITTLE FRIENDS',
 'COSY SLIPPER SHOES SMALL GREEN',
 'FELTCRAFT DOLL ROSIE',
 'FELTCRAFT DOLL EMILY',
 'FELTCRAFT PRINCESS OLIVIA DOLL',
 'REX CASH+CARRY JUMBO SHOPPER',
 'FELTCRAFT CUSHION RABBIT',
 'FELTCRAFT CUSHION BUTTERFLY',
 'TOTE BAG I LOVE LONDON',
 'FOLDING UMBRELLA PINKWHITE POLKADOT',
 'FOLDING UMBRELLA CREAM POLKADOT',
 'FOLDING UMBRELLA WHITE/RED POLKADOT',
 'SET 10 LIGHTS NIGHT OWL',
 'FOLDING UMBRELLA RED/WHITE POLKADOT',
 'S/4 VALENTINE DECOUPAGE HEART BOX',
 'SOLDIERS EGG CUP',
 'RED RETROSPOT MINI CASES',
 nan,
 '60 CAKE CASES VINTAGE CHRISTMAS',
 'RIBBON REEL CHRISTMAS SOCK BAUBLE',
 'RIBBON REEL SNOWY VILLAGE',
 'SET OF 20 VINTAGE CHRISTMAS NAPKINS',
 'TURQUOISE CHRISTMAS TREE',
 'RED STAR CARD HOLDER',
 'WICKER WREATH SMALL',
 'ADVENT CALENDAR GINGHAM SACK',
 'FELTCRAFT BUTTERFLY HEARTS',
 'PARTY CONE CHRISTMAS DECORATION',
 'WICKER STAR',
 'VINTAGE SNAP CARDS',
 'FELTCRAFT 6 FLOWER FRIENDS',
 'BIRD DECORATION RED RETROSPOT',
 'CHRISTMAS GINGHAM TREE',
 'CHRISTMAS GINGHAM STAR',
 'CHRISTMAS GINGHAM HEART',
 'PACK OF 12 PINK POLKADOT TISSUES',
 'FELTCRAFT PRINCESS LOLA DOLL',
 'PACK OF 12 LONDON TISSUES',
 'PURPLE DRAWERKNOB ACRYLIC EDWARDIAN',
 "CHILDREN'S APRON DOLLY GIRL",
 'CHILDRENS APRON SPACEBOY DESIGN',
 'CHRISTMAS LIGHTS 10 SANTAS',
 'PACK OF 60 MUSHROOM CAKE CASES',
 '60 CAKE CASES DOLLY GIRL DESIGN',
 'HAND WARMER BABUSHKA DESIGN',
 'SET 12 RETRO WHITE CHALK STICKS',
 'FELTCRAFT HAIRBAND RED AND BLUE',
 'FELTCRAFT HAIRBAND PINK AND PURPLE',
 'FELTCRAFT HAIRBANDS PINK AND WHITE',
 'TV DINNER TRAY DOLLY GIRL',
 'PLASTERS IN TIN VINTAGE PAISLEY',
 'PLASTERS IN TIN SPACEBOY',
 'PLASTERS IN TIN WOODLAND ANIMALS',
 'MAGIC DRAWING SLATE SPACEBOY',
 'MAGIC DRAWING SLATE GO TO THE FAIR',
 'MAGIC DRAWING SLATE DOLLY GIRL',
 'CHARLIE + LOLA RED HOT WATER BOTTLE',
 'URBAN BLACK RIBBONS',
 'SET OF 6 T-LIGHTS TOADSTOOLS',
 'ROTATING LEAVES T-LIGHT HOLDER',
 'CUPCAKE LACE PAPER SET 6',
 'TRADITIONAL WOODEN CATCH CUP GAME',
 'S/6 WOODEN SKITTLES IN COTTON BAG',
 'RED METAL BEACH SPADE',
 'BOYS VINTAGE TIN SEASIDE BUCKET',
 'GIRLS VINTAGE TIN SEASIDE BUCKET',
 'GREY HEART HOT WATER BOTTLE',
 'KINGS CHOICE TEA CADDY',
 'KINGS CHOICE BISCUIT TIN',
 'METAL SIGN EMPIRE TEA',
 'FAWN BLUE HOT WATER BOTTLE',
 'PACK OF 6 BIRDY GIFT TAGS',
 'CERAMIC STRAWBERRY MONEY BOX',
 'CERAMIC HEART FAIRY CAKE MONEY BANK',
 'CERAMIC PIRATE CHEST MONEY BANK',
 'DOORSTOP RETROSPOT HEART',
 'RETROSPOT BABUSHKA DOORSTOP',
 'SWEETHEART WIRE WALL TIDY',
 'RED RETROSPOT OVEN GLOVE',
 'NAMASTE SWAGAT INCENSE',
 'CERAMIC STRAWBERRY DESIGN MUG',
 'CLASSICAL ROSE SMALL VASE',
 'HYACINTH BULB T-LIGHT CANDLES',
 'CHRISTMAS CRAFT WHITE FAIRY',
 'COSY HOUR CIGAR BOX MATCHES',
 'RED TEA TOWEL CLASSIC DESIGN',
 'HEART FILIGREE DOVE  SMALL',
 'RETROSPOT CHILDRENS APRON',
 'COLOURING PENCILS BROWN TUBE',
 '4 IVORY DINNER CANDLES SILVER FLOCK',
 'ZINC METAL HEART DECORATION',
 'GREEN FERN NOTEBOOK',
 'BLUE PAISLEY NOTEBOOK',
 'CHRYSANTHEMUM NOTEBOOK',
 'LARGE CHINESE STYLE SCISSOR',
 'SMALL CHINESE STYLE SCISSOR',
 'HANGING GLASS ETCHED TEALIGHT',
 'COOKING SET RETROSPOT',
 'KINGS CHOICE GIANT TUBE MATCHES',
 'PLACE SETTING WHITE STAR',
 'S/15 SILVER GLASS BAUBLES IN BAG',
 'FRENCH WC SIGN BLUE METAL',
 'FAIRY SOAP SOAP HOLDER',
 'GREEN GIANT GARDEN THERMOMETER',
 'BLUE GIANT GARDEN THERMOMETER',
 'VICTORIAN SEWING BOX SMALL',
 'VICTORIAN SEWING BOX MEDIUM',
 'SET/10 RED POLKADOT PARTY CANDLES',
 'WASHROOM METAL SIGN',
 'BLACK SWEETHEART BRACELET',
 'DIAMANTE HAIR GRIP PACK/2 BLACK DIA',
 'BLACK DIAMANTE EXPANDABLE RING',
 'DIAMANTE HAIR GRIP PACK/2 RUBY',
 'DIAMANTE HAIR GRIP PACK/2 MONTANA',
 'BLUE SWEETHEART BRACELET',
 'PINK SWEETHEART BRACELET',
 'PURPLE SWEETHEART BRACELET',
 'RIBBON REEL CHRISTMAS PRESENT',
 'FIRST AID TIN',
 'MAKE YOUR OWN MONSOON CARD KIT',
 'PACK OF 12 HEARTS DESIGN TISSUES',
 'HEART FILIGREE DOVE LARGE',
 'SWIRLY CIRCULAR RUBBERS IN BAG',
 'VINTAGE PAISLEY STATIONERY SET',
 'SET/10 BLUE POLKADOT PARTY CANDLES',
 'RIBBON REEL SOCKS AND MITTENS',
 'CHRISTMAS METAL TAGS ASSORTED',
 'CHRISTMAS TREE T-LIGHT HOLDER',
 'STAR  T-LIGHT HOLDER',
 'HEART T-LIGHT HOLDER',
 'MINI FUNKY DESIGN TAPES',
 'STAR WOODEN CHRISTMAS DECORATION',
 'WOODEN HEART CHRISTMAS SCANDINAVIAN',
 'CHRISTMAS RETROSPOT TREE WOOD',
 'SET/9 CHRISTMAS T-LIGHTS SCENTED',
 'BLUE ROSE FABRIC MIRROR',
 'THREE CANVAS LUGGAGE TAGS',
 'RETROSPOT PARTY BAG + STICKER SET',
 'RETROSPOT SMALL TUBE MATCHES',
 '3D CHRISTMAS STAMPS STICKERS',
 '36 FOIL HEART CAKE CASES',
 'PACK OF 6 SWEETIE GIFT BOXES',
 'CINAMMON SET OF 9 T-LIGHTS',
 'ORANGE SCENTED SET/9 T-LIGHTS',
 'RIBBON REEL STRIPES DESIGN',
 'SET OF 2 TINS JARDIN DE PROVENCE',
 'MAKE YOUR OWN PLAYTIME CARD KIT',
 'DINOSAURS  WRITING SET',
 'SKULLS WRITING SET',
 'DOORMAT BLACK FLOCK',
 'CHRISTMAS DECOUPAGE CANDLE',
 'OFFICE MUG WARMER POLKADOT',
 'BLACK RECORD COVER FRAME',
 'RECORD FRAME 7" SINGLE SIZE',
 '36 PENCILS TUBE RED RETROSPOT',
 '36 PENCILS TUBE WOODLAND',
 'ROCKING HORSE RED CHRISTMAS',
 'REGENCY CAKESTAND 3 TIER',
 'VINTAGE UNION JACK BUNTING',
 'RETRO LONGBOARD IRONING BOARD COVER',
 '3D DOG PICTURE PLAYING CARDS',
 'SAVE THE PLANET COTTON TOTE BAG',
 'PAPER BUNTING WHITE LACE',
 'GENTLEMAN SHIRT REPAIR KIT',
 'CARD I LOVE LONDON',
 'MIRRORED WALL ART FOXY',
 'MIRRORED WALL ART GENTS',
 'AIRLINE BAG VINTAGE JET SET WHITE',
 "POTTING SHED SOW 'N' GROW SET",
 'AIRLINE BAG VINTAGE WORLD CHAMPION',
 'PINK HEARTS PAPER GARLAND',
 'POTTING SHED SEED ENVELOPES',
 'HI TEC ALPINE HAND WARMER',
 'POLYESTER FILLER PAD 45x45cm',
 'CARD DOLLY GIRL',
 'CARD BILLBOARD FONT',
 'RAINY LADIES BIRTHDAY CARD',
 'RED WHITE SCARF  HOT WATER BOTTLE',
 'SET OF 2 TEA TOWELS APPLE AND PEARS',
 'LANTERN CREAM GAZEBO',
 'BLUE BIRDHOUSE DECORATION',
 'ANTIQUE SILVER TEA GLASS ENGRAVED',
 'SET OF 2 WOODEN MARKET CRATES',
 'CLASSIC FRENCH STYLE BASKET NATURAL',
 'CRAZY DAISY HEART DECORATION',
 'CARD HOLDER GINGHAM HEART',
 'SMALL STRIPES CHOCOLATE GIFT BAG',
 'TRAY, BREAKFAST IN BED',
 'PIZZA PLATE IN BOX',
 'PINK HEART DOTS HOT WATER BOTTLE',
 'PLACE SETTING WHITE HEART',
 'SET OF 4 NAPKIN CHARMS LEAVES',
 'SET OF 4 NAPKIN CHARMS STARS',
 'SET OF 4 NAPKIN CHARMS CUTLERY',
 'CARAVAN SQUARE TISSUE BOX',
 'BUTTON BOX',
 '12 MESSAGE CARDS WITH ENVELOPES',
 'SMALL RED BABUSHKA NOTEBOOK',
 'HERB MARKER MINT',
 'HERB MARKER ROSEMARY',
 'HERB MARKER BASIL',
 'HERB MARKER CHIVES',
 'HERB MARKER PARSLEY',
 'HERB MARKER THYME',
 'METAL MERRY CHRISTMAS WREATH',
 'WHITE CHRISTMAS GARLAND STARS TREES',
 'RETROSPOT GIANT TUBE MATCHES',
 '36 FOIL STAR CAKE CASES',
 'PACK OF 6 HANDBAG GIFT BOXES',
 'GARLAND WOODEN HAPPY EASTER',
 'CALENDAR PAPER CUT DESIGN',
 'CALENDAR IN SEASON DESIGN',
 'BLUE PAISLEY TISSUE BOX',
 'PINK PAISLEY SQUARE TISSUE BOX',
 'TOAST ITS - HAPPY BIRTHDAY',
 'SET/10 IVORY POLKADOT PARTY CANDLES',
 'SKULLS STORAGE BOX SMALL',
 'JUMBO STORAGE BAG SKULLS',
 'GARDEN PATH JOURNAL',
 'BLACK ORANGE SQUEEZER',
 'SET OF 72 GREEN PAPER DOILIES',
 'RETROSPOT RED WASHING UP GLOVES',
 'SMALL LICORICE DES PINK BOWL',
 'SWISS ROLL TOWEL, CHOCOLATE  SPOTS',
 'PICNIC BASKET WICKER LARGE',
 'CREAM SWEETHEART EGG HOLDER',
 'PINK 3 PIECE POLKADOT CUTLERY SET',
 'PINK PARTY BAGS',
 'BLUE PARTY BAGS',
 'PINK CREAM FELT CRAFT TRINKET BOX',
 'RED RETROSPOT OVEN GLOVE DOUBLE',
 'RIDGED GLASS STORAGE JAR CREAM LID',
 'PACK OF 20 NAPKINS PANTRY DESIGN',
 'SWEETHEART CAKESTAND 3 TIER',
 'CHRISTMAS HANGING STAR WITH BELL',
 'MULTICOLOUR  CONFETTI IN TUBE',
 'CHOCOLATE 3 WICK MORRIS BOX CANDLE',
 'SET OF 16 VINTAGE PISTACHIO CUTLERY',
 'CHRISTMAS TOILET ROLL',
 'WHITE BELL HONEYCOMB PAPER',
 '4 PURPLE FLOCK DINNER CANDLES',
 'PINK & WHITE BREAKFAST TRAY',
 'ENGLISH ROSE SPIRIT LEVEL',
 'LARGE ROUND WICKER PLATTER',
 'BLACK TEA TOWEL CLASSIC DESIGN',
 'CHRISTMAS LIGHTS 10 VINTAGE BAUBLES',
 'ROSES REGENCY TEACUP AND SAUCER',
 'T-LIGHT HOLDER HANGING LACE',
 'HANGING HEART MIRROR DECORATION',
 'CREAM SLICE FLANNEL CHOCOLATE SPOT',
 'CREAM SLICE FLANNEL PINK SPOT',
 'GREEN REGENCY TEACUP AND SAUCER',
 'EIGHT PIECE DINOSAUR SET',
 'HEADS AND TAILS SPORTING FUN',
 "ASS COL SMALL SAND GECKO P'WEIGHT",
 'ENAMEL MEASURING JUG CREAM',
 '12 PENCILS SMALL TUBE SKULL',
 '12 PENCIL SMALL TUBE WOODLAND',
 'BLUE PAPER PARASOL',
 'VICTORIAN  METAL POSTCARD SPRING',

## 2) Vamos contar quantas vezes cada item aparece neste dataset.

In [68]:
item_freq = mba.groupby("Itemname")["Itemname"].count().sort_values(ascending=False)
item_freq.head(40)

Itemname
WHITE HANGING HEART T-LIGHT HOLDER    2269
JUMBO BAG RED RETROSPOT               2087
REGENCY CAKESTAND 3 TIER              1930
PARTY BUNTING                         1677
LUNCH BAG RED RETROSPOT               1570
ASSORTED COLOUR BIRD ORNAMENT         1465
SET OF 3 CAKE TINS PANTRY DESIGN      1360
PACK OF 72 RETROSPOT CAKE CASES       1328
LUNCH BAG  BLACK SKULL.               1315
NATURAL SLATE HEART CHALKBOARD        1246
JUMBO BAG PINK POLKADOT               1231
HEART OF WICKER SMALL                 1206
JUMBO STORAGE BAG SUKI                1191
PAPER CHAIN KIT 50'S CHRISTMAS        1183
JUMBO SHOPPER VINTAGE RED PAISLEY     1181
LUNCH BAG SPACEBOY DESIGN             1169
LUNCH BAG CARS BLUE                   1156
SPOTTY BUNTING                        1133
JAM MAKING SET PRINTED                1123
LUNCH BAG SUKI DESIGN                 1112
WOODEN PICTURE FRAME WHITE FINISH     1103
RECIPE BOX PANTRY YELLOW DESIGN       1101
LUNCH BAG PINK POLKADOT               1100
JAM MAKING SET WITH JARS              1098
SET OF 4 PANTRY JELLY MOULDS          1081
POSTAGE                               1070
LUNCH BAG APPLE DESIGN                1057
ALARM CLOCK BAKELIKE RED              1050
RED RETROSPOT CHARLOTTE BAG           1046
VICTORIAN GLASS HANGING T-LIGHT       1032
ROSES REGENCY TEACUP AND SAUCER       1031
LUNCH BAG WOODLAND                    1028
RABBIT NIGHT LIGHT                    1021
GREEN REGENCY TEACUP AND SAUCER       1003
SET/20 RED RETROSPOT PAPER NAPKINS     991
ALARM CLOCK BAKELIKE GREEN             987
JUMBO BAG APPLES                       974
WOODEN FRAME ANTIQUE WHITE             969
6 RIBBONS RUSTIC CHARM                 967
REX CASH+CARRY JUMBO SHOPPER           963
Name: Itemname, dtype: int64

In [69]:
item_freq = mba.groupby("Itemname")["Itemname"].count().sort_values(ascending=False)
item_freq.tail(20)

Itemname
PINK DOLLY HAIR CLIPS                  1
PINK CRYSTAL GUITAR PHONE CHARM        1
PINK CHRYSANTHEMUMS ART FLOWER         1
PINK CHERRY LIGHTS                     1
PINK CHERRY BLOSSOM CUP & SAUCER       1
PINK BOUDOIR T-LIGHT HOLDER            1
PINK BERTIE MOBILE PHONE CHARM         1
PINK BEADS+HAND PHONE CHARM            1
PINK BAROQUE FLOCK CANDLE HOLDER       1
PINK ACRYLIC JEWEL SNOWFLAKE           1
PEARL & SHELL 42"NECKL. IVORY          1
PAPER CRAFT , LITTLE BIRDIE            1
PAINTED HEART WREATH WITH BELL         1
PACK 4 FLOWER/BUTTERFLY PATCHES        1
ORANGE/FUSCHIA STONES NECKLACE         1
ORANGE PENDANT TRIPLE SHELL NECKLAC    1
ORANGE FELT VASE + FLOWERS             1
OPULENT VELVET SET/3 CANDLES           1
OOPS ! adjustment                      1
wrongly sold sets                      1
Name: Itemname, dtype: int64

### 3) Alguns itens são bem comuns, mas outros foram comprados uma única vez. Vamos fazer uma limpeza nesta dataset, caso contrário o tempo de execução do algoritmo será muito longo.

# Vamos manter apenas os itens que aparecem pelo menos 1000 vezes.

In [70]:
item_filt = item_freq[item_freq >= 1000].index.tolist()
len(item_filt) # agora poucos itens, 34 apenas, melhor para se trabalhar

34

In [71]:
item_filt

['WHITE HANGING HEART T-LIGHT HOLDER',
 'JUMBO BAG RED RETROSPOT',
 'REGENCY CAKESTAND 3 TIER',
 'PARTY BUNTING',
 'LUNCH BAG RED RETROSPOT',
 'ASSORTED COLOUR BIRD ORNAMENT',
 'SET OF 3 CAKE TINS PANTRY DESIGN',
 'PACK OF 72 RETROSPOT CAKE CASES',
 'LUNCH BAG  BLACK SKULL.',
 'NATURAL SLATE HEART CHALKBOARD',
 'JUMBO BAG PINK POLKADOT',
 'HEART OF WICKER SMALL',
 'JUMBO STORAGE BAG SUKI',
 "PAPER CHAIN KIT 50'S CHRISTMAS",
 'JUMBO SHOPPER VINTAGE RED PAISLEY',
 'LUNCH BAG SPACEBOY DESIGN',
 'LUNCH BAG CARS BLUE',
 'SPOTTY BUNTING',
 'JAM MAKING SET PRINTED',
 'LUNCH BAG SUKI DESIGN',
 'WOODEN PICTURE FRAME WHITE FINISH',
 'RECIPE BOX PANTRY YELLOW DESIGN',
 'LUNCH BAG PINK POLKADOT',
 'JAM MAKING SET WITH JARS',
 'SET OF 4 PANTRY JELLY MOULDS',
 'POSTAGE',
 'LUNCH BAG APPLE DESIGN',
 'ALARM CLOCK BAKELIKE RED',
 'RED RETROSPOT CHARLOTTE BAG',
 'VICTORIAN GLASS HANGING T-LIGHT',
 'ROSES REGENCY TEACUP AND SAUCER',
 'LUNCH BAG WOODLAND',
 'RABBIT NIGHT LIGHT',
 'GREEN REGENCY TEACUP AND SAUCER']

A próxima célula mantém apenas as transações que contém os 34 itens selecionados.

In [72]:
mba_filt = mba[mba["Itemname"].isin(item_filt)]
mba_filt

,BillNo,Itemname,Quantity,Date,Price,CustomerID,Country
0,536365,WHITE HANGING HEART T-LIGHT HOLDER,6,01.12.2010 08:26,"2,55",17850.0,United Kingdom
9,536367,ASSORTED COLOUR BIRD ORNAMENT,32,01.12.2010 08:34,"1,69",13047.0,United Kingdom
21,536368,JAM MAKING SET WITH JARS,6,01.12.2010 08:34,"4,25",13047.0,United Kingdom
27,536370,ALARM CLOCK BAKELIKE RED,24,01.12.2010 08:45,"3,75",12583.0,France
45,536370,POSTAGE,3,01.12.2010 08:45,18,12583.0,France
...,...,...,...,...,...,...,...
522026,581585,VICTORIAN GLASS HANGING T-LIGHT,12,09.12.2011 12:31,"1,95",15804.0,United Kingdom
522029,581585,RABBIT NIGHT LIGHT,12,09.12.2011 12:31,"2,08",15804.0,United Kingdom
522030,581585,ASSORTED COLOUR BIRD ORNAMENT,16,09.12.2011 12:31,"1,69",15804.0,United Kingdom
522035,581585,ALARM CLOCK BAKELIKE RED,4,09.12.2011 12:31,"3,75",15804.0,United Kingdom
522053,581587,ALARM CLOCK BAKELIKE RED,4,09.12.2011 12:50,"3,75",12680.0,France

Agora vamos ver quantas compras aparecem, agregando pelo atributo `BillNo`. Neste caso, já estamos também selecionando os itens de cada transação, e formatando como lista.

In [73]:
# BillNo, é o número único da compra

In [74]:
baskets = mba_filt.groupby("BillNo")["Itemname"].agg(list).tolist()
len(baskets)

12788

In [75]:
baskets

[['WHITE HANGING HEART T-LIGHT HOLDER'],
 ['ASSORTED COLOUR BIRD ORNAMENT'],
 ['JAM MAKING SET WITH JARS'],
 ['ALARM CLOCK BAKELIKE RED', 'POSTAGE'],
 ["PAPER CHAIN KIT 50'S CHRISTMAS"],
 ['WHITE HANGING HEART T-LIGHT HOLDER', 'WOODEN PICTURE FRAME WHITE FINISH'],
 ['WHITE HANGING HEART T-LIGHT HOLDER', 'WOODEN PICTURE FRAME WHITE FINISH'],
 ['JUMBO BAG PINK POLKADOT',
  'LUNCH BAG RED RETROSPOT',
  'PACK OF 72 RETROSPOT CAKE CASES',
  'JUMBO STORAGE BAG SUKI'],
 ['JAM MAKING SET PRINTED'],
 ['JUMBO SHOPPER VINTAGE RED PAISLEY', "PAPER CHAIN KIT 50'S CHRISTMAS"],
 ['JUMBO SHOPPER VINTAGE RED PAISLEY'],
 ['NATURAL SLATE HEART CHALKBOARD', 'HEART OF WICKER SMALL'],
 ['JAM MAKING SET PRINTED', 'JAM MAKING SET WITH JARS'],
 ['JUMBO BAG RED RETROSPOT'],
 ['HEART OF WICKER SMALL'],
 ['ALARM CLOCK BAKELIKE RED'],
 ['JAM MAKING SET WITH JARS',
  'JAM MAKING SET PRINTED',
  'WHITE HANGING HEART T-LIGHT HOLDER',
  'JUMBO BAG RED RETROSPOT'],
 ['ASSORTED COLOUR BIRD ORNAMENT'],
 ['WHITE HANGING HEART T-LIGHT HOLDER'],
 ['ASSORTED COLOUR BIRD ORNAMENT',
  'PACK OF 72 RETROSPOT CAKE CASES',
  'ALARM CLOCK BAKELIKE RED'],
 ['WHITE HANGING HEART T-LIGHT HOLDER', 'WOODEN PICTURE FRAME WHITE FINISH'],
 ['JAM MAKING SET PRINTED',
  'WHITE HANGING HEART T-LIGHT HOLDER',
  'LUNCH BAG RED RETROSPOT',
  'LUNCH BAG SPACEBOY DESIGN',
  'LUNCH BAG WOODLAND',
  'LUNCH BAG PINK POLKADOT'],
 ["PAPER CHAIN KIT 50'S CHRISTMAS"],
 ['POSTAGE'],
 ['HEART OF WICKER SMALL',
  'PACK OF 72 RETROSPOT CAKE CASES',
  'LUNCH BAG CARS BLUE',
  'LUNCH BAG  BLACK SKULL.'],
 ['WHITE HANGING HEART T-LIGHT HOLDER', 'WOODEN PICTURE FRAME WHITE FINISH'],
 ['VICTORIAN GLASS HANGING T-LIGHT',
  'ASSORTED COLOUR BIRD ORNAMENT',
  'PACK OF 72 RETROSPOT CAKE CASES'],
 ['JUMBO STORAGE BAG SUKI', 'JUMBO BAG RED RETROSPOT'],
 ['LUNCH BAG CARS BLUE',
  'LUNCH BAG SPACEBOY DESIGN',
  'LUNCH BAG  BLACK SKULL.',
  'JAM MAKING SET PRINTED',
  "PAPER CHAIN KIT 50'S CHRISTMAS",
  'LUNCH BAG RED RETROSPOT'],
 ['HEART OF WICKER SMALL',
  'JAM MAKING SET PRINTED',
  "PAPER CHAIN KIT 50'S CHRISTMAS",
  'PACK OF 72 RETROSPOT CAKE CASES'],
 ['JAM MAKING SET PRINTED'],
 ['ASSORTED COLOUR BIRD ORNAMENT'],
 ['JUMBO BAG PINK POLKADOT',
  'JUMBO BAG RED RETROSPOT',
  'ASSORTED COLOUR BIRD ORNAMENT',
  "PAPER CHAIN KIT 50'S CHRISTMAS",
  'PACK OF 72 RETROSPOT CAKE CASES',
  'PACK OF 72 RETROSPOT CAKE CASES',
  'JAM MAKING SET WITH JARS'],
 ['JAM MAKING SET WITH JARS', 'JAM MAKING SET PRINTED'],
 ['REGENCY CAKESTAND 3 TIER', 'JUMBO SHOPPER VINTAGE RED PAISLEY'],
 ['JAM MAKING SET WITH JARS', 'JAM MAKING SET PRINTED'],
 ['ASSORTED COLOUR BIRD ORNAMENT',
  'WHITE HANGING HEART T-LIGHT HOLDER',
  'REGENCY CAKESTAND 3 TIER'],
 ['WHITE HANGING HEART T-LIGHT HOLDER',
  'HEART OF WICKER SMALL',
  'HEART OF WICKER SMALL'],
 ['JUMBO BAG RED RETROSPOT', 'JUMBO STORAGE BAG SUKI'],
 ['ROSES REGENCY TEACUP AND SAUCER'],
 ['GREEN REGENCY TEACUP AND SAUCER'],
 ['REGENCY CAKESTAND 3 TIER'],
 ['JUMBO BAG RED RETROSPOT', 'JUMBO SHOPPER VINTAGE RED PAISLEY'],
 ['POSTAGE'],
 ['JUMBO SHOPPER VINTAGE RED PAISLEY',
  'JAM MAKING SET WITH JARS',
  'REGENCY CAKESTAND 3 TIER',
  'JAM MAKING SET PRINTED',
  'JUMBO SHOPPER VINTAGE RED PAISLEY'],
 ['ROSES REGENCY TEACUP AND SAUCER',
  'REGENCY CAKESTAND 3 TIER',
  'JUMBO SHOPPER VINTAGE RED PAISLEY'],
 ['ALARM CLOCK BAKELIKE RED', "PAPER CHAIN KIT 50'S CHRISTMAS"],
 ['JAM MAKING SET PRINTED',
  'PACK OF 72 RETROSPOT CAKE CASES',
  'RECIPE BOX PANTRY YELLOW DESIGN'],
 ['ASSORTED COLOUR BIRD ORNAMENT'],
 ['REGENCY CAKESTAND 3 TIER'],
 ["PAPER CHAIN KIT 50'S CHRISTMAS",
  'NATURAL SLATE HEART CHALKBOARD',
  'HEART OF WICKER SMALL'],
 ['REGENCY CAKESTAND 3 TIER'],
 ['LUNCH BAG SPACEBOY DESIGN',
  'LUNCH BAG  BLACK SKULL.',
  'JUMBO BAG PINK POLKADOT',
  'JUMBO BAG RED RETROSPOT',
  'JUMBO SHOPPER VINTAGE RED PAISLEY',
  'JUMBO STORAGE BAG SUKI',
  'WHITE HANGING HEART T-LIGHT HOLDER'],
 ["PAPER CHAIN KIT 50'S CHRISTMAS",
  'VICTORIAN GLASS HANGING T-LIGHT',
  'LUNCH BAG PINK POLKADOT',
  'REGENCY CAKESTAND 3 TIER',
  'NATURAL SLATE HEART CHALKBOARD',
  'HEART OF WICKER SMALL',
  'RECIPE BOX PANTRY YELLOW DESIGN',
  'GREEN REGENCY TEACUP AND SAUCER',
  'ROSES REGENCY TEACUP AND SAUCER',
  'ALARM CLOCK BAKELIKE RED',
  'JAM MAKING SET WITH JARS',
  'JAM MAKING SET PRINTED',
  'JUMBO BAG RED RETROSPOT',
  'WHITE HANGING HEART T-LIGHT HOLDER',
  'RED RETROSPOT CHARLOTTE BAG',
  'LUNCH BAG RED RETROSPOT',
  'PACK OF 72 RETROSPOT CAKE CASES'],
 ['RECIPE BOX PANTRY YELLOW DESIGN'],
 ['JAM MAKING SET WITH JARS'],
 ['REGENCY CAKESTAND 3 TIER'],
 ["PAPER CHAIN KIT 50'S CHRISTMAS"],
 ['NATURAL SLATE HEART CHALKBOARD'],
 ['HEART OF WICKER SMALL'],
 ['VICTORIAN GLASS HANGING T-LIGHT'],
 ['JUMBO BAG RED RETROSPOT', 'WHITE HANGING HEART T-LIGHT HOLDER'],
 ['LUNCH BAG  BLACK SKULL.',
  'JUMBO BAG RED RETROSPOT',
  'WHITE HANGING HEART T-LIGHT HOLDER'],
 ['LUNCH BAG RED RETROSPOT'],
 ['LUNCH BAG  BLACK SKULL.'],
 ['JUMBO BAG RED RETROSPOT'],
 ['JAM MAKING SET WITH JARS',
  'JAM MAKING SET PRINTED',
  'RECIPE BOX PANTRY YELLOW DESIGN'],
 ['WHITE HANGING HEART T-LIGHT HOLDER', 'NATURAL SLATE HEART CHALKBOARD'],
 ['JUMBO BAG PINK POLKADOT'],
 ['RED RETROSPOT CHARLOTTE BAG',
  'LUNCH BAG RED RETROSPOT',
  'LUNCH BAG  BLACK SKULL.',
  'PACK OF 72 RETROSPOT CAKE CASES',
  'JUMBO STORAGE BAG SUKI',
  "PAPER CHAIN KIT 50'S CHRISTMAS",
  'VICTORIAN GLASS HANGING T-LIGHT',
  'JUMBO BAG PINK POLKADOT',
  'JUMBO SHOPPER VINTAGE RED PAISLEY',
  'REGENCY CAKESTAND 3 TIER',
  'HEART OF WICKER SMALL',
  'RECIPE BOX PANTRY YELLOW DESIGN',
  'GREEN REGENCY TEACUP AND SAUCER',
  'ROSES REGENCY TEACUP AND SAUCER',
  'JAM MAKING SET PRINTED',
  'ASSORTED COLOUR BIRD ORNAMENT',
  'JUMBO BAG RED RETROSPOT',
  'WHITE HANGING HEART T-LIGHT HOLDER',
  'LUNCH BAG CARS BLUE'],
 ['WHITE HANGING HEART T-LIGHT HOLDER'],
 ["PAPER CHAIN KIT 50'S CHRISTMAS",
  'LUNCH BAG PINK POLKADOT',
  'LUNCH BAG WOODLAND'],
 ['VICTORIAN GLASS HANGING T-LIGHT'],
 ['ALARM CLOCK BAKELIKE RED'],
 ['WHITE HANGING HEART T-LIGHT HOLDER',
  'WOODEN PICTURE FRAME WHITE FINISH',
  'JUMBO SHOPPER VINTAGE RED PAISLEY'],
 ['JUMBO SHOPPER VINTAGE RED PAISLEY', 'WHITE HANGING HEART T-LIGHT HOLDER'],
 ['NATURAL SLATE HEART CHALKBOARD', 'JAM MAKING SET PRINTED'],
 ['JUMBO BAG PINK POLKADOT',
  'JUMBO BAG RED RETROSPOT',
  'ASSORTED COLOUR BIRD ORNAMENT',
  'REGENCY CAKESTAND 3 TIER',
  'NATURAL SLATE HEART CHALKBOARD',
  'WHITE HANGING HEART T-LIGHT HOLDER'],
 ['WHITE HANGING HEART T-LIGHT HOLDER',
  'WOODEN PICTURE FRAME WHITE FINISH',
  'JUMBO SHOPPER VINTAGE RED PAISLEY'],
 ['WHITE HANGING HEART T-LIGHT HOLDER',
  'WOODEN PICTURE FRAME WHITE FINISH',
  'JUMBO SHOPPER VINTAGE RED PAISLEY'],
 ['JAM MAKING SET WITH JARS', 'JAM MAKING SET PRINTED'],
 ['PACK OF 72 RETROSPOT CAKE CASES', 'JAM MAKING SET PRINTED'],
 ['GREEN REGENCY TEACUP AND SAUCER'],
 ['ALARM CLOCK BAKELIKE RED',
  'ROSES REGENCY TEACUP AND SAUCER',
  'PACK OF 72 RETROSPOT CAKE CASES'],
 ['JAM MAKING SET PRINTED',
  'REGENCY CAKESTAND 3 TIER',
  'GREEN REGENCY TEACUP AND SAUCER',
  'ROSES REGENCY TEACUP AND SAUCER'],
 ['WHITE HANGING HEART T-LIGHT HOLDER',
  'WOODEN PICTURE FRAME WHITE FINISH',
  'JUMBO SHOPPER VINTAGE RED PAISLEY'],
 ['WHITE HANGING HEART T-LIGHT HOLDER',
  'WOODEN PICTURE FRAME WHITE FINISH',
  'JUMBO SHOPPER VINTAGE RED PAISLEY'],
 ['JUMBO STORAGE BAG SUKI',
  'JUMBO BAG RED RETROSPOT',
  'JUMBO BAG PINK POLKADOT',
  'JAM MAKING SET PRINTED'],
 ['JAM MAKING SET WITH JARS',
  "PAPER CHAIN KIT 50'S CHRISTMAS",
  'JAM MAKING SET PRINTED'],
 ['NATURAL SLATE HEART CHALKBOARD', 'LUNCH BAG  BLACK SKULL.'],
 ['JAM MAKING SET PRINTED'],
 ["PAPER CHAIN KIT 50'S CHRISTMAS"],
 ['PACK OF 72 RETROSPOT CAKE CASES',
  'JAM MAKING SET PRINTED',
  'JAM MAKING SET WITH JARS'],
 ['HEART OF WICKER SMALL'],
 ['JAM MAKING SET PRINTED'],
 ['JUMBO SHOPPER VINTAGE RED PAISLEY'],
 ['JUMBO BAG RED RETROSPOT', 'JUMBO BAG RED RETROSPOT'],
 ['REGENCY CAKESTAND 3 TIER', "PAPER CHAIN KIT 50'S CHRISTMAS"],
 ['HEART OF WICKER SMALL'],
 ['ASSORTED COLOUR BIRD ORNAMENT', 'REGENCY CAKESTAND 3 TIER'],
 ['WHITE HANGING HEART T-LIGHT HOLDER',
  'WOODEN PICTURE FRAME WHITE FINISH',
  'JUMBO SHOPPER VINTAGE RED PAISLEY'],
 ['WHITE HANGING HEART T-LIGHT HOLDER',
  'WOODEN PICTURE FRAME WHITE FINISH',
  'JUMBO SHOPPER VINTAGE RED PAISLEY'],
 ['NATURAL SLATE HEART CHALKBOARD', 'LUNCH BAG SPACEBOY DESIGN'],
 ['REGENCY CAKESTAND 3 TIER'],
 ['REGENCY CAKESTAND 3 TIER',
  "PAPER CHAIN KIT 50'S CHRISTMAS",
  'PACK OF 72 RETROSPOT CAKE CASES'],
 ['RECIPE BOX PANTRY YELLOW DESIGN'],
 ['JAM MAKING SET PRINTED'],
 ['NATURAL SLATE HEART CHALKBOARD', 'ASSORTED COLOUR BIRD ORNAMENT'],
 ["PAPER CHAIN KIT 50'S CHRISTMAS",
  'JUMBO STORAGE BAG SUKI',
  'HEART OF WICKER SMALL',
  'RECIPE BOX PANTRY YELLOW DESIGN'],
 ['REGENCY CAKESTAND 3 TIER'],
 ['PACK OF 72 RETROSPOT CAKE CASES',
  'ASSORTED COLOUR BIRD ORNAMENT',
  'WHITE HANGING HEART T-LIGHT HOLDER'],
 ['WHITE HANGING HEART T-LIGHT HOLDER',
  'WOODEN PICTURE FRAME WHITE FINISH',
  'JUMBO SHOPPER VINTAGE RED PAISLEY'],
 ['WHITE HANGING HEART T-LIGHT HOLDER',
  'WOODEN PICTURE FRAME WHITE FINISH',
  'JUMBO SHOPPER VINTAGE RED PAISLEY'],
 ['LUNCH BAG PINK POLKADOT', 'LUNCH BAG  BLACK SKULL.', 'LUNCH BAG WOODLAND'],
 ["PAPER CHAIN KIT 50'S CHRISTMAS"],
 ['JAM MAKING SET PRINTED', 'ALARM CLOCK BAKELIKE RED'],
 ['WHITE HANGING HEART T-LIGHT HOLDER'],
 ['RED RETROSPOT CHARLOTTE BAG',
  'LUNCH BAG RED RETROSPOT',
  'PACK OF 72 RETROSPOT CAKE CASES',
  "PAPER CHAIN KIT 50'S CHRISTMAS",
  'LUNCH BAG PINK POLKADOT',
  'LUNCH BAG  BLACK SKULL.',
  'LUNCH BAG SPACEBOY DESIGN'],
 ['JAM MAKING SET PRINTED', 'JAM MAKING SET WITH JARS'],
 ['JUMBO BAG RED RETROSPOT'],
 ['HEART OF WICKER SMALL'],
 ['PACK OF 72 RETROSPOT CAKE CASES'],
 ['PACK OF 72 RETROSPOT CAKE CASES'],
 ['ASSORTED COLOUR BIRD ORNAMENT', 'REGENCY CAKESTAND 3 TIER'],
 ['WHITE HANGING HEART T-LIGHT HOLDER', 'WOODEN PICTURE FRAME WHITE FINISH'],
 ['WHITE HANGING HEART T-LIGHT HOLDER', 'WOODEN PICTURE FRAME WHITE FINISH'],
 ['ALARM CLOCK BAKELIKE RED', 'JAM MAKING SET WITH JARS'],
 ['ALARM CLOCK BAKELIKE RED'],
 ["PAPER CHAIN KIT 50'S CHRISTMAS", 'WHITE HANGING HEART T-LIGHT HOLDER'],
 ['RED RETROSPOT CHARLOTTE BAG',
  'ASSORTED COLOUR BIRD ORNAMENT',
  'ASSORTED COLOUR BIRD ORNAMENT',
  'LUNCH BAG CARS BLUE'],
 ['JUMBO STORAGE BAG SUKI',
  'JUMBO BAG RED RETROSPOT',
  'JUMBO BAG PINK POLKADOT'],
 ['JAM MAKING SET WITH JARS',
  'JAM MAKING SET PRINTED',
  'ALARM CLOCK BAKELIKE RED'],
 ["PAPER CHAIN KIT 50'S CHRISTMAS"],
 ['REGENCY CAKESTAND 3 TIER',
  'GREEN REGENCY TEACUP AND SAUCER',
  'ASSORTED COLOUR BIRD ORNAMENT'],
 ['REGENCY CAKESTAND 3 TIER'],
 ["PAPER CHAIN KIT 50'S CHRISTMAS"],
 ['RECIPE BOX PANTRY YELLOW DESIGN'],
 ['WHITE HANGING HEART T-LIGHT HOLDER'],
 ['WHITE HANGING HEART T-LIGHT HOLDER'],
 ['WOODEN PICTURE FRAME WHITE FINISH', 'WHITE HANGING HEART T-LIGHT HOLDER'],
 ['ASSORTED COLOUR BIRD ORNAMENT'],
 ['JAM MAKING SET PRINTED', 'PACK OF 72 RETROSPOT CAKE CASES', 'POSTAGE'],
 ['ASSORTED COLOUR BIRD ORNAMENT',
  'HEART OF WICKER SMALL',
  'RED RETROSPOT CHARLOTTE BAG'],
 ['LUNCH BAG WOODLAND'],
 ['LUNCH BAG PINK POLKADOT',
  'LUNCH BAG  BLACK SKULL.',
  'LUNCH BAG RED RETROSPOT'],
 ['HEART OF WICKER SMALL',
  'RECIPE BOX PANTRY YELLOW DESIGN',
  'REGENCY CAKESTAND 3 TIER',
  'LUNCH BAG CARS BLUE',
  'LUNCH BAG SPACEBOY DESIGN'],
 ['ALARM CLOCK BAKELIKE RED'],
 ['POSTAGE'],
 ['JAM MAKING SET WITH JARS',
  'REGENCY CAKESTAND 3 TIER',
  'ROSES REGENCY TEACUP AND SAUCER',
  'GREEN REGENCY TEACUP AND SAUCER'],
 ['WHITE HANGING HEART T-LIGHT HOLDER'],
 ['POSTAGE'],
 ["PAPER CHAIN KIT 50'S CHRISTMAS", 'WHITE HANGING HEART T-LIGHT HOLDER'],
 ['POSTAGE'],
 ['LUNCH BAG RED RETROSPOT',
  'VICTORIAN GLASS HANGING T-LIGHT',
  'JUMBO BAG PINK POLKADOT',
  'REGENCY CAKESTAND 3 TIER',
  'NATURAL SLATE HEART CHALKBOARD',
  'HEART OF WICKER SMALL',
  'GREEN REGENCY TEACUP AND SAUCER',
  'JUMBO BAG RED RETROSPOT'],
 ['LUNCH BAG  BLACK SKULL.',
  'LUNCH BAG RED RETROSPOT',
  'LUNCH BAG PINK POLKADOT',
  'LUNCH BAG SPACEBOY DESIGN',
  'LUNCH BAG  BLACK SKULL.',
  'WHITE HANGING HEART T-LIGHT HOLDER',
  'JAM MAKING SET WITH JARS',
  'LUNCH BAG PINK POLKADOT'],
 ['LUNCH BAG RED RETROSPOT', 'PARTY BUNTING', 'JUMBO BAG RED RETROSPOT'],
 ['RED RETROSPOT CHARLOTTE BAG',
  'LUNCH BAG RED RETROSPOT',
  'JUMBO BAG PINK POLKADOT',
  'NATURAL SLATE HEART CHALKBOARD',
  'HEART OF WICKER SMALL',
  'RECIPE BOX PANTRY YELLOW DESIGN',
  'GREEN REGENCY TEACUP AND SAUCER',
  'ROSES REGENCY TEACUP AND SAUCER',
  'JAM MAKING SET WITH JARS',
  'PARTY BUNTING',
  'JUMBO BAG RED RETROSPOT'],
 ['JAM MAKING SET PRINTED',
  'JAM MAKING SET WITH JARS',
  'JAM MAKING SET PRINTED',
  'JUMBO BAG RED RETROSPOT'],
 ["PAPER CHAIN KIT 50'S CHRISTMAS",
  'VICTORIAN GLASS HANGING T-LIGHT',
  'LUNCH BAG SPACEBOY DESIGN',
  'LUNCH BAG PINK POLKADOT',
  'REGENCY CAKESTAND 3 TIER',
  'NATURAL SLATE HEART CHALKBOARD',
  'HEART OF WICKER SMALL',
  'GREEN REGENCY TEACUP AND SAUCER',
  'ROSES REGENCY TEACUP AND SAUCER',
  'JAM MAKING SET WITH JARS',
  'JAM MAKING SET PRINTED',
  'PARTY BUNTING',
  'WOODEN PICTURE FRAME WHITE FINISH',
  'ASSORTED COLOUR BIRD ORNAMENT',
  'JUMBO BAG RED RETROSPOT',
  'WHITE HANGING HEART T-LIGHT HOLDER',
  'RED RETROSPOT CHARLOTTE BAG',
  'LUNCH BAG RED RETROSPOT',
  'LUNCH BAG WOODLAND',
  'ASSORTED COLOUR BIRD ORNAMENT',
  "PAPER CHAIN KIT 50'S CHRISTMAS",
  'LUNCH BAG  BLACK SKULL.',
  'PACK OF 72 RETROSPOT CAKE CASES',
  'JUMBO STORAGE BAG SUKI'],
 ['JUMBO BAG PINK POLKADOT',
  'JUMBO STORAGE BAG SUKI',
  'RED RETROSPOT CHARLOTTE BAG'],
 ['HEART OF WICKER SMALL',
  "PAPER CHAIN KIT 50'S CHRISTMAS",
  'ASSORTED COLOUR BIRD ORNAMENT'],
 ['LUNCH BAG PINK POLKADOT',
  'LUNCH BAG  BLACK SKULL.',
  'LUNCH BAG RED RETROSPOT',
  'LUNCH BAG CARS BLUE'],
 ['HEART OF WICKER SMALL', 'JUMBO SHOPPER VINTAGE RED PAISLEY'],
 ["PAPER CHAIN KIT 50'S CHRISTMAS",
  'ASSORTED COLOUR BIRD ORNAMENT',
  'PACK OF 72 RETROSPOT CAKE CASES',
  'GREEN REGENCY TEACUP AND SAUCER',
  'ROSES REGENCY TEACUP AND SAUCER'],
 ['PACK OF 72 RETROSPOT CAKE CASES', 'REGENCY CAKESTAND 3 TIER'],
 ['REGENCY CAKESTAND 3 TIER', 'PARTY BUNTING'],
 ["PAPER CHAIN KIT 50'S CHRISTMAS"],
 ['POSTAGE', 'JUMBO BAG RED RETROSPOT'],
 ['REGENCY CAKESTAND 3 TIER'],
 ['JAM MAKING SET PRINTED'],
 ['HEART OF WICKER SMALL', 'NATURAL SLATE HEART CHALKBOARD'],
 ['LUNCH BAG RED RETROSPOT', 'LUNCH BAG WOODLAND', 'POSTAGE'],
 ['JUMBO SHOPPER VINTAGE RED PAISLEY', 'WHITE HANGING HEART T-LIGHT HOLDER'],
 ['REGENCY CAKESTAND 3 TIER',
  'ROSES REGENCY TEACUP AND SAUCER',
  'GREEN REGENCY TEACUP AND SAUCER'],
 ['JUMBO SHOPPER VINTAGE RED PAISLEY', 'JUMBO SHOPPER VINTAGE RED PAISLEY'],
 ['RED RETROSPOT CHARLOTTE BAG',
  'LUNCH BAG WOODLAND',
  'LUNCH BAG  BLACK SKULL.',
  'LUNCH BAG CARS BLUE',
  'PACK OF 72 RETROSPOT CAKE CASES',
  'JUMBO STORAGE BAG SUKI',
  "PAPER CHAIN KIT 50'S CHRISTMAS",
  'LUNCH BAG PINK POLKADOT',
  'JUMBO SHOPPER VINTAGE RED PAISLEY',
  'REGENCY CAKESTAND 3 TIER',
  'HEART OF WICKER SMALL',
  'ALARM CLOCK BAKELIKE RED',
  'WHITE HANGING HEART T-LIGHT HOLDER'],
 ['POSTAGE'],
 ['REGENCY CAKESTAND 3 TIER'],
 ['WHITE HANGING HEART T-LIGHT HOLDER', 'JAM MAKING SET PRINTED'],
 ["PAPER CHAIN KIT 50'S CHRISTMAS", 'JUMBO SHOPPER VINTAGE RED PAISLEY'],
 ['JUMBO STORAGE BAG SUKI'],
 ['LUNCH BAG CARS BLUE', 'POSTAGE', 'LUNCH BAG WOODLAND'],
 ['LUNCH BAG WOODLAND',
  'WHITE HANGING HEART T-LIGHT HOLDER',
  'RECIPE BOX PANTRY YELLOW DESIGN'],
 ['GREEN REGENCY TEACUP AND SAUCER', 'POSTAGE'],
 ['NATURAL SLATE HEART CHALKBOARD', 'RED RETROSPOT CHARLOTTE BAG'],
 ['LUNCH BAG CARS BLUE', 'LUNCH BAG SPACEBOY DESIGN'],
 ['PACK OF 72 RETROSPOT CAKE CASES', 'JUMBO BAG RED RETROSPOT', 'POSTAGE'],
 ['ASSORTED COLOUR BIRD ORNAMENT'],
 ["PAPER CHAIN KIT 50'S CHRISTMAS", 'REGENCY CAKESTAND 3 TIER'],
 ['REGENCY CAKESTAND 3 TIER'],
 ['ALARM CLOCK BAKELIKE RED', 'RECIPE BOX PANTRY YELLOW DESIGN'],
 ['RECIPE BOX PANTRY YELLOW DESIGN',
  'GREEN REGENCY TEACUP AND SAUCER',
  'ROSES REGENCY TEACUP AND SAUCER',
  'REGENCY CAKESTAND 3 TIER',
  'HEART OF WICKER SMALL',
  'JAM MAKING SET PRINTED',
  'RECIPE BOX PANTRY YELLOW DESIGN'],
 ['WHITE HANGING HEART T-LIGHT HOLDER'],
 ['HEART OF WICKER SMALL'],
 ['HEART OF WICKER SMALL',
  'WHITE HANGING HEART T-LIGHT HOLDER',
  'WOODEN PICTURE FRAME WHITE FINISH'],
 ["PAPER CHAIN KIT 50'S CHRISTMAS",
  'LUNCH BAG WOODLAND',
  'LUNCH BAG RED RETROSPOT'],
 ["PAPER CHAIN KIT 50'S CHRISTMAS"],
 ['LUNCH BAG SPACEBOY DESIGN', 'LUNCH BAG WOODLAND'],
 ['WHITE HANGING HEART T-LIGHT HOLDER',
  'HEART OF WICKER SMALL',
  'WHITE HANGING HEART T-LIGHT HOLDER',
  'ALARM CLOCK BAKELIKE RED',
  'ALARM CLOCK BAKELIKE RED',
  'ALARM CLOCK BAKELIKE RED'],
 ['RECIPE BOX PANTRY YELLOW DESIGN', 'REGENCY CAKESTAND 3 TIER'],
 ['HEART OF WICKER SMALL',
  'WHITE HANGING HEART T-LIGHT HOLDER',
  'LUNCH BAG CARS BLUE',
  'WHITE HANGING HEART T-LIGHT HOLDER'],
 ['WHITE HANGING HEART T-LIGHT HOLDER',
  'WOODEN PICTURE FRAME WHITE FINISH',
  'ASSORTED COLOUR BIRD ORNAMENT'],
 ["PAPER CHAIN KIT 50'S CHRISTMAS",
  'NATURAL SLATE HEART CHALKBOARD',
  'JUMBO BAG RED RETROSPOT',
  'LUNCH BAG SPACEBOY DESIGN'],
 ['PARTY BUNTING',
  'ALARM CLOCK BAKELIKE RED',
  'LUNCH BAG RED RETROSPOT',
  'LUNCH BAG WOODLAND',
  'LUNCH BAG CARS BLUE',
  'REGENCY CAKESTAND 3 TIER',
  'POSTAGE'],
 ['HEART OF WICKER SMALL'],
 ['LUNCH BAG SPACEBOY DESIGN',
  'WOODEN PICTURE FRAME WHITE FINISH',
  'ALARM CLOCK BAKELIKE RED'],
 ['WHITE HANGING HEART T-LIGHT HOLDER',
  "PAPER CHAIN KIT 50'S CHRISTMAS",
  'PACK OF 72 RETROSPOT CAKE CASES',
  'PACK OF 72 RETROSPOT CAKE CASES',
  'RECIPE BOX PANTRY YELLOW DESIGN',
  'JUMBO BAG PINK POLKADOT',
  'JUMBO STORAGE BAG SUKI',
  'JUMBO BAG RED RETROSPOT',
  'RED RETROSPOT CHARLOTTE BAG',
  'NATURAL SLATE HEART CHALKBOARD'],
 ['WHITE HANGING HEART T-LIGHT HOLDER'],
 ['RECIPE BOX PANTRY YELLOW DESIGN',
  "PAPER CHAIN KIT 50'S CHRISTMAS",
  'PARTY BUNTING'],
 ['ALARM CLOCK BAKELIKE RED', 'JAM MAKING SET WITH JARS'],
 ["PAPER CHAIN KIT 50'S CHRISTMAS", 'ASSORTED COLOUR BIRD ORNAMENT'],
 ['REGENCY CAKESTAND 3 TIER',
  'NATURAL SLATE HEART CHALKBOARD',
  'LUNCH BAG PINK POLKADOT',
  'LUNCH BAG RED RETROSPOT',
  'LUNCH BAG SPACEBOY DESIGN',
  'LUNCH BAG CARS BLUE',
  'LUNCH BAG WOODLAND',
  'JUMBO BAG RED RETROSPOT',
  'JUMBO BAG PINK POLKADOT',
  "PAPER CHAIN KIT 50'S CHRISTMAS",
  'JUMBO STORAGE BAG SUKI'],
 ['HEART OF WICKER SMALL',
  'NATURAL SLATE HEART CHALKBOARD',
  'ASSORTED COLOUR BIRD ORNAMENT',
  'RECIPE BOX PANTRY YELLOW DESIGN',
  'LUNCH BAG RED RETROSPOT',
  'RED RETROSPOT CHARLOTTE BAG',
  'LUNCH BAG CARS BLUE',
  'LUNCH BAG  BLACK SKULL.'],
 ['WHITE HANGING HEART T-LIGHT HOLDER', "PAPER CHAIN KIT 50'S CHRISTMAS"],
 ['REGENCY CAKESTAND 3 TIER'],
 ["PAPER CHAIN KIT 50'S CHRISTMAS",
  'ALARM CLOCK BAKELIKE RED',
  'ALARM CLOCK BAKELIKE RED',
  'WOODEN PICTURE FRAME WHITE FINISH'],
 ['PARTY BUNTING', 'HEART OF WICKER SMALL'],
 ["PAPER CHAIN KIT 50'S CHRISTMAS",
  'HEART OF WICKER SMALL',
  "PAPER CHAIN KIT 50'S CHRISTMAS",
  'WHITE HANGING HEART T-LIGHT HOLDER',
  "PAPER CHAIN KIT 50'S CHRISTMAS",
  'JUMBO BAG RED RETROSPOT',
  'JUMBO STORAGE BAG SUKI'],
 ['JAM MAKING SET WITH JARS'],
 ['ALARM CLOCK BAKELIKE RED',
  'RECIPE BOX PANTRY YELLOW DESIGN',
  'WOODEN PICTURE FRAME WHITE FINISH',
  'WOODEN PICTURE FRAME WHITE FINISH',
  'ALARM CLOCK BAKELIKE RED',
  'ALARM CLOCK BAKELIKE RED',
  'ALARM CLOCK BAKELIKE RED',
  'JUMBO BAG RED RETROSPOT',
  "PAPER CHAIN KIT 50'S CHRISTMAS"],
 ["PAPER CHAIN KIT 50'S CHRISTMAS"],
 ['PACK OF 72 RETROSPOT CAKE CASES', 'GREEN REGENCY TEACUP AND SAUCER'],
 ['ASSORTED COLOUR BIRD ORNAMENT',
  'ALARM CLOCK BAKELIKE RED',
  'ROSES REGENCY TEACUP AND SAUCER',
  'GREEN REGENCY TEACUP AND SAUCER'],
 ['JUMBO BAG PINK POLKADOT',
  'RECIPE BOX PANTRY YELLOW DESIGN',
  'JUMBO BAG PINK POLKADOT',
  'JAM MAKING SET PRINTED'],
 ['NATURAL SLATE HEART CHALKBOARD'],
 ["PAPER CHAIN KIT 50'S CHRISTMAS"],
 ['ASSORTED COLOUR BIRD ORNAMENT'],
 ['JAM MAKING SET PRINTED', 'POSTAGE'],

Vamos inspecionar as duas primeiras compras.

In [76]:
baskets[:2]

[['WHITE HANGING HEART T-LIGHT HOLDER'], ['ASSORTED COLOUR BIRD ORNAMENT']]

Veja que elas correspondem às primeiras duas linhas do DataFrame acima.

Por fim, precisamos ordenar esta lista em ordem decrescente de itens, para permitir sua importação com o Pandas mais tarde.

In [77]:
baskets = sorted(baskets, key=len, reverse=True)

In [78]:
baskets

[['RED RETROSPOT CHARLOTTE BAG',
  'LUNCH BAG RED RETROSPOT',
  'LUNCH BAG WOODLAND',
  'LUNCH BAG  BLACK SKULL.',
  'LUNCH BAG CARS BLUE',
  'PACK OF 72 RETROSPOT CAKE CASES',
  'JUMBO STORAGE BAG SUKI',
  "PAPER CHAIN KIT 50'S CHRISTMAS",
  'VICTORIAN GLASS HANGING T-LIGHT',
  'LUNCH BAG SPACEBOY DESIGN',
  'LUNCH BAG SUKI DESIGN',
  'LUNCH BAG PINK POLKADOT',
  'JUMBO BAG PINK POLKADOT',
  'JUMBO SHOPPER VINTAGE RED PAISLEY',
  'REGENCY CAKESTAND 3 TIER',
  'NATURAL SLATE HEART CHALKBOARD',
  'HEART OF WICKER SMALL',
  'RECIPE BOX PANTRY YELLOW DESIGN',
  'GREEN REGENCY TEACUP AND SAUCER',
  'ROSES REGENCY TEACUP AND SAUCER',
  'SET OF 3 CAKE TINS PANTRY DESIGN',
  'ALARM CLOCK BAKELIKE RED',
  'JAM MAKING SET WITH JARS',
  'JAM MAKING SET PRINTED',
  'SET OF 4 PANTRY JELLY MOULDS',
  'RABBIT NIGHT LIGHT',
  'LUNCH BAG APPLE DESIGN',
  'SPOTTY BUNTING',
  'PARTY BUNTING',
  'WOODEN PICTURE FRAME WHITE FINISH',
  'JUMBO BAG RED RETROSPOT',
  'WHITE HANGING HEART T-LIGHT HOLDER'],
 ['PACK OF 72 RETROSPOT CAKE CASES',
  'JUMBO STORAGE BAG SUKI',
  "PAPER CHAIN KIT 50'S CHRISTMAS",
  'VICTORIAN GLASS HANGING T-LIGHT',
  'LUNCH BAG SUKI DESIGN',
  'LUNCH BAG PINK POLKADOT',
  'JUMBO SHOPPER VINTAGE RED PAISLEY',
  'REGENCY CAKESTAND 3 TIER',
  'NATURAL SLATE HEART CHALKBOARD',
  'HEART OF WICKER SMALL',
  'RECIPE BOX PANTRY YELLOW DESIGN',
  'GREEN REGENCY TEACUP AND SAUCER',
  'ROSES REGENCY TEACUP AND SAUCER',
  'SET OF 3 CAKE TINS PANTRY DESIGN',
  'ALARM CLOCK BAKELIKE RED',
  'JAM MAKING SET WITH JARS',
  'JAM MAKING SET PRINTED',
  'SET OF 4 PANTRY JELLY MOULDS',
  'RABBIT NIGHT LIGHT',
  'LUNCH BAG APPLE DESIGN',
  'SPOTTY BUNTING',
  'JUMBO BAG RED RETROSPOT',
  'WHITE HANGING HEART T-LIGHT HOLDER',
  'RED RETROSPOT CHARLOTTE BAG',
  'LUNCH BAG RED RETROSPOT',
  'LUNCH BAG WOODLAND',
  'LUNCH BAG  BLACK SKULL.'],
 ['PACK OF 72 RETROSPOT CAKE CASES',
  'JUMBO STORAGE BAG SUKI',
  "PAPER CHAIN KIT 50'S CHRISTMAS",
  'VICTORIAN GLASS HANGING T-LIGHT',
  'LUNCH BAG SPACEBOY DESIGN',
  'LUNCH BAG SUKI DESIGN',
  'LUNCH BAG PINK POLKADOT',
  'REGENCY CAKESTAND 3 TIER',
  'NATURAL SLATE HEART CHALKBOARD',
  'RECIPE BOX PANTRY YELLOW DESIGN',
  'GREEN REGENCY TEACUP AND SAUCER',
  'ROSES REGENCY TEACUP AND SAUCER',
  'SET OF 3 CAKE TINS PANTRY DESIGN',
  'ALARM CLOCK BAKELIKE RED',
  'JAM MAKING SET WITH JARS',
  'JAM MAKING SET PRINTED',
  'RABBIT NIGHT LIGHT',
  'LUNCH BAG APPLE DESIGN',
  'SPOTTY BUNTING',
  'WOODEN PICTURE FRAME WHITE FINISH',
  'ASSORTED COLOUR BIRD ORNAMENT',
  'JUMBO BAG RED RETROSPOT',
  'WHITE HANGING HEART T-LIGHT HOLDER',
  'LUNCH BAG RED RETROSPOT',
  'LUNCH BAG WOODLAND',
  'LUNCH BAG  BLACK SKULL.',
  'LUNCH BAG CARS BLUE'],
 ['ALARM CLOCK BAKELIKE RED',
  'JAM MAKING SET WITH JARS',
  'JAM MAKING SET PRINTED',
  'SET OF 4 PANTRY JELLY MOULDS',
  'RABBIT NIGHT LIGHT',
  'LUNCH BAG APPLE DESIGN',
  'JUMBO BAG RED RETROSPOT',
  'WHITE HANGING HEART T-LIGHT HOLDER',
  'RED RETROSPOT CHARLOTTE BAG',
  'LUNCH BAG RED RETROSPOT',
  'LUNCH BAG  BLACK SKULL.',
  'LUNCH BAG CARS BLUE',
  'PACK OF 72 RETROSPOT CAKE CASES',
  'JUMBO STORAGE BAG SUKI',
  "PAPER CHAIN KIT 50'S CHRISTMAS",
  'VICTORIAN GLASS HANGING T-LIGHT',
  'LUNCH BAG SUKI DESIGN',
  'LUNCH BAG PINK POLKADOT',
  'REGENCY CAKESTAND 3 TIER',
  'NATURAL SLATE HEART CHALKBOARD',
  'HEART OF WICKER SMALL',
  'RECIPE BOX PANTRY YELLOW DESIGN',
  'GREEN REGENCY TEACUP AND SAUCER',
  'ROSES REGENCY TEACUP AND SAUCER',
  'SET OF 3 CAKE TINS PANTRY DESIGN'],
 ['RED RETROSPOT CHARLOTTE BAG',
  'LUNCH BAG WOODLAND',
  'LUNCH BAG  BLACK SKULL.',
  'LUNCH BAG CARS BLUE',
  'PACK OF 72 RETROSPOT CAKE CASES',
  'JUMBO STORAGE BAG SUKI',
  "PAPER CHAIN KIT 50'S CHRISTMAS",
  'VICTORIAN GLASS HANGING T-LIGHT',
  'LUNCH BAG SPACEBOY DESIGN',
  'LUNCH BAG SUKI DESIGN',
  'REGENCY CAKESTAND 3 TIER',
  'NATURAL SLATE HEART CHALKBOARD',
  'HEART OF WICKER SMALL',
  'RECIPE BOX PANTRY YELLOW DESIGN',
  'GREEN REGENCY TEACUP AND SAUCER',
  'ROSES REGENCY TEACUP AND SAUCER',
  'SET OF 3 CAKE TINS PANTRY DESIGN',
  'ALARM CLOCK BAKELIKE RED',
  'JAM MAKING SET WITH JARS',
  'JAM MAKING SET PRINTED',
  'SET OF 4 PANTRY JELLY MOULDS',
  'RABBIT NIGHT LIGHT',
  'SPOTTY BUNTING',
  'PARTY BUNTING',
  'WHITE HANGING HEART T-LIGHT HOLDER'],
 ['LUNCH BAG WOODLAND',
  'LUNCH BAG  BLACK SKULL.',
  'PACK OF 72 RETROSPOT CAKE CASES',
  'JUMBO STORAGE BAG SUKI',
  "PAPER CHAIN KIT 50'S CHRISTMAS",
  'VICTORIAN GLASS HANGING T-LIGHT',
  'LUNCH BAG SUKI DESIGN',
  'JUMBO SHOPPER VINTAGE RED PAISLEY',
  'REGENCY CAKESTAND 3 TIER',
  'NATURAL SLATE HEART CHALKBOARD',
  'RECIPE BOX PANTRY YELLOW DESIGN',
  'GREEN REGENCY TEACUP AND SAUCER',
  'ROSES REGENCY TEACUP AND SAUCER',
  'SET OF 3 CAKE TINS PANTRY DESIGN',
  'JAM MAKING SET WITH JARS',
  'JAM MAKING SET PRINTED',
  'SET OF 4 PANTRY JELLY MOULDS',
  'RABBIT NIGHT LIGHT',
  'LUNCH BAG APPLE DESIGN',
  'SPOTTY BUNTING',
  'PARTY BUNTING',
  'ASSORTED COLOUR BIRD ORNAMENT',
  'JUMBO BAG RED RETROSPOT',
  'WHITE HANGING HEART T-LIGHT HOLDER',
  'LUNCH BAG CARS BLUE'],
 ['RECIPE BOX PANTRY YELLOW DESIGN',
  'GREEN REGENCY TEACUP AND SAUCER',
  'ROSES REGENCY TEACUP AND SAUCER',
  'SET OF 3 CAKE TINS PANTRY DESIGN',
  'ALARM CLOCK BAKELIKE RED',
  'JAM MAKING SET WITH JARS',
  'JAM MAKING SET PRINTED',
  'SET OF 4 PANTRY JELLY MOULDS',
  'RABBIT NIGHT LIGHT',
  'LUNCH BAG APPLE DESIGN',
  'RED RETROSPOT CHARLOTTE BAG',
  'LUNCH BAG RED RETROSPOT',
  'LUNCH BAG CARS BLUE',
  'PACK OF 72 RETROSPOT CAKE CASES',
  'JUMBO STORAGE BAG SUKI',
  "PAPER CHAIN KIT 50'S CHRISTMAS",
  'VICTORIAN GLASS HANGING T-LIGHT',
  'LUNCH BAG SPACEBOY DESIGN',
  'LUNCH BAG SUKI DESIGN',
  'LUNCH BAG PINK POLKADOT',
  'JUMBO SHOPPER VINTAGE RED PAISLEY',
  'REGENCY CAKESTAND 3 TIER',
  'NATURAL SLATE HEART CHALKBOARD',
  'JUMBO BAG RED RETROSPOT',
  'WHITE HANGING HEART T-LIGHT HOLDER'],
 ["PAPER CHAIN KIT 50'S CHRISTMAS",
  'VICTORIAN GLASS HANGING T-LIGHT',
  'LUNCH BAG SPACEBOY DESIGN',
  'LUNCH BAG PINK POLKADOT',
  'REGENCY CAKESTAND 3 TIER',
  'NATURAL SLATE HEART CHALKBOARD',
  'HEART OF WICKER SMALL',
  'GREEN REGENCY TEACUP AND SAUCER',
  'ROSES REGENCY TEACUP AND SAUCER',
  'JAM MAKING SET WITH JARS',
  'JAM MAKING SET PRINTED',
  'PARTY BUNTING',
  'WOODEN PICTURE FRAME WHITE FINISH',
  'ASSORTED COLOUR BIRD ORNAMENT',
  'JUMBO BAG RED RETROSPOT',
  'WHITE HANGING HEART T-LIGHT HOLDER',
  'RED RETROSPOT CHARLOTTE BAG',
  'LUNCH BAG RED RETROSPOT',
  'LUNCH BAG WOODLAND',
  'ASSORTED COLOUR BIRD ORNAMENT',
  "PAPER CHAIN KIT 50'S CHRISTMAS",
  'LUNCH BAG  BLACK SKULL.',
  'PACK OF 72 RETROSPOT CAKE CASES',
  'JUMBO STORAGE BAG SUKI'],
 ['PACK OF 72 RETROSPOT CAKE CASES',
  "PAPER CHAIN KIT 50'S CHRISTMAS",
  'VICTORIAN GLASS HANGING T-LIGHT',
  'LUNCH BAG SPACEBOY DESIGN',
  'LUNCH BAG SUKI DESIGN',
  'LUNCH BAG PINK POLKADOT',
  'JUMBO SHOPPER VINTAGE RED PAISLEY',
  'REGENCY CAKESTAND 3 TIER',
  'NATURAL SLATE HEART CHALKBOARD',
  'HEART OF WICKER SMALL',
  'GREEN REGENCY TEACUP AND SAUCER',
  'ROSES REGENCY TEACUP AND SAUCER',
  'SET OF 3 CAKE TINS PANTRY DESIGN',
  'ALARM CLOCK BAKELIKE RED',
  'JAM MAKING SET WITH JARS',
  'JAM MAKING SET PRINTED',
  'SET OF 4 PANTRY JELLY MOULDS',
  'RABBIT NIGHT LIGHT',
  'LUNCH BAG APPLE DESIGN',
  'JUMBO BAG RED RETROSPOT',
  'WHITE HANGING HEART T-LIGHT HOLDER',
  'LUNCH BAG RED RETROSPOT',
  'LUNCH BAG WOODLAND',
  'LUNCH BAG  BLACK SKULL.'],
 ["PAPER CHAIN KIT 50'S CHRISTMAS",
  'VICTORIAN GLASS HANGING T-LIGHT',
  'LUNCH BAG SPACEBOY DESIGN',
  'JUMBO BAG PINK POLKADOT',
  'JUMBO SHOPPER VINTAGE RED PAISLEY',
  'REGENCY CAKESTAND 3 TIER',
  'NATURAL SLATE HEART CHALKBOARD',
  'HEART OF WICKER SMALL',
  'RECIPE BOX PANTRY YELLOW DESIGN',
  'GREEN REGENCY TEACUP AND SAUCER',
  'ROSES REGENCY TEACUP AND SAUCER',
  'SET OF 3 CAKE TINS PANTRY DESIGN',
  'ALARM CLOCK BAKELIKE RED',
  'JAM MAKING SET WITH JARS',
  'JAM MAKING SET PRINTED',
  'SET OF 4 PANTRY JELLY MOULDS',
  'RABBIT NIGHT LIGHT',
  'PARTY BUNTING',
  'JUMBO BAG RED RETROSPOT',
  'WHITE HANGING HEART T-LIGHT HOLDER',
  'LUNCH BAG RED RETROSPOT',
  'LUNCH BAG WOODLAND',
  'LUNCH BAG CARS BLUE',
  'PACK OF 72 RETROSPOT CAKE CASES'],
 ['VICTORIAN GLASS HANGING T-LIGHT',
  'LUNCH BAG SPACEBOY DESIGN',
  'JUMBO BAG PINK POLKADOT',
  'REGENCY CAKESTAND 3 TIER',
  'RED RETROSPOT CHARLOTTE BAG',
  'LUNCH BAG RED RETROSPOT',
  'LUNCH BAG WOODLAND',
  'LUNCH BAG  BLACK SKULL.',
  'LUNCH BAG CARS BLUE',
  'RECIPE BOX PANTRY YELLOW DESIGN',
  'GREEN REGENCY TEACUP AND SAUCER',
  'ROSES REGENCY TEACUP AND SAUCER',
  'SET OF 3 CAKE TINS PANTRY DESIGN',
  'JAM MAKING SET PRINTED',
  'SET OF 4 PANTRY JELLY MOULDS',
  'RABBIT NIGHT LIGHT',
  'LUNCH BAG APPLE DESIGN',
  'WOODEN PICTURE FRAME WHITE FINISH',
  'ASSORTED COLOUR BIRD ORNAMENT',
  'JUMBO BAG RED RETROSPOT',
  'WHITE HANGING HEART T-LIGHT HOLDER',
  'PACK OF 72 RETROSPOT CAKE CASES',
  'JUMBO STORAGE BAG SUKI',
  "PAPER CHAIN KIT 50'S CHRISTMAS"],
 ['LUNCH BAG APPLE DESIGN',
  'WOODEN PICTURE FRAME WHITE FINISH',
  'JUMBO BAG RED RETROSPOT',
  'RED RETROSPOT CHARLOTTE BAG',
  'LUNCH BAG RED RETROSPOT',
  'LUNCH BAG CARS BLUE',
  'PACK OF 72 RETROSPOT CAKE CASES',
  "PAPER CHAIN KIT 50'S CHRISTMAS",
  'VICTORIAN GLASS HANGING T-LIGHT',
  'LUNCH BAG SPACEBOY DESIGN',
  'LUNCH BAG SUKI DESIGN',
  'LUNCH BAG PINK POLKADOT',
  'JUMBO SHOPPER VINTAGE RED PAISLEY',
  'REGENCY CAKESTAND 3 TIER',
  'NATURAL SLATE HEART CHALKBOARD',
  'HEART OF WICKER SMALL',
  'RECIPE BOX PANTRY YELLOW DESIGN',
  'GREEN REGENCY TEACUP AND SAUCER',
  'ROSES REGENCY TEACUP AND SAUCER',
  'SET OF 3 CAKE TINS PANTRY DESIGN',
  'JAM MAKING SET WITH JARS',
  'JAM MAKING SET PRINTED',
  'SET OF 4 PANTRY JELLY MOULDS',
  'RABBIT NIGHT LIGHT'],
 ['RED RETROSPOT CHARLOTTE BAG',
  'LUNCH BAG RED RETROSPOT',
  'LUNCH BAG CARS BLUE',
  'PACK OF 72 RETROSPOT CAKE CASES',
  'JUMBO STORAGE BAG SUKI',
  "PAPER CHAIN KIT 50'S CHRISTMAS",
  'VICTORIAN GLASS HANGING T-LIGHT',
  'LUNCH BAG SUKI DESIGN',
  'JUMBO SHOPPER VINTAGE RED PAISLEY',
  'REGENCY CAKESTAND 3 TIER',
  'NATURAL SLATE HEART CHALKBOARD',
  'HEART OF WICKER SMALL',
  'GREEN REGENCY TEACUP AND SAUCER',
  'ROSES REGENCY TEACUP AND SAUCER',
  'SET OF 3 CAKE TINS PANTRY DESIGN',
  'ALARM CLOCK BAKELIKE RED',
  'JAM MAKING SET WITH JARS',
  'JAM MAKING SET PRINTED',
  'SET OF 4 PANTRY JELLY MOULDS',
  'RABBIT NIGHT LIGHT',
  'LUNCH BAG APPLE DESIGN',
  'PARTY BUNTING',
  'ASSORTED COLOUR BIRD ORNAMENT',
  'WHITE HANGING HEART T-LIGHT HOLDER'],
 ['PARTY BUNTING',
  'ASSORTED COLOUR BIRD ORNAMENT',
  'LUNCH BAG  BLACK SKULL.',
  'LUNCH BAG CARS BLUE',
  'PACK OF 72 RETROSPOT CAKE CASES',
  'JUMBO STORAGE BAG SUKI',
  "PAPER CHAIN KIT 50'S CHRISTMAS",
  'RED RETROSPOT CHARLOTTE BAG',
  'LUNCH BAG RED RETROSPOT',
  'LUNCH BAG WOODLAND',
  'VICTORIAN GLASS HANGING T-LIGHT',
  'JUMBO SHOPPER VINTAGE RED PAISLEY',
  'NATURAL SLATE HEART CHALKBOARD',
  'RECIPE BOX PANTRY YELLOW DESIGN',
  'GREEN REGENCY TEACUP AND SAUCER',
  'ROSES REGENCY TEACUP AND SAUCER',
  'SET OF 3 CAKE TINS PANTRY DESIGN',
  'ALARM CLOCK BAKELIKE RED',
  'JAM MAKING SET WITH JARS',
  'JAM MAKING SET PRINTED',
  'SET OF 4 PANTRY JELLY MOULDS',
  'RABBIT NIGHT LIGHT',
  'LUNCH BAG APPLE DESIGN',
  'SPOTTY BUNTING'],
 ['RED RETROSPOT CHARLOTTE BAG',
  'LUNCH BAG RED RETROSPOT',
  'LUNCH BAG WOODLAND',
  'LUNCH BAG  BLACK SKULL.',
  'LUNCH BAG CARS BLUE',
  'JUMBO STORAGE BAG SUKI',
  "PAPER CHAIN KIT 50'S CHRISTMAS",
  'VICTORIAN GLASS HANGING T-LIGHT',
  'LUNCH BAG SUKI DESIGN',
  'LUNCH BAG PINK POLKADOT',
  'JUMBO BAG PINK POLKADOT',
  'JUMBO SHOPPER VINTAGE RED PAISLEY',
  'REGENCY CAKESTAND 3 TIER',
  'NATURAL SLATE HEART CHALKBOARD',
  'GREEN REGENCY TEACUP AND SAUCER',
  'ROSES REGENCY TEACUP AND SAUCER',
  'SET OF 3 CAKE TINS PANTRY DESIGN',
  'JAM MAKING SET WITH JARS',
  'SET OF 4 PANTRY JELLY MOULDS',
  'SPOTTY BUNTING',
  'PARTY BUNTING',
  'WOODEN PICTURE FRAME WHITE FINISH',
  'JUMBO BAG RED RETROSPOT',
  'WHITE HANGING HEART T-LIGHT HOLDER'],
 ['LUNCH BAG SPACEBOY DESIGN',
  'JUMBO SHOPPER VINTAGE RED PAISLEY',
  'REGENCY CAKESTAND 3 TIER',
  'NATURAL SLATE HEART CHALKBOARD',
  'HEART OF WICKER SMALL',
  'RECIPE BOX PANTRY YELLOW DESIGN',
  'GREEN REGENCY TEACUP AND SAUCER',
  'ROSES REGENCY TEACUP AND SAUCER',
  'PACK OF 72 RETROSPOT CAKE CASES',
  'JUMBO STORAGE BAG SUKI',
  "PAPER CHAIN KIT 50'S CHRISTMAS",
  'VICTORIAN GLASS HANGING T-LIGHT',
  'JAM MAKING SET WITH JARS',
  'JAM MAKING SET PRINTED',
  'WOODEN PICTURE FRAME WHITE FINISH',
  'JUMBO BAG RED RETROSPOT',
  'WHITE HANGING HEART T-LIGHT HOLDER',
  'RED RETROSPOT CHARLOTTE BAG',
  'LUNCH BAG RED RETROSPOT',
  'LUNCH BAG WOODLAND',
  'LUNCH BAG  BLACK SKULL.',
  'LUNCH BAG CARS BLUE',
  'JUMBO BAG PINK POLKADOT'],
 ['JAM MAKING SET WITH JARS',
  'JAM MAKING SET PRINTED',
  'PARTY BUNTING',
  'WOODEN PICTURE FRAME WHITE FINISH',
  'ASSORTED COLOUR BIRD ORNAMENT',
  'JUMBO BAG RED RETROSPOT',
  'WHITE HANGING HEART T-LIGHT HOLDER',
  'RED RETROSPOT CHARLOTTE BAG',
  'LUNCH BAG RED RETROSPOT',
  'PACK OF 72 RETROSPOT CAKE CASES',
  'JUMBO STORAGE BAG SUKI',
  "PAPER CHAIN KIT 50'S CHRISTMAS",
  'VICTORIAN GLASS HANGING T-LIGHT',
  'JUMBO BAG PINK POLKADOT',
  'JUMBO SHOPPER VINTAGE RED PAISLEY',
  'REGENCY CAKESTAND 3 TIER',
  'REGENCY CAKESTAND 3 TIER',
  'NATURAL SLATE HEART CHALKBOARD',
  'HEART OF WICKER SMALL',
  'RECIPE BOX PANTRY YELLOW DESIGN',
  'GREEN REGENCY TEACUP AND SAUCER',
  'ROSES REGENCY TEACUP AND SAUCER',
  'ALARM CLOCK BAKELIKE RED'],
 ['LUNCH BAG SUKI DESIGN',
  'LUNCH BAG  BLACK SKULL.',
  'LUNCH BAG RED RETROSPOT',
  'LUNCH BAG SUKI DESIGN',
  'LUNCH BAG SPACEBOY DESIGN',
  'LUNCH BAG APPLE DESIGN',
  'LUNCH BAG PINK POLKADOT',
  'RED RETROSPOT CHARLOTTE BAG',
  'LUNCH BAG WOODLAND',
  'LUNCH BAG CARS BLUE',
  'LUNCH BAG APPLE DESIGN',
  'JUMBO STORAGE BAG SUKI',
  'JUMBO BAG RED RETROSPOT',
  'JUMBO BAG PINK POLKADOT',
  'SET OF 3 CAKE TINS PANTRY DESIGN',
  "PAPER CHAIN KIT 50'S CHRISTMAS",
  'SET OF 4 PANTRY JELLY MOULDS',
  'PACK OF 72 RETROSPOT CAKE CASES',
  'PACK OF 72 RETROSPOT CAKE CASES',
  'PACK OF 72 RETROSPOT CAKE CASES',
  'JAM MAKING SET WITH JARS',
  'WHITE HANGING HEART T-LIGHT HOLDER',
  'SET OF 3 CAKE TINS PANTRY DESIGN'],
 ['LUNCH BAG RED RETROSPOT',
  'LUNCH BAG WOODLAND',
  'JUMBO STORAGE BAG SUKI',
  "PAPER CHAIN KIT 50'S CHRISTMAS",
  'VICTORIAN GLASS HANGING T-LIGHT',
  'LUNCH BAG PINK POLKADOT',
  'JUMBO BAG PINK POLKADOT',
  'JUMBO SHOPPER VINTAGE RED PAISLEY',
  'REGENCY CAKESTAND 3 TIER',
  'NATURAL SLATE HEART CHALKBOARD',
  'RECIPE BOX PANTRY YELLOW DESIGN',
  'GREEN REGENCY TEACUP AND SAUCER',
  'SET OF 3 CAKE TINS PANTRY DESIGN',
  'ALARM CLOCK BAKELIKE RED',
  'JAM MAKING SET WITH JARS',
  'JAM MAKING SET PRINTED',
  'SET OF 4 PANTRY JELLY MOULDS',
  'RABBIT NIGHT LIGHT',
  'LUNCH BAG APPLE DESIGN',
  'SPOTTY BUNTING',
  'WOODEN PICTURE FRAME WHITE FINISH',
  'JUMBO BAG RED RETROSPOT',
  'WHITE HANGING HEART T-LIGHT HOLDER'],
 ['RED RETROSPOT CHARLOTTE BAG',
  'LUNCH BAG RED RETROSPOT',
  'LUNCH BAG  BLACK SKULL.',
  'PACK OF 72 RETROSPOT CAKE CASES',
  'JUMBO STORAGE BAG SUKI',
  "PAPER CHAIN KIT 50'S CHRISTMAS",
  'VICTORIAN GLASS HANGING T-LIGHT',
  'JUMBO SHOPPER VINTAGE RED PAISLEY',
  'NATURAL SLATE HEART CHALKBOARD',
  'HEART OF WICKER SMALL',
  'RECIPE BOX PANTRY YELLOW DESIGN',
  'GREEN REGENCY TEACUP AND SAUCER',
  'ROSES REGENCY TEACUP AND SAUCER',
  'ALARM CLOCK BAKELIKE RED',
  'JAM MAKING SET WITH JARS',
  'JAM MAKING SET PRINTED',
  'SET OF 4 PANTRY JELLY MOULDS',
  'RABBIT NIGHT LIGHT',
  'LUNCH BAG APPLE DESIGN',
  'SPOTTY BUNTING',
  'JUMBO BAG RED RETROSPOT',
  'WHITE HANGING HEART T-LIGHT HOLDER',
  'REGENCY CAKESTAND 3 TIER'],
 ['JUMBO BAG RED RETROSPOT',
  'LUNCH BAG  BLACK SKULL.',
  'LUNCH BAG CARS BLUE',
  'PACK OF 72 RETROSPOT CAKE CASES',
  "PAPER CHAIN KIT 50'S CHRISTMAS",
  'VICTORIAN GLASS HANGING T-LIGHT',
  'LUNCH BAG SUKI DESIGN',
  'LUNCH BAG PINK POLKADOT',
  'JUMBO SHOPPER VINTAGE RED PAISLEY',
  'NATURAL SLATE HEART CHALKBOARD',
  'HEART OF WICKER SMALL',
  'RECIPE BOX PANTRY YELLOW DESIGN',
  'GREEN REGENCY TEACUP AND SAUCER',
  'ROSES REGENCY TEACUP AND SAUCER',
  'SET OF 3 CAKE TINS PANTRY DESIGN',
  'ALARM CLOCK BAKELIKE RED',
  'JAM MAKING SET WITH JARS',
  'JAM MAKING SET PRINTED',
  'SET OF 4 PANTRY JELLY MOULDS',
  'RABBIT NIGHT LIGHT',
  'LUNCH BAG APPLE DESIGN',
  'PARTY BUNTING',
  'WOODEN PICTURE FRAME WHITE FINISH'],
 ['JUMBO BAG RED RETROSPOT',
  'RED RETROSPOT CHARLOTTE BAG',
  'LUNCH BAG RED RETROSPOT',
  'LUNCH BAG  BLACK SKULL.',
  'LUNCH BAG CARS BLUE',
  'PACK OF 72 RETROSPOT CAKE CASES',
  "PAPER CHAIN KIT 50'S CHRISTMAS",
  'LUNCH BAG SPACEBOY DESIGN',
  'LUNCH BAG PINK POLKADOT',
  'JUMBO BAG PINK POLKADOT',
  'JUMBO SHOPPER VINTAGE RED PAISLEY',
  'REGENCY CAKESTAND 3 TIER',
  'NATURAL SLATE HEART CHALKBOARD',
  'RECIPE BOX PANTRY YELLOW DESIGN',
  'ROSES REGENCY TEACUP AND SAUCER',
  'SET OF 3 CAKE TINS PANTRY DESIGN',
  'ALARM CLOCK BAKELIKE RED',
  'JAM MAKING SET WITH JARS',
  'JAM MAKING SET PRINTED',
  'SET OF 4 PANTRY JELLY MOULDS',
  'RABBIT NIGHT LIGHT',
  'LUNCH BAG APPLE DESIGN',
  'SPOTTY BUNTING'],
 ['JUMBO BAG RED RETROSPOT',
  'WHITE HANGING HEART T-LIGHT HOLDER',
  'RED RETROSPOT CHARLOTTE BAG',
  'LUNCH BAG RED RETROSPOT',
  'LUNCH BAG CARS BLUE',
  'PACK OF 72 RETROSPOT CAKE CASES',
  "PAPER CHAIN KIT 50'S CHRISTMAS",
  'VICTORIAN GLASS HANGING T-LIGHT',
  'LUNCH BAG SPACEBOY DESIGN',
  'LUNCH BAG SUKI DESIGN',
  'JUMBO SHOPPER VINTAGE RED PAISLEY',
  'REGENCY CAKESTAND 3 TIER',
  'NATURAL SLATE HEART CHALKBOARD',
  'HEART OF WICKER SMALL',
  'RECIPE BOX PANTRY YELLOW DESIGN',
  'GREEN REGENCY TEACUP AND SAUCER',
  'ROSES REGENCY TEACUP AND SAUCER',
  'SET OF 3 CAKE TINS PANTRY DESIGN',
  'JAM MAKING SET WITH JARS',
  'JAM MAKING SET PRINTED',
  'SET OF 4 PANTRY JELLY MOULDS',
  'RABBIT NIGHT LIGHT'],
 ['RED RETROSPOT CHARLOTTE BAG',
  'LUNCH BAG RED RETROSPOT',
  'LUNCH BAG  BLACK SKULL.',
  'JUMBO STORAGE BAG SUKI',
  "PAPER CHAIN KIT 50'S CHRISTMAS",
  'VICTORIAN GLASS HANGING T-LIGHT',
  'LUNCH BAG SUKI DESIGN',
  'LUNCH BAG PINK POLKADOT',
  'REGENCY CAKESTAND 3 TIER',
  'NATURAL SLATE HEART CHALKBOARD',
  'RECIPE BOX PANTRY YELLOW DESIGN',
  'GREEN REGENCY TEACUP AND SAUCER',
  'ROSES REGENCY TEACUP AND SAUCER',
  'SET OF 3 CAKE TINS PANTRY DESIGN',
  'JAM MAKING SET WITH JARS',
  'JAM MAKING SET PRINTED',
  'SET OF 4 PANTRY JELLY MOULDS',
  'RABBIT NIGHT LIGHT',
  'LUNCH BAG APPLE DESIGN',
  'SPOTTY BUNTING',
  'WOODEN PICTURE FRAME WHITE FINISH',
  'JUMBO BAG RED RETROSPOT'],
 ["PAPER CHAIN KIT 50'S CHRISTMAS",
  'VICTORIAN GLASS HANGING T-LIGHT',
  'LUNCH BAG SUKI DESIGN',
  'LUNCH BAG PINK POLKADOT',
  'JUMBO SHOPPER VINTAGE RED PAISLEY',
  'REGENCY CAKESTAND 3 TIER',
  'NATURAL SLATE HEART CHALKBOARD',
  'HEART OF WICKER SMALL',
  'RECIPE BOX PANTRY YELLOW DESIGN',
  'GREEN REGENCY TEACUP AND SAUCER',
  'ROSES REGENCY TEACUP AND SAUCER',
  'SET OF 3 CAKE TINS PANTRY DESIGN',
  'ALARM CLOCK BAKELIKE RED',
  'JAM MAKING SET WITH JARS',
  'JAM MAKING SET PRINTED',
  'SET OF 4 PANTRY JELLY MOULDS',
  'RABBIT NIGHT LIGHT',
  'LUNCH BAG APPLE DESIGN',
  'PARTY BUNTING',
  'JUMBO BAG RED RETROSPOT',
  'WHITE HANGING HEART T-LIGHT HOLDER',
  'LUNCH BAG  BLACK SKULL.'],
 ['RED RETROSPOT CHARLOTTE BAG',
  'LUNCH BAG RED RETROSPOT',
  'LUNCH BAG WOODLAND',
  'PACK OF 72 RETROSPOT CAKE CASES',
  "PAPER CHAIN KIT 50'S CHRISTMAS",
  'VICTORIAN GLASS HANGING T-LIGHT',
  'LUNCH BAG SPACEBOY DESIGN',
  'LUNCH BAG PINK POLKADOT',
  'JUMBO BAG PINK POLKADOT',
  'JUMBO SHOPPER VINTAGE RED PAISLEY',
  'REGENCY CAKESTAND 3 TIER',
  'NATURAL SLATE HEART CHALKBOARD',
  'HEART OF WICKER SMALL',
  'RECIPE BOX PANTRY YELLOW DESIGN',
  'GREEN REGENCY TEACUP AND SAUCER',
  'ROSES REGENCY TEACUP AND SAUCER',
  'ALARM CLOCK BAKELIKE RED',
  'JAM MAKING SET PRINTED',
  'PARTY BUNTING',
  'JUMBO BAG RED RETROSPOT',
  'WHITE HANGING HEART T-LIGHT HOLDER'],
 ['RED RETROSPOT CHARLOTTE BAG',
  'LUNCH BAG RED RETROSPOT',

### Vamos inspecionar de novo as duas primeiras compras.

In [79]:
baskets[:2] # duas compras, com os maiores itens comprados

[['RED RETROSPOT CHARLOTTE BAG',
  'LUNCH BAG RED RETROSPOT',
  'LUNCH BAG WOODLAND',
  'LUNCH BAG  BLACK SKULL.',
  'LUNCH BAG CARS BLUE',
  'PACK OF 72 RETROSPOT CAKE CASES',
  'JUMBO STORAGE BAG SUKI',
  "PAPER CHAIN KIT 50'S CHRISTMAS",
  'VICTORIAN GLASS HANGING T-LIGHT',
  'LUNCH BAG SPACEBOY DESIGN',
  'LUNCH BAG SUKI DESIGN',
  'LUNCH BAG PINK POLKADOT',
  'JUMBO BAG PINK POLKADOT',
  'JUMBO SHOPPER VINTAGE RED PAISLEY',
  'REGENCY CAKESTAND 3 TIER',
  'NATURAL SLATE HEART CHALKBOARD',
  'HEART OF WICKER SMALL',
  'RECIPE BOX PANTRY YELLOW DESIGN',
  'GREEN REGENCY TEACUP AND SAUCER',
  'ROSES REGENCY TEACUP AND SAUCER',
  'SET OF 3 CAKE TINS PANTRY DESIGN',
  'ALARM CLOCK BAKELIKE RED',
  'JAM MAKING SET WITH JARS',
  'JAM MAKING SET PRINTED',
  'SET OF 4 PANTRY JELLY MOULDS',
  'RABBIT NIGHT LIGHT',
  'LUNCH BAG APPLE DESIGN',
  'SPOTTY BUNTING',
  'PARTY BUNTING',
  'WOODEN PICTURE FRAME WHITE FINISH',
  'JUMBO BAG RED RETROSPOT',
  'WHITE HANGING HEART T-LIGHT HOLDER'],
 ['PACK OF 72 RETROSPOT CAKE CASES',
  'JUMBO STORAGE BAG SUKI',
  "PAPER CHAIN KIT 50'S CHRISTMAS",
  'VICTORIAN GLASS HANGING T-LIGHT',
  'LUNCH BAG SUKI DESIGN',
  'LUNCH BAG PINK POLKADOT',
  'JUMBO SHOPPER VINTAGE RED PAISLEY',
  'REGENCY CAKESTAND 3 TIER',
  'NATURAL SLATE HEART CHALKBOARD',
  'HEART OF WICKER SMALL',
  'RECIPE BOX PANTRY YELLOW DESIGN',
  'GREEN REGENCY TEACUP AND SAUCER',
  'ROSES REGENCY TEACUP AND SAUCER',
  'SET OF 3 CAKE TINS PANTRY DESIGN',
  'ALARM CLOCK BAKELIKE RED',
  'JAM MAKING SET WITH JARS',
  'JAM MAKING SET PRINTED',
  'SET OF 4 PANTRY JELLY MOULDS',
  'RABBIT NIGHT LIGHT',
  'LUNCH BAG APPLE DESIGN',
  'SPOTTY BUNTING',
  'JUMBO BAG RED RETROSPOT',
  'WHITE HANGING HEART T-LIGHT HOLDER',
  'RED RETROSPOT CHARLOTTE BAG',
  'LUNCH BAG RED RETROSPOT',
  'LUNCH BAG WOODLAND',
  'LUNCH BAG  BLACK SKULL.']]

E as duas últimas.

In [80]:
baskets[-2:]

[['POSTAGE'], ['JUMBO BAG PINK POLKADOT']]

## 4) Agora podemos salvar essas compras em um arquivo txt na pasta do Drive. Para evitar confusão com o delimitador, já que um item pode conter vírgulas em sua descrição, vamos manter o caractere `;`.

In [81]:
#na página atual
DRIVE_DIRECTORY=''
with open(os.path.join(DRIVE_DIRECTORY, "itemlist.txt"), "w") as f:
    for basket in baskets:
        f.write(";".join(basket) + "\n")

Observe como os arquivos foram salvos.

In [82]:
caminho_pasta = os.getcwd()
#print(caminho_pasta)  # Pasta onde o notebook está rodando

In [83]:
!head {caminho_pasta}/itemlist.txt

RED RETROSPOT CHARLOTTE BAG;LUNCH BAG RED RETROSPOT;LUNCH BAG WOODLAND;LUNCH BAG  BLACK SKULL.;LUNCH BAG CARS BLUE;PACK OF 72 RETROSPOT CAKE CASES;JUMBO STORAGE BAG SUKI;PAPER CHAIN KIT 50'S CHRISTMAS;VICTORIAN GLASS HANGING T-LIGHT;LUNCH BAG SPACEBOY DESIGN;LUNCH BAG SUKI DESIGN;LUNCH BAG PINK POLKADOT;JUMBO BAG PINK POLKADOT;JUMBO SHOPPER VINTAGE RED PAISLEY;REGENCY CAKESTAND 3 TIER;NATURAL SLATE HEART CHALKBOARD;HEART OF WICKER SMALL;RECIPE BOX PANTRY YELLOW DESIGN;GREEN REGENCY TEACUP AND SAUCER;ROSES REGENCY TEACUP AND SAUCER;SET OF 3 CAKE TINS PANTRY DESIGN;ALARM CLOCK BAKELIKE RED;JAM MAKING SET WITH JARS;JAM MAKING SET PRINTED;SET OF 4 PANTRY JELLY MOULDS;RABBIT NIGHT LIGHT;LUNCH BAG APPLE DESIGN;SPOTTY BUNTING;PARTY BUNTING;WOODEN PICTURE FRAME WHITE FINISH;JUMBO BAG RED RETROSPOT;WHITE HANGING HEART T-LIGHT HOLDER
PACK OF 72 RETROSPOT CAKE CASES;JUMBO STORAGE BAG SUKI;PAPER CHAIN KIT 50'S CHRISTMAS;VICTORIAN GLASS HANGING T-LIGHT;LUNCH BAG SUKI DESIGN;LUNCH BAG PINK POLKADOT;JUMBO SHOPPER VINTAGE RED PAISLEY;REGENCY CAKESTAND 3 TIER;NATURAL SLATE HEART CHALKBOARD;HEART OF WICKER SMALL;RECIPE BOX PANTRY YELLOW DESIGN;GREEN REGENCY TEACUP AND SAUCER;ROSES REGENCY TEACUP AND SAUCER;SET OF 3 CAKE TINS PANTRY DESIGN;ALARM CLOCK BAKELIKE RED;JAM MAKING SET WITH JARS;JAM MAKING SET PRINTED;SET OF 4 PANTRY JELLY MOULDS;RABBIT NIGHT LIGHT;LUNCH BAG APPLE DESIGN;SPOTTY BUNTING;JUMBO BAG RED RETROSPOT;WHITE HANGING HEART T-LIGHT HOLDER;RED RETROSPOT CHARLOTTE BAG;LUNCH BAG RED RETROSPOT;LUNCH BAG WOODLAND;LUNCH BAG  BLACK SKULL.
PACK OF 72 RETROSPOT CAKE CASES;JUMBO STORAGE BAG SUKI;PAPER CHAIN KIT 50'S CHRISTMAS;VICTORIAN GLASS HANGING T-LIGHT;LUNCH BAG SPACEBOY DESIGN;LUNCH BAG SUKI DESIGN;LUNCH BAG PINK POLKADOT;REGENCY CAKESTAND 3 TIER;NATURAL SLATE HEART CHALKBOARD;RECIPE BOX PANTRY YELLOW DESIGN;GREEN REGENCY TEACUP AND SAUCER;ROSES REGENCY TEACUP AND SAUCER;SET OF 3 CAKE TINS PANTRY DESIGN;ALARM CLOCK BAKELIKE RED;JAM MAKING SET WITH JARS;JAM MAKING SET PRINTED;RABBIT NIGHT LIGHT;LUNCH BAG APPLE DESIGN;SPOTTY BUNTING;WOODEN PICTURE FRAME WHITE FINISH;ASSORTED COLOUR BIRD ORNAMENT;JUMBO BAG RED RETROSPOT;WHITE HANGING HEART T-LIGHT HOLDER;LUNCH BAG RED RETROSPOT;LUNCH BAG WOODLAND;LUNCH BAG  BLACK SKULL.;LUNCH BAG CARS BLUE
ALARM CLOCK BAKELIKE RED;JAM MAKING SET WITH JARS;JAM MAKING SET PRINTED;SET OF 4 PANTRY JELLY MOULDS;RABBIT NIGHT LIGHT;LUNCH BAG APPLE DESIGN;JUMBO BAG RED RETROSPOT;WHITE HANGING HEART T-LIGHT HOLDER;RED RETROSPOT CHARLOTTE BAG;LUNCH BAG RED RETROSPOT;LUNCH BAG  BLACK SKULL.;LUNCH BAG CARS BLUE;PACK OF 72 RETROSPOT CAKE CASES;JUMBO STORAGE BAG SUKI;PAPER CHAIN KIT 50'S CHRISTMAS;VICTORIAN GLASS HANGING T-LIGHT;LUNCH BAG SUKI DESIGN;LUNCH BAG PINK POLKADOT;REGENCY CAKESTAND 3 TIER;NATURAL SLATE HEART CHALKBOARD;HEART OF WICKER SMALL;RECIPE BOX PANTRY YELLOW DESIGN;GREEN REGENCY TEACUP AND SAUCER;ROSES REGENCY TEACUP AND SAUCER;SET OF 3 CAKE TINS PANTRY DESIGN
RED RETROSPOT CHARLOTTE BAG;LUNCH BAG WOODLAND;LUNCH BAG  BLACK SKULL.;LUNCH BAG CARS BLUE;PACK OF 72 RETROSPOT CAKE CASES;JUMBO STORAGE BAG SUKI;PAPER CHAIN KIT 50'S CHRISTMAS;VICTORIAN GLASS HANGING T-LIGHT;LUNCH BAG SPACEBOY DESIGN;LUNCH BAG SUKI DESIGN;REGENCY CAKESTAND 3 TIER;NATURAL SLATE HEART CHALKBOARD;HEART OF WICKER SMALL;RECIPE BOX PANTRY YELLOW DESIGN;GREEN REGENCY TEACUP AND SAUCER;ROSES REGENCY TEACUP AND SAUCER;SET OF 3 CAKE TINS PANTRY DESIGN;ALARM CLOCK BAKELIKE RED;JAM MAKING SET WITH JARS;JAM MAKING SET PRINTED;SET OF 4 PANTRY JELLY MOULDS;RABBIT NIGHT LIGHT;SPOTTY BUNTING;PARTY BUNTING;WHITE HANGING HEART T-LIGHT HOLDER
LUNCH BAG WOODLAND;LUNCH BAG  BLACK SKULL.;PACK OF 72 RETROSPOT CAKE CASES;JUMBO STORAGE BAG SUKI;PAPER CHAIN KIT 50'S CHRISTMAS;VICTORIAN GLASS HANGING T-LIGHT;LUNCH BAG SUKI DESIGN;JUMBO SHOPPER VINTAGE RED PAISLEY;REGENCY CAKESTAND 3 TIER;NATURAL SLATE HEART CHALKBOARD;RECIPE BOX PANTRY YELLOW DESIGN;GREEN REGENCY TEACUP AND SAUCER;ROSES REGENCY TEACUP AND SAUCER;SET OF 3 CAKE TINS PANTRY DESIGN;JAM MAKING SET WITH JARS;JAM MAKING SET PRINTED;SET OF 4 PANTRY JELLY MOULDS;RABBIT NIGHT LIGHT;LUNCH BAG APPLE DESIGN;SPOTTY BUNTING;PARTY BUNTING;ASSORTED COLOUR BIRD ORNAMENT;JUMBO BAG RED RETROSPOT;WHITE HANGING HEART T-LIGHT HOLDER;LUNCH BAG CARS BLUE
RECIPE BOX PANTRY YELLOW DESIGN;GREEN REGENCY TEACUP AND SAUCER;ROSES REGENCY TEACUP AND SAUCER;SET OF 3 CAKE TINS PANTRY DESIGN;ALARM CLOCK BAKELIKE RED;JAM MAKING SET WITH JARS;JAM MAKING SET PRINTED;SET OF 4 PANTRY JELLY MOULDS;RABBIT NIGHT LIGHT;LUNCH BAG APPLE DESIGN;RED RETROSPOT CHARLOTTE BAG;LUNCH BAG RED RETROSPOT;LUNCH BAG CARS BLUE;PACK OF 72 RETROSPOT CAKE CASES;JUMBO STORAGE BAG SUKI;PAPER CHAIN KIT 50'S CHRISTMAS;VICTORIAN GLASS HANGING T-LIGHT;LUNCH BAG SPACEBOY DESIGN;LUNCH BAG SUKI DESIGN;LUNCH BAG PINK POLKADOT;JUMBO SHOPPER VINTAGE RED PAISLEY;REGENCY CAKESTAND 3 TIER;NATURAL SLATE HEART CHALKBOARD;JUMBO BAG RED RETROSPOT;WHITE HANGING HEART T-LIGHT HOLDER
PAPER CHAIN KIT 50'S CHRISTMAS;VICTORIAN GLASS HANGING T-LIGHT;LUNCH BAG SPACEBOY DESIGN;LUNCH BAG PINK POLKADOT;REGENCY CAKESTAND 3 TIER;NATURAL SLATE HEART CHALKBOARD;HEART OF WICKER SMALL;GREEN REGENCY TEACUP AND SAUCER;ROSES REGENCY TEACUP AND SAUCER;JAM MAKING SET WITH JARS;JAM MAKING SET PRINTED;PARTY BUNTING;WOODEN PICTURE FRAME WHITE FINISH;ASSORTED COLOUR BIRD ORNAMENT;JUMBO BAG RED RETROSPOT;WHITE HANGING HEART T-LIGHT HOLDER;RED RETROSPOT CHARLOTTE BAG;LUNCH BAG RED RETROSPOT;LUNCH BAG WOODLAND;ASSORTED COLOUR BIRD ORNAMENT;PAPER CHAIN KIT 50'S CHRISTMAS;LUNCH BAG  BLACK SKULL.;PACK OF 72 RETROSPOT CAKE CASES;JUMBO STORAGE BAG SUKI
PACK OF 72 RETROSPOT CAKE CASES;PAPER CHAIN KIT 50'S CHRISTMAS;VICTORIAN GLASS HANGING T-LIGHT;LUNCH BAG SPACEBOY DESIGN;LUNCH BAG SUKI DESIGN;LUNCH BAG PINK POLKADOT;JUMBO SHOPPER VINTAGE RED PAISLEY;REGENCY CAKESTAND 3 TIER;NATURAL SLATE HEART CHALKBOARD;HEART OF WICKER SMALL;GREEN REGENCY TEACUP AND SAUCER;ROSES REGENCY TEACUP AND SAUCER;SET OF 3 CAKE TINS PANTRY DESIGN;ALARM CLOCK BAKELIKE RED;JAM MAKING SET WITH JARS;JAM MAKING SET PRINTED;SET OF 4 PANTRY JELLY MOULDS;RABBIT NIGHT LIGHT;LUNCH BAG APPLE DESIGN;JUMBO BAG RED RETROSPOT;WHITE HANGING HEART T-LIGHT HOLDER;LUNCH BAG RED RETROSPOT;LUNCH BAG WOODLAND;LUNCH BAG  BLACK SKULL.
PAPER CHAIN KIT 50'S CHRISTMAS;VICTORIAN GLASS HANGING T-LIGHT;LUNCH BAG SPACEBOY DESIGN;JUMBO BAG PINK POLKADOT;JUMBO SHOPPER VINTAGE RED PAISLEY;REGENCY CAKESTAND 3 TIER;NATURAL SLATE HEART CHALKBOARD;HEART OF WICKER SMALL;RECIPE BOX PANTRY YELLOW DESIGN;GREEN REGENCY TEACUP AND SAUCER;ROSES REGENCY TEACUP AND SAUCER;SET OF 3 CAKE TINS PANTRY DESIGN;ALARM CLOCK BAKELIKE RED;JAM MAKING SET WITH JARS;JAM MAKING SET PRINTED;SET OF 4 PANTRY JELLY MOULDS;RABBIT NIGHT LIGHT;PARTY BUNTING;JUMBO BAG RED RETROSPOT;WHITE HANGING HEART T-LIGHT HOLDER;LUNCH BAG RED RETROSPOT;LUNCH BAG WOODLAND;LUNCH BAG CARS BLUE;PACK OF 72 RETROSPOT CAKE CASES

# 5) ir para a análise Apriori

## Algoritmo apriori

Carregue a lista de compras como um DataFrame do Pandas, lembre-se de selecionar o delimitador adequado.

In [84]:
base = pd.read_csv(os.path.join(DRIVE_DIRECTORY, "itemlist.txt"), delimiter=";", header=None)
base.tail(20)

,0,1,2,3,4,5,6,7,8,9,...,22,23,24,25,26,27,28,29,30,31
12768,POSTAGE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12769,ASSORTED COLOUR BIRD ORNAMENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12770,LUNCH BAG SPACEBOY DESIGN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12771,NATURAL SLATE HEART CHALKBOARD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12772,HEART OF WICKER SMALL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12773,PACK OF 72 RETROSPOT CAKE CASES,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12774,PAPER CHAIN KIT 50'S CHRISTMAS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12775,PAPER CHAIN KIT 50'S CHRISTMAS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12776,ASSORTED COLOUR BIRD ORNAMENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12777,LUNCH BAG CARS BLUE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12778,ASSORTED COLOUR BIRD ORNAMENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12779,LUNCH BAG CARS BLUE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12780,SET OF 4 PANTRY JELLY MOULDS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12781,RED RETROSPOT CHARLOTTE BAG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12782,JUMBO BAG RED RETROSPOT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12783,PARTY BUNTING,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12784,JUMBO BAG RED RETROSPOT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12785,POSTAGE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12786,POSTAGE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12787,JUMBO BAG PINK POLKADOT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [85]:
base.head(20)

,0,1,2,3,4,5,6,7,8,9,...,22,23,24,25,26,27,28,29,30,31
0,RED RETROSPOT CHARLOTTE BAG,LUNCH BAG RED RETROSPOT,LUNCH BAG WOODLAND,LUNCH BAG BLACK SKULL.,LUNCH BAG CARS BLUE,PACK OF 72 RETROSPOT CAKE CASES,JUMBO STORAGE BAG SUKI,PAPER CHAIN KIT 50'S CHRISTMAS,VICTORIAN GLASS HANGING T-LIGHT,LUNCH BAG SPACEBOY DESIGN,...,JAM MAKING SET WITH JARS,JAM MAKING SET PRINTED,SET OF 4 PANTRY JELLY MOULDS,RABBIT NIGHT LIGHT,LUNCH BAG APPLE DESIGN,SPOTTY BUNTING,PARTY BUNTING,WOODEN PICTURE FRAME WHITE FINISH,JUMBO BAG RED RETROSPOT,WHITE HANGING HEART T-LIGHT HOLDER
1,PACK OF 72 RETROSPOT CAKE CASES,JUMBO STORAGE BAG SUKI,PAPER CHAIN KIT 50'S CHRISTMAS,VICTORIAN GLASS HANGING T-LIGHT,LUNCH BAG SUKI DESIGN,LUNCH BAG PINK POLKADOT,JUMBO SHOPPER VINTAGE RED PAISLEY,REGENCY CAKESTAND 3 TIER,NATURAL SLATE HEART CHALKBOARD,HEART OF WICKER SMALL,...,WHITE HANGING HEART T-LIGHT HOLDER,RED RETROSPOT CHARLOTTE BAG,LUNCH BAG RED RETROSPOT,LUNCH BAG WOODLAND,LUNCH BAG BLACK SKULL.,NaN,NaN,NaN,NaN,NaN
2,PACK OF 72 RETROSPOT CAKE CASES,JUMBO STORAGE BAG SUKI,PAPER CHAIN KIT 50'S CHRISTMAS,VICTORIAN GLASS HANGING T-LIGHT,LUNCH BAG SPACEBOY DESIGN,LUNCH BAG SUKI DESIGN,LUNCH BAG PINK POLKADOT,REGENCY CAKESTAND 3 TIER,NATURAL SLATE HEART CHALKBOARD,RECIPE BOX PANTRY YELLOW DESIGN,...,WHITE HANGING HEART T-LIGHT HOLDER,LUNCH BAG RED RETROSPOT,LUNCH BAG WOODLAND,LUNCH BAG BLACK SKULL.,LUNCH BAG CARS BLUE,NaN,NaN,NaN,NaN,NaN
3,ALARM CLOCK BAKELIKE RED,JAM MAKING SET WITH JARS,JAM MAKING SET PRINTED,SET OF 4 PANTRY JELLY MOULDS,RABBIT NIGHT LIGHT,LUNCH BAG APPLE DESIGN,JUMBO BAG RED RETROSPOT,WHITE HANGING HEART T-LIGHT HOLDER,RED RETROSPOT CHARLOTTE BAG,LUNCH BAG RED RETROSPOT,...,GREEN REGENCY TEACUP AND SAUCER,ROSES REGENCY TEACUP AND SAUCER,SET OF 3 CAKE TINS PANTRY DESIGN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,RED RETROSPOT CHARLOTTE BAG,LUNCH BAG WOODLAND,LUNCH BAG BLACK SKULL.,LUNCH BAG CARS BLUE,PACK OF 72 RETROSPOT CAKE CASES,JUMBO STORAGE BAG SUKI,PAPER CHAIN KIT 50'S CHRISTMAS,VICTORIAN GLASS HANGING T-LIGHT,LUNCH BAG SPACEBOY DESIGN,LUNCH BAG SUKI DESIGN,...,SPOTTY BUNTING,PARTY BUNTING,WHITE HANGING HEART T-LIGHT HOLDER,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,LUNCH BAG WOODLAND,LUNCH BAG BLACK SKULL.,PACK OF 72 RETROSPOT CAKE CASES,JUMBO STORAGE BAG SUKI,PAPER CHAIN KIT 50'S CHRISTMAS,VICTORIAN GLASS HANGING T-LIGHT,LUNCH BAG SUKI DESIGN,JUMBO SHOPPER VINTAGE RED PAISLEY,REGENCY CAKESTAND 3 TIER,NATURAL SLATE HEART CHALKBOARD,...,JUMBO BAG RED RETROSPOT,WHITE HANGING HEART T-LIGHT HOLDER,LUNCH BAG CARS BLUE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,RECIPE BOX PANTRY YELLOW DESIGN,GREEN REGENCY TEACUP AND SAUCER,ROSES REGENCY TEACUP AND SAUCER,SET OF 3 CAKE TINS PANTRY DESIGN,ALARM CLOCK BAKELIKE RED,JAM MAKING SET WITH JARS,JAM MAKING SET PRINTED,SET OF 4 PANTRY JELLY MOULDS,RABBIT NIGHT LIGHT,LUNCH BAG APPLE DESIGN,...,NATURAL SLATE HEART CHALKBOARD,JUMBO BAG RED RETROSPOT,WHITE HANGING HEART T-LIGHT HOLDER,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,PAPER CHAIN KIT 50'S CHRISTMAS,VICTORIAN GLASS HANGING T-LIGHT,LUNCH BAG SPACEBOY DESIGN,LUNCH BAG PINK POLKADOT,REGENCY CAKESTAND 3 TIER,NATURAL SLATE HEART CHALKBOARD,HEART OF WICKER SMALL,GREEN REGENCY TEACUP AND SAUCER,ROSES REGENCY TEACUP AND SAUCER,JAM MAKING SET WITH JARS,...,PACK OF 72 RETROSPOT CAKE CASES,JUMBO STORAGE BAG SUKI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,PACK OF 72 RETROSPOT CAKE CASES,PAPER CHAIN KIT 50'S CHRISTMAS,VICTORIAN GLASS HANGING T-LIGHT,LUNCH BAG SPACEBOY DESIGN,LUNCH BAG SUKI DESIGN,LUNCH BAG PINK POLKADOT,JUMBO SHOPPER VINTAGE RED PAISLEY,REGENCY CAKESTAND 3 TIER,NATURAL SLATE HEART CHALKBOARD,HEART OF WICKER SMALL,...,LUNCH BAG WOODLAND,LUNCH BAG BLACK SKULL.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,PAPER CHAIN KIT 50'S CHRISTMAS,VICTORIAN GLASS HANGING T-LIGHT,LUNCH BAG SPACEBOY DESIGN,JUMBO BAG PINK POLKADOT,JUMBO SHOPPER VINTAGE RED PAISLEY,REGENCY CAKESTAND 3 TIER,NATURAL SLATE HEART CHALKBOARD,HEART OF WICKER SMALL,RECIPE BOX PANTRY YELLOW DESIGN,GREEN REGENCY TEACUP AND SAUCER,...,LUNCH BAG CARS BLUE,PACK OF 72 RETROSPOT CAKE CASES,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,VICTORIAN GLASS HANGING T-LIGHT,LUNCH BAG SPACEBOY DESIGN,JUMBO BAG PINK POLKADOT,REGENCY CAKESTAND 3 TIER,RED RETROSPOT CHARLOTTE BAG,LUNCH BAG RED RETROSPOT,LUNCH BAG WOODLAND,LUNCH BAG BLACK SKULL.,LUNCH BAG CARS BLUE,RECIPE BOX PANTRY YELLOW DESIGN,...,JUMBO STORAGE BAG SUKI,PAPER CHAIN KIT 50'S CHRISTMAS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,LUNCH BAG APPLE DESIGN,WOODEN PICTURE FRAME WHITE FINISH,JUMBO BAG RED RETROSPOT,RED RETROSPOT CHARLOTTE BAG,LUNCH BAG RED RETROSPOT,LUNCH BAG CARS BLUE,PACK OF 72 RETROSPOT CAKE CASES,PAPER CHAIN KIT 50'S CHRISTMAS,VICTORIAN GLASS HANGING T-LIGHT,LUNCH BAG SPACEBOY DESIGN,...,SET OF 4 PANTRY JELLY MOULDS,RABBIT NIGHT LIGHT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,RED RETROSPOT CHARLOTTE BAG,LUNCH BAG RED RETROSPOT,LUNCH BAG CARS BLUE,PACK OF 72 RETROSPOT CAKE CASES,JUMBO STORAGE BAG SUKI,PAPER CHAIN KIT 50'S CHRISTMAS,VICTORIAN GLASS HANGING T-LIGHT,LUNCH BAG SUKI DESIGN,JUMBO SHOPPER VINTAGE RED PAISLEY,REGENCY CAKESTAND 3 TIER,...,ASSORTED COLOUR BIRD ORNAMENT,WHITE HANGING HEART T-LIGHT HOLDER,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,PARTY BUNTING,ASSORTED COLOUR BIRD ORNAMENT,LUNCH BAG BLACK SKULL.,LUNCH BAG CARS BLUE,PACK OF 72 RETROSPOT CAKE CASES,JUMBO STORAGE BAG SUKI,PAPER CHAIN KIT 50'S CHRISTMAS,RED RETROSPOT CHARLOTTE BAG,LUNCH BAG RED RETROSPOT,LUNCH BAG WOODLAND,...,LUNCH BAG APPLE DESIGN,SPOTTY BUNTING,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,RED RETROSPOT CHARLOTTE BAG,LUNCH BAG RED RETROSPOT,LUNCH BAG WOODLAND,LUNCH BAG BLACK SKULL.,LUNCH BAG CARS BLUE,JUMBO STORAGE BAG SUKI,PAPER CHAIN KIT 50'S CHRISTMAS,VICTORIAN GLASS HANGING T-LIGHT,LUNCH BAG SUKI DESIGN,LUNCH BAG PINK POLKADOT,...,JUMBO BAG RED RETROSPOT,WHITE HANGING HEART T-LIGHT HOLDER,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,LUNCH BAG SPACEBOY DESIGN,JUMBO SHOPPER VINTAGE RED PAISLEY,REGENCY CAKESTAND 3 TIER,NATURAL SLATE HEART CHALKBOARD,HEART OF WICKER SMALL,RECIPE BOX PANTRY YELLOW DESIGN,GREEN REGENCY TEACUP AND SAUCER,ROSES REGENCY TEACUP AND SAUCER,PACK OF 72 RETROSPOT CAKE CASES,JUMBO STORAGE BAG SUKI,...,JUMBO BAG PINK POLKADOT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,JAM MAKING SET WITH JARS,JAM MAKING SET PRINTED,PARTY BUNTING,WOODEN PICTURE FRAME WHITE FINISH,ASSORTED COLOUR BIRD ORNAMENT,JUMBO BAG RED RETROSPOT,WHITE HANGING HEART T-LIGHT HOLDER,RED RETROSPOT CHARLOTTE BAG,LUNCH BAG RED RETROSPOT,PACK OF 72 RETROSPOT CAKE CASES,...,ALARM CLOCK BAKELIKE RED,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,LUNCH BAG SUKI DESIGN,LUNCH BAG BLACK SKULL.,LUNCH BAG RED RETROSPOT,LUNCH BAG SUKI DESIGN,LUNCH BAG SPACEBOY DESIGN,LUNCH BAG APPLE DESIGN,LUNCH BAG PINK POLKADOT,RED RETROSPOT CHARLOTTE BAG,LUNCH BAG WOODLAND,LUNCH BAG CARS BLUE,...,SET OF 3 CAKE TINS PANTRY DESIGN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,LUNCH BAG RED RETROSPOT,LUNCH BAG WOODLAND,JUMBO STORAGE BAG SUKI,PAPER CHAIN KIT 50'S CHRISTMAS,VICTORIAN GLASS HANGING T-LIGHT,LUNCH BAG PINK POLKADOT,JUMBO BAG PINK POLKADOT,JUMBO SHOPPER VINTAGE RED PAISLEY,REGENCY CAKESTAND 3 TIER,NATURAL SLATE HEART CHALKBOARD,...,WHITE HANGING HEART T-LIGHT HOLDER,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,RED RETROSPOT CHARLOTTE BAG,LUNCH BAG RED RETROSPOT,LUNCH BAG BLACK SKULL.,PACK OF 72 RETROSPOT CAKE CASES,JUMBO STORAGE BAG SUKI,PAPER CHAIN KIT 50'S CHRISTMAS,VICTORIAN GLASS HANGING T-LIGHT,JUMBO SHOPPER VINTAGE RED PAISLEY,NATURAL SLATE HEART CHALKBOARD,HEART OF WICKER SMALL,...,REGENCY CAKESTAND 3 TIER,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [86]:
# notamos que o máximo de itens e uma única compra é de 32 compras em um único cliente.

In [87]:
print(f'Compras selecionadas de cada cliente ou cada transação foram de {len(base)}.')

Compras selecionadas de cada cliente ou cada transação foram de 12788.

### Desta vez, você pode facilitar o processamento preenchendo os campos vazios com a string `nan`:

In [88]:
base.isnull().sum()

0         0
1      4437
2      7094
3      8771
4      9932
5     10713
6     11265
7     11602
8     11835
9     12041
10    12198
11    12321
12    12410
13    12501
14    12565
15    12623
16    12663
17    12700
18    12716
19    12736
20    12752
21    12763
22    12766
23    12773
24    12781
25    12785
26    12785
27    12787
28    12787
29    12787
30    12787
31    12787
dtype: int64

In [90]:
base.fillna("nan", inplace=True)

In [92]:
base.tail(1)

,0,1,2,3,4,5,6,7,8,9,...,22,23,24,25,26,27,28,29,30,31
12787,JUMBO BAG PINK POLKADOT,nan,nan,nan,nan,nan,nan,nan,nan,nan,...,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan

#### Agora converta o dataframe em uma lista de listas, primeiro chamando o atributo `values`, depois o método `tolist`:

In [93]:
transactions = base.values.tolist()

In [96]:
transactions[:1]

[['RED RETROSPOT CHARLOTTE BAG',
  'LUNCH BAG RED RETROSPOT',
  'LUNCH BAG WOODLAND',
  'LUNCH BAG  BLACK SKULL.',
  'LUNCH BAG CARS BLUE',
  'PACK OF 72 RETROSPOT CAKE CASES',
  'JUMBO STORAGE BAG SUKI',
  "PAPER CHAIN KIT 50'S CHRISTMAS",
  'VICTORIAN GLASS HANGING T-LIGHT',
  'LUNCH BAG SPACEBOY DESIGN',
  'LUNCH BAG SUKI DESIGN',
  'LUNCH BAG PINK POLKADOT',
  'JUMBO BAG PINK POLKADOT',
  'JUMBO SHOPPER VINTAGE RED PAISLEY',
  'REGENCY CAKESTAND 3 TIER',
  'NATURAL SLATE HEART CHALKBOARD',
  'HEART OF WICKER SMALL',
  'RECIPE BOX PANTRY YELLOW DESIGN',
  'GREEN REGENCY TEACUP AND SAUCER',
  'ROSES REGENCY TEACUP AND SAUCER',
  'SET OF 3 CAKE TINS PANTRY DESIGN',
  'ALARM CLOCK BAKELIKE RED',
  'JAM MAKING SET WITH JARS',
  'JAM MAKING SET PRINTED',
  'SET OF 4 PANTRY JELLY MOULDS',
  'RABBIT NIGHT LIGHT',
  'LUNCH BAG APPLE DESIGN',
  'SPOTTY BUNTING',
  'PARTY BUNTING',
  'WOODEN PICTURE FRAME WHITE FINISH',
  'JUMBO BAG RED RETROSPOT',
  'WHITE HANGING HEART T-LIGHT HOLDER']]

#### Por curiosidade, inspecione a transação de índice 300.

In [98]:
transactions[300] # produtos compraoos

['PARTY BUNTING',
 'REGENCY CAKESTAND 3 TIER',
 'SET OF 4 PANTRY JELLY MOULDS',
 'VICTORIAN GLASS HANGING T-LIGHT',
 'LUNCH BAG RED RETROSPOT',
 'LUNCH BAG CARS BLUE',
 'LUNCH BAG WOODLAND',
 'LUNCH BAG  BLACK SKULL.',
 'LUNCH BAG SPACEBOY DESIGN',
 'LUNCH BAG SUKI DESIGN',
 'LUNCH BAG PINK POLKADOT',
 'WHITE HANGING HEART T-LIGHT HOLDER',
 'PACK OF 72 RETROSPOT CAKE CASES',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan',
 'nan']

### Agora invoque o algoritmo `apriori`, informando as transações, `min_support=0.02`, `min_confidence=0.25` e `min_lift=5`.

In [99]:

n_vezes_vendas = 4
semana_dia = 7

compras = n_vezes_vendas*semana_dia

print('compras',compras)

qtd_pessoas_comprou_local = len(base)
print('qtd. de pessoas que compraram no local',qtd_pessoas_comprou_local)

print('suporte')
# divisão de produtos vendidos/ quantidades totais de produtos 
print(compras/qtd_pessoas_comprou_local) # valor que é a base para o suporte na regra apriori
# valor os produtos que são vendidos 4 vezes ao dia, na nossa base de dados

compras 28
qtd. de pessoas que compraram no local 12788
suporte
0.002189552705661558

In [101]:
rules = apriori(transactions, min_support=0.02, min_confidence=0.25, min_lift=5)

### Execute o algoritmo, convertendo as regras para uma lista.

In [102]:
results = list(rules)

Cheque quantas regras foram geradas.

In [103]:
len(results)

78

In [107]:
import prettyprinter as pp
pp.pprint(results)
print('\nquantidade de dados:', len(resultados)) # quantidade de dados diminuiram

[
    apyori.RelationRecord(
        items=frozenset([
            'ROSES REGENCY TEACUP AND SAUCER',
            'GREEN REGENCY TEACUP AND SAUCER'
        ]),
        support=0.057162965279949955,
        ordered_statistics=[
            apyori.OrderedStatistic(
                items_base=frozenset(['GREEN REGENCY TEACUP AND SAUCER']),
                items_add=frozenset(['ROSES REGENCY TEACUP AND SAUCER']),
                confidence=0.7497435897435898,
                lift=9.464680183258665
            ),
            apyori.OrderedStatistic(
                items_base=frozenset(['ROSES REGENCY TEACUP AND SAUCER']),
                items_add=frozenset(['GREEN REGENCY TEACUP AND SAUCER']),
                confidence=0.721618953603159,
                lift=9.464680183258663
            )
        ]
    ),
    apyori.RelationRecord(
        items=frozenset([
            'LUNCH BAG  BLACK SKULL.',
            'LUNCH BAG PINK POLKADOT'
        ]),
        support=0.04183609634031905,
        ordered_statistics=[
            apyori.OrderedStatistic(
                items_base=frozenset(['LUNCH BAG  BLACK SKULL.']),
                items_add=frozenset(['LUNCH BAG PINK POLKADOT']),
                confidence=0.4246031746031746,
                lift=5.060415094897854
            ),
            apyori.OrderedStatistic(
                items_base=frozenset(['LUNCH BAG PINK POLKADOT']),
                items_add=frozenset(['LUNCH BAG  BLACK SKULL.']),
                confidence=0.49860205032618826,
                lift=5.060415094897854
            )
        ]
    ),
    apyori.RelationRecord(
        items=frozenset(['LUNCH BAG SUKI DESIGN', 'LUNCH BAG APPLE DESIGN']),
        support=0.03479824835783547,
        ordered_statistics=[
            apyori.OrderedStatistic(
                items_base=frozenset(['LUNCH BAG APPLE DESIGN']),
                items_add=frozenset(['LUNCH BAG SUKI DESIGN']),
                confidence=0.4354207436399218,
                lift=5.165269452381558
            ),
            apyori.OrderedStatistic(
                items_base=frozenset(['LUNCH BAG SUKI DESIGN']),
                items_add=frozenset(['LUNCH BAG APPLE DESIGN']),
                confidence=0.4128014842300557,
                lift=5.165269452381558
            )
        ]
    ),
    apyori.RelationRecord(
        items=frozenset(['LUNCH BAG CARS BLUE', 'LUNCH BAG PINK POLKADOT']),
        support=0.03878636221457617,
        ordered_statistics=[
            apyori.OrderedStatistic(
                items_base=frozenset(['LUNCH BAG CARS BLUE']),
                items_add=frozenset(['LUNCH BAG PINK POLKADOT']),
                confidence=0.4381625441696113,
                lift=5.222015484474362
            ),
            apyori.OrderedStatistic(
                items_base=frozenset(['LUNCH BAG PINK POLKADOT']),
                items_add=frozenset(['LUNCH BAG CARS BLUE']),
                confidence=0.462255358807083,
                lift=5.222015484474362
            )
        ]
    ),
    apyori.RelationRecord(
        items=frozenset(['LUNCH BAG SPACEBOY DESIGN', 'LUNCH BAG WOODLAND']),
        support=0.03722239599624648,
        ordered_statistics=[
            apyori.OrderedStatistic(
                items_base=frozenset(['LUNCH BAG SPACEBOY DESIGN']),
                items_add=frozenset(['LUNCH BAG WOODLAND']),
                confidence=0.4149956408020924,
                lift=5.28582097069438
            ),
            apyori.OrderedStatistic(
                items_base=frozenset(['LUNCH BAG WOODLAND']),
                items_add=frozenset(['LUNCH BAG SPACEBOY DESIGN']),
                confidence=0.4741035856573705,
                lift=5.28582097069438
            )
        ]
    ),
    apyori.RelationRecord(
        items=frozenset([
            'ROSES REGENCY TEACUP AND SAUCER',
            'GREEN REGENCY TEACUP AND SAUCER',
            'REGENCY CAKESTAND 3 TIER'
        ]),
        support=0.029715358148264,
        ordered_statistics=[
            apyori.OrderedStatistic(
                items_base=frozenset(['GREEN REGENCY TEACUP AND SAUCER']),
                items_add=frozenset([
                    'ROSES REGENCY TEACUP AND SAUCER',
                    'REGENCY CAKESTAND 3 TIER'
                ]),
                confidence=0.38974358974358975,
                lift=10.192312935871218
            ),
            apyori.OrderedStatistic(
                items_base=frozenset(['ROSES REGENCY TEACUP AND SAUCER']),
                items_add=frozenset([
                    'GREEN REGENCY TEACUP AND SAUCER',
                    'REGENCY CAKESTAND 3 TIER'
                ]),
                confidence=0.3751233958538993,
                lift=9.973135106402628
            ),
            apyori.OrderedStatistic(
                items_base=frozenset([
                    'GREEN REGENCY TEACUP AND SAUCER',
                    'REGENCY CAKESTAND 3 TIER'
                ]),
                items_add=frozenset(['ROSES REGENCY TEACUP AND SAUCER']),
                confidence=0.7900207900207901,
                lift=9.97313510640263
            ),
            apyori.OrderedStatistic(
                items_base=frozenset([
                    'ROSES REGENCY TEACUP AND SAUCER',
                    'REGENCY CAKESTAND 3 TIER'
                ]),
                items_add=frozenset(['GREEN REGENCY TEACUP AND SAUCER']),
                confidence=0.7770961145194275,
                lift=10.19231293587122
            )
        ]
    ),
    apyori.RelationRecord(
        items=frozenset([
            'ROSES REGENCY TEACUP AND SAUCER',
            'GREEN REGENCY TEACUP AND SAUCER',
            'nan'
        ]),
        support=0.05708476696903347,
        ordered_statistics=[
            apyori.OrderedStatistic(
                items_base=frozenset(['GREEN REGENCY TEACUP AND SAUCER']),
                items_add=frozenset([
                    'ROSES REGENCY TEACUP AND SAUCER',
                    'nan'
                ]),
                confidence=0.7487179487179487,
                lift=9.461072261072262
            ),
            apyori.OrderedStatistic(
                items_base=frozenset(['ROSES REGENCY TEACUP AND SAUCER']),
                items_add=frozenset([
                    'GREEN REGENCY TEACUP AND SAUCER',
                    'nan'
                ]),
                confidence=0.7206317867719645,
                lift=9.461436641930064
            ),
            apyori.OrderedStatistic(
                items_base=frozenset([
                    'GREEN REGENCY TEACUP AND SAUCER',
                    'nan'
                ]),
                items_add=frozenset(['ROSES REGENCY TEACUP AND SAUCER']),
                confidence=0.7494866529774128,
                lift=9.461436641930064
            ),
            apyori.OrderedStatistic(
                items_base=frozenset([
                    'ROSES REGENCY TEACUP AND SAUCER',
                    'nan'
                ]),
                items_add=frozenset(['GREEN REGENCY TEACUP AND SAUCER']),
                confidence=0.7213438735177866,
                lift=9.461072261072262
            )
        ]
    ),
    apyori.RelationRecord(
        items=frozenset([
            'JUMBO BAG RED RETROSPOT',
            'JUMBO SHOPPER VINTAGE RED PAISLEY',
            'JUMBO BAG PINK POLKADOT'
        ]),
        support=0.029480763215514544,
        ordered_statistics=[
            apyori.OrderedStatistic(
                items_base=frozenset(['JUMBO BAG PINK POLKADOT']),
                items_add=frozenset([
                    'JUMBO BAG RED RETROSPOT',
                    'JUMBO SHOPPER VINTAGE RED PAISLEY'
                ]),
                confidence=0.31131296449215523,
                lift=5.889157085688877
            ),
            apyori.OrderedStatistic(
                items_base=frozenset(['JUMBO SHOPPER VINTAGE RED PAISLEY']),
                items_add=frozenset([
                    'JUMBO BAG RED RETROSPOT',
                    'JUMBO BAG PINK POLKADOT'
                ]),
                confidence=0.323327615780446,
                lift=5.0484902937733125
            ),
            apyori.OrderedStatistic(
                items_base=frozenset([
                    'JUMBO BAG RED RETROSPOT',
                    'JUMBO BAG PINK POLKADOT'
                ]),
                items_add=frozenset(['JUMBO SHOPPER VINTAGE RED PAISLEY']),
                confidence=0.4603174603174603,
                lift=5.0484902937733125
            ),
            apyori.OrderedStatistic(
                items_base=frozenset([
                    'JUMBO SHOPPER VINTAGE RED PAISLEY',
                    'JUMBO BAG PINK POLKADOT'
                ]),
                items_add=frozenset(['JUMBO BAG RED RETROSPOT']),
                confidence=0.8072805139186295,
                lift=5.001697292631509
            ),
            apyori.OrderedStatistic(
                items_base=frozenset([
                    'JUMBO BAG RED RETROSPOT',
                    'JUMBO SHOPPER VINTAGE RED PAISLEY'
                ]),
                items_add=frozenset(['JUMBO BAG PINK POLKADOT']),
                confidence=0.5576923076923077,
                lift=5.889157085688878
            )
        ]
    ),
    apyori.RelationRecord(
        items=frozenset([
            'JUMBO STORAGE BAG SUKI',
            'JUMBO BAG RED RETROSPOT',
            'JUMBO BAG PINK POLKADOT'
        ]),
        support=0.03221770409759149,
        ordered_statistics=[
            apyori.OrderedStatistic(
                items_base=frozenset(['JUMBO BAG PINK POLKADOT']),
                items_add=frozenset([
                    'JUMBO STORAGE BAG SUKI',
                    'JUMBO BAG RED RETROSPOT'
                ]),
                confidence=0.34021469859620146,
                lift=6.034210215878258
            ),
            apyori.OrderedStatistic(
                items_base=frozenset(['JUMBO STORAGE BAG SUKI']),
                items_add=frozenset([
                    'JUMBO BAG RED RETROSPOT',
                    'JUMBO BAG PINK POLKADOT'
                ]),
                confidence=0.3497453310696095,
                lift=5.460980822610703
            ),
            apyori.OrderedStatistic(
                items_base=frozenset([
                    'JUMBO BAG RED RETROSPOT',
                    'JUMBO BAG PINK POLKADOT'
                ]),
                items_add=frozenset(['JUMBO STORAGE BAG SUKI']),
                confidence=0.503052503052503,
                lift=5.460980822610703
            ),
            apyori.OrderedStatistic(
                items_base=frozenset([
                    'JUMBO STORAGE BAG SUKI',
                    'JUMBO BAG RED RETROSPOT'
                ]),
                items_add=frozenset(['JUMBO BAG PINK POLKADOT']),
                confidence=0.5714285714285714,
                lift=6.034210215878258
            )
        ]
    ),
    apyori.RelationRecord(
        items=frozenset([
            'JUMBO STORAGE BAG SUKI',
            'JUMBO SHOPPER VINTAGE RED PAISLEY',
            'JUMBO BAG PINK POLKADOT'
        ]),
        support=0.024085079762277136,
        ordered_statistics=[
            apyori.OrderedStatistic(
                items_base=frozenset(['JUMBO BAG PINK POLKADOT']),
                items_add=frozenset([
                    'JUMBO STORAGE BAG SUKI',
                    'JUMBO SHOPPER VINTAGE RED PAISLEY'
                ]),
                confidence=0.254335260115607,
                lift=6.2546909737661185
            ),
            apyori.OrderedStatistic(
                items_base=frozenset(['JUMBO SHOPPER VINTAGE RED PAISLEY']),
                items_add=frozenset([
                    'JUMBO STORAGE BAG SUKI',
                    'JUMBO BAG PINK POLKADOT'
                ]),
                confidence=0.26415094339622647,
                lift=6.571911019748919
            ),
            apyori.OrderedStatistic(
                items_base=frozenset(['JUMBO STORAGE BAG SUKI']),
                items_add=frozenset([
                    'JUMBO SHOPPER VINTAGE RED PAISLEY',
                    'JUMBO BAG PINK POLKADOT'
                ]),
                confidence=0.2614601018675721,
                lift=7.159639791611375
            ),
            apyori.OrderedStatistic(
                items_base=frozenset([
                    'JUMBO SHOPPER VINTAGE RED PAISLEY',
                    'JUMBO BAG PINK POLKADOT'
                ]),
                items_add=frozenset(['JUMBO STORAGE BAG SUKI']),
                confidence=0.6595289079229122,
                lift=7.159639791611376
            ),
            apyori.OrderedStatistic(
                items_base=frozenset([
                    'JUMBO STORAGE BAG SUKI',
                    'JUMBO BAG PINK POLKADOT'
                ]),
                items_add=frozenset(['JUMBO SHOPPER VINTAGE RED PAISLEY']),
                confidence=0.5992217898832686,
                lift=6.571911019748918
            ),
            apyori.OrderedStatistic(
                items_base=frozenset([
                    'JUMBO STORAGE BAG SUKI',
                    'JUMBO SHOPPER VINTAGE RED PAISLEY'
                ]),
                items_add=frozenset(['JUMBO BAG PINK POLKADOT']),
                confidence=0.5923076923076923,
                lift=6.2546909737661185
            )
        ]
    ),
    apyori.RelationRecord(
        items=frozenset([
            'JUMBO STORAGE BAG SUKI',
            'JUMBO BAG RED RETROSPOT',
            'JUMBO SHOPPER VINTAGE RED PAISLEY'
        ]),
        support=0.030340944635595873,
        ordered_statistics=[
            apyori.OrderedStatistic(
                items_base=frozenset(['JUMBO SHOPPER VINTAGE RED PAISLEY']),
                items_add=frozenset([
                    'JUMBO STORAGE BAG SUKI',
                    'JUMBO BAG RED RETROSPOT'
                ]),
                confidence=0.33276157804459694,
                lift=5.90201811377851
            ),
            apyori.OrderedStatistic(
                items_base=frozenset(['JUMBO STORAGE BAG SUKI']),
                items_add=frozenset([
                    'JUMBO BAG RED RETROSPOT',
                    'JUMBO SHOPPER VINTAGE RED PAISLEY'
                ]),
                confidence=0.3293718166383701,
                lift=6.230779276880884
            ),
            apyori.OrderedStatistic(
                items_base=frozenset([
                    'JUMBO BAG RED RETROSPOT',
                    'JUMBO SHOPPER VINTAGE RED PAISLEY'
                ]),
                items_add=frozenset(['JUMBO STORAGE BAG SUKI']),
                confidence=0.5739644970414202,
                lift=6.230779276880884
            ),
            apyori.OrderedStatistic(
                items_base=frozenset([
                    'JUMBO STORAGE BAG SUKI',
                    'JUMBO BAG RED RETROSPOT'
                ]),
                items_add=frozenset(['JUMBO SHOPPER VINTAGE RED PAISLEY']),
                confidence=0.5381414701803051,
                lift=5.902018113778509
            )
        ]
    ),
    apyori.RelationRecord(
        items=frozenset([
            'LUNCH BAG RED RETROSPOT',
            'LUNCH BAG  BLACK SKULL.',
            'LUNCH BAG APPLE DESIGN'
        ]),
        support=0.02103534563653425,
        ordered_statistics=[
            apyori.OrderedStatistic(
                items_base=frozenset(['LUNCH BAG APPLE DESIGN']),
                items_add=frozenset([
                    'LUNCH BAG RED RETROSPOT',
                    'LUNCH BAG  BLACK SKULL.'
                ]),
                confidence=0.26320939334637966,
                lift=5.3258255096732645
            ),
            apyori.OrderedStatistic(
                items_base=frozenset([
                    'LUNCH BAG  BLACK SKULL.',
                    'LUNCH BAG APPLE DESIGN'
                ]),
                items_add=frozenset(['LUNCH BAG RED RETROSPOT']),
                confidence=0.6545012165450121,
                lift=5.431383229836221
            ),
            apyori.OrderedStatistic(
                items_base=frozenset([
                    'LUNCH BAG RED RETROSPOT',
                    'LUNCH BAG  BLACK SKULL.'
                ]),
                items_add=frozenset(['LUNCH BAG APPLE DESIGN']),
                confidence=0.425632911392405,
                lift=5.325825509673264
            ),
            apyori.OrderedStatistic(
                items_base=frozenset([
                    'LUNCH BAG RED RETROSPOT',
                    'LUNCH BAG APPLE DESIGN'
                ]),
                items_add=frozenset(['LUNCH BAG  BLACK SKULL.']),
                confidence=0.558091286307054,
                lift=5.664183626424291
            )
        ]
    ),
    apyori.RelationRecord(
        items=frozenset([
            'LUNCH BAG SUKI DESIGN',
            'LUNCH BAG  BLACK SKULL.',
            'LUNCH BAG APPLE DESIGN'
        ]),
        support=0.020722552392868313,
        ordered_statistics=[
            apyori.OrderedStatistic(
                items_base=frozenset(['LUNCH BAG APPLE DESIGN']),
                items_add=frozenset([
                    'LUNCH BAG SUKI DESIGN',
                    'LUNCH BAG  BLACK SKULL.'
                ]),
                confidence=0.25929549902152643,
                lift=6.476310237279844
            ),
            apyori.OrderedStatistic(
                items_base=frozenset([
                    'LUNCH BAG  BLACK SKULL.',
                    'LUNCH BAG APPLE DESIGN'
                ]),
                items_add=frozenset(['LUNCH BAG SUKI DESIGN']),
                confidence=0.6447688564476886,
                lift=7.648705135670724
            ),
            apyori.OrderedStatistic(
                items_base=frozenset([
                    'LUNCH BAG SUKI DESIGN',
                    'LUNCH BAG  BLACK SKULL.'
                ]),
                items_add=frozenset(['LUNCH BAG APPLE DESIGN']),
                confidence=0.5175781249999999,
                lift=6.476310237279843
            ),
            apyori.OrderedStatistic(
                items_base=frozenset([
                    'LUNCH BAG SUKI DESIGN',
                    'LUNCH BAG APPLE DESIGN'
                ]),
                items_add=frozenset(['LUNCH BAG  BLACK SKULL.']),
                confidence=0.595505617977528,
                lift=6.043909398965577
            )
        ]
    ),
    apyori.RelationRecord(
        items=frozenset([
            'LUNCH BAG CARS BLUE',
            'LUNCH BAG  BLACK SKULL.',
            'LUNCH BAG PINK POLKADOT'
        ]),
        support=0.02400688145136065,
        ordered_statistics=[
            apyori.OrderedStatistic(
                items_base=frozenset(['LUNCH BAG CARS BLUE']),
                items_add=frozenset([
                    'LUNCH BAG  BLACK SKULL.',
                    'LUNCH BAG PINK POLKADOT'
                ]),
                confidence=0.2712014134275618,
                lift=6.4824741587133845
            ),
            apyori.OrderedStatistic(
                items_base=frozenset(['LUNCH BAG PINK POLKADOT']),
                items_add=frozenset([
                    'LUNCH BAG CARS BLUE',
                    'LUNCH BAG  BLACK SKULL.'
                ]),
                confidence=0.28611369990680335,
                lift=7.063362923567956
            ),
            apyori.OrderedStatistic(
                items_base=frozenset([
                    'LUNCH BAG CARS BLUE',
                    'LUNCH BAG  BLACK SKULL.'
                ]),
                items_add=frozenset(['LUNCH BAG PINK POLKADOT']),
                confidence=0.5926640926640927,
                lift=7.063362923567957
            ),
            apyori.OrderedStatistic(
                items_base=frozenset([
                    'LUNCH BAG  BLACK SKULL.',
                    'LUNCH BAG PINK POLKADOT'

NameError: name 'resultados' is not defined

In [110]:
print(results[0])
print()
print(results[0][0])
print()
print(results[0][1])
print()
print(results[0][2])

RelationRecord(items=frozenset({'ROSES REGENCY TEACUP AND SAUCER', 'GREEN REGENCY TEACUP AND SAUCER'}), support=0.057162965279949955, ordered_statistics=[OrderedStatistic(items_base=frozenset({'GREEN REGENCY TEACUP AND SAUCER'}), items_add=frozenset({'ROSES REGENCY TEACUP AND SAUCER'}), confidence=0.7497435897435898, lift=9.464680183258665), OrderedStatistic(items_base=frozenset({'ROSES REGENCY TEACUP AND SAUCER'}), items_add=frozenset({'GREEN REGENCY TEACUP AND SAUCER'}), confidence=0.721618953603159, lift=9.464680183258663)])

frozenset({'ROSES REGENCY TEACUP AND SAUCER', 'GREEN REGENCY TEACUP AND SAUCER'})

0.057162965279949955

[OrderedStatistic(items_base=frozenset({'GREEN REGENCY TEACUP AND SAUCER'}), items_add=frozenset({'ROSES REGENCY TEACUP AND SAUCER'}), confidence=0.7497435897435898, lift=9.464680183258665), OrderedStatistic(items_base=frozenset({'ROSES REGENCY TEACUP AND SAUCER'}), items_add=frozenset({'GREEN REGENCY TEACUP AND SAUCER'}), confidence=0.721618953603159, lift=9.464680183258663)]

In [111]:
print(results[0][2][0][0]) # primeira regra "se"
print()
print(results[0][2][0][1]) # segunda regra "então"
print()
print(results[0][2][0][2]) # confiança
print()
print(results[0][2][0][3]) # valores do lift

frozenset({'GREEN REGENCY TEACUP AND SAUCER'})

frozenset({'ROSES REGENCY TEACUP AND SAUCER'})

0.7497435897435898

9.464680183258665

## 6) Utilize o mesmo código de parsing apresentado em aula para organizar os resultados em um DataFrame.

In [112]:
A = []
B = []
support = []
confidence = []
lift = []

for result in results:
    s = result[1]
    result_rules = result[2]
    for result_rule in result_rules:
        a = list(result_rule[0])
        b = list(result_rule[1])
        c = result_rule[2]
        l = result_rule[3]
        A.append(a)
        B.append(b)
        support.append(s)
        confidence.append(c)
        lift.append(l)

In [114]:
rules_df = pd.DataFrame({'A': A, 'B': B, 'support': support, 'confidence': confidence, 'lift': lift})

In [115]:
rules_df.tail()

,A,B,support,confidence,lift
480,"[JUMBO STORAGE BAG SUKI, nan, JUMBO SHOPPER VI...","[JUMBO BAG RED RETROSPOT, JUMBO BAG PINK POLKA...",0.020801,0.512524,8.002635
481,"[JUMBO BAG RED RETROSPOT, nan, JUMBO SHOPPER V...",[JUMBO STORAGE BAG SUKI],0.020801,0.707447,7.679822
482,"[JUMBO STORAGE BAG SUKI, JUMBO BAG RED RETROSP...",[JUMBO SHOPPER VINTAGE RED PAISLEY],0.020801,0.647202,7.098129
483,"[JUMBO STORAGE BAG SUKI, nan, JUMBO SHOPPER VI...",[JUMBO BAG RED RETROSPOT],0.020801,0.866450,5.368293
484,"[JUMBO STORAGE BAG SUKI, JUMBO BAG RED RETROSP...",[JUMBO BAG PINK POLKADOT],0.020801,0.687339,7.258204

# 7) Exiba o DataFrame com os resultados, ordenado de forma decrescente por valor de lift.

In [116]:
rules_df.sort_values(by = 'lift', ascending = False).tail(25)

,A,B,support,confidence,lift
106,"[LUNCH BAG SUKI DESIGN, nan]",[LUNCH BAG APPLE DESIGN],0.034720,0.412256,5.158447
393,"[LUNCH BAG CARS BLUE, LUNCH BAG WOODLAND, nan]",[LUNCH BAG RED RETROSPOT],0.021270,0.621005,5.153411
389,"[LUNCH BAG CARS BLUE, LUNCH BAG WOODLAND]","[LUNCH BAG RED RETROSPOT, nan]",0.021270,0.619590,5.145011
79,"[LUNCH BAG SPACEBOY DESIGN, LUNCH BAG BLACK S...",[LUNCH BAG RED RETROSPOT],0.024554,0.619329,5.139510
305,"[LUNCH BAG SPACEBOY DESIGN, LUNCH BAG BLACK S...",[LUNCH BAG RED RETROSPOT],0.024476,0.618577,5.133266
301,"[LUNCH BAG SPACEBOY DESIGN, LUNCH BAG BLACK S...","[LUNCH BAG RED RETROSPOT, nan]",0.024476,0.617357,5.126468
52,"[LUNCH BAG CARS BLUE, LUNCH BAG BLACK SKULL.]",[LUNCH BAG RED RETROSPOT],0.024945,0.615830,5.110471
260,"[LUNCH BAG CARS BLUE, LUNCH BAG BLACK SKULL.,...",[LUNCH BAG RED RETROSPOT],0.024867,0.615087,5.104304
255,"[LUNCH BAG CARS BLUE, LUNCH BAG BLACK SKULL.]","[LUNCH BAG RED RETROSPOT, nan]",0.024867,0.613900,5.097759
3,[LUNCH BAG PINK POLKADOT],[LUNCH BAG BLACK SKULL.],0.041836,0.498602,5.060415
2,[LUNCH BAG BLACK SKULL.],[LUNCH BAG PINK POLKADOT],0.041836,0.424603,5.060415
76,"[nan, LUNCH BAG PINK POLKADOT]",[LUNCH BAG BLACK SKULL.],0.041758,0.498134,5.055668
73,[LUNCH BAG BLACK SKULL.],"[nan, LUNCH BAG PINK POLKADOT]",0.041758,0.423810,5.055668
74,[LUNCH BAG PINK POLKADOT],"[LUNCH BAG BLACK SKULL., nan]",0.041758,0.497670,5.054968
75,"[LUNCH BAG BLACK SKULL., nan]",[LUNCH BAG PINK POLKADOT],0.041758,0.424146,5.054968
20,"[JUMBO BAG RED RETROSPOT, JUMBO BAG PINK POLKA...",[JUMBO SHOPPER VINTAGE RED PAISLEY],0.029481,0.460317,5.048490
19,[JUMBO SHOPPER VINTAGE RED PAISLEY],"[JUMBO BAG RED RETROSPOT, JUMBO BAG PINK POLKA...",0.029481,0.323328,5.048490
197,"[JUMBO BAG RED RETROSPOT, nan, JUMBO BAG PINK ...",[JUMBO SHOPPER VINTAGE RED PAISLEY],0.029403,0.459658,5.041254
192,[JUMBO SHOPPER VINTAGE RED PAISLEY],"[JUMBO BAG RED RETROSPOT, nan, JUMBO BAG PINK ...",0.029403,0.322470,5.041254
196,"[nan, JUMBO SHOPPER VINTAGE RED PAISLEY]","[JUMBO BAG RED RETROSPOT, JUMBO BAG PINK POLKA...",0.029403,0.322747,5.039421
193,"[JUMBO BAG RED RETROSPOT, JUMBO BAG PINK POLKA...","[nan, JUMBO SHOPPER VINTAGE RED PAISLEY]",0.029403,0.459096,5.039421
122,"[LUNCH BAG SPACEBOY DESIGN, LUNCH BAG CARS BLUE]",[LUNCH BAG RED RETROSPOT],0.022599,0.604603,5.017298
375,"[LUNCH BAG SPACEBOY DESIGN, LUNCH BAG CARS BLU...",[LUNCH BAG RED RETROSPOT],0.022521,0.603774,5.010420
370,"[LUNCH BAG SPACEBOY DESIGN, LUNCH BAG CARS BLUE]","[LUNCH BAG RED RETROSPOT, nan]",0.022521,0.602510,5.003184
21,"[JUMBO SHOPPER VINTAGE RED PAISLEY, JUMBO BAG ...",[JUMBO BAG RED RETROSPOT],0.029481,0.807281,5.001697

In [117]:
rules_df.sort_values(by = 'lift', ascending = False).head(5)

,A,B,support,confidence,lift
13,"[ROSES REGENCY TEACUP AND SAUCER, REGENCY CAKE...",[GREEN REGENCY TEACUP AND SAUCER],0.029715,0.777096,10.192313
10,[GREEN REGENCY TEACUP AND SAUCER],"[ROSES REGENCY TEACUP AND SAUCER, REGENCY CAKE...",0.029715,0.389744,10.192313
180,"[ROSES REGENCY TEACUP AND SAUCER, REGENCY CAKE...",[GREEN REGENCY TEACUP AND SAUCER],0.029637,0.776639,10.186322
173,[GREEN REGENCY TEACUP AND SAUCER],"[ROSES REGENCY TEACUP AND SAUCER, REGENCY CAKE...",0.029637,0.388718,10.186322
177,"[ROSES REGENCY TEACUP AND SAUCER, REGENCY CAKE...","[GREEN REGENCY TEACUP AND SAUCER, nan]",0.029637,0.775051,10.175928