In [1]:
import sys
print(sys.executable)

/home/fabiene/anaconda3/envs/Maq2/bin/python

https://googlechromelabs.github.io/chrome-for-testing/
https://storage.googleapis.com/chrome-for-testing-public/126.0.6478.182/linux64/chromedriver-linux64.zip

https://googlechromelabs.github.io/chrome-for-testing/


Atualização

Google Chrome 152.0.7977.64

ChromeDriver 130.0.6723.116


chromedriver	linux64	https://storage.googleapis.com/chrome-for-testing-public/153.0.8010.36/linux64/chromedriver-linux64.zip

(base) fabiene@notebook:~/Documentos/Fabiene/PYTHON_CURSO_LIRA_C2/instalacao_chromedriver_parabaixarnoPython$ cd chromedriver_062026/
    
(base) fabiene@notebook:~/Documentos/Fabiene/PYTHON_CURSO_LIRA_C2/instalacao_chromedriver_parabaixarnoPython/chromedriver_062026$ ls
    
chromedriver-linux64  chromedriver-linux64.zip
(base) fabiene@notebook:~/Documentos/Fabiene/PYTHON_CURSO_LIRA_C2/instalacao_chromedriver_parabaixarnoPython/chromedriver_062026$ cd chromedriver-linux64/

(base) fabiene@notebook:~/Documentos/Fabiene/PYTHON_CURSO_LIRA_C2/instalacao_chromedriver_parabaixarnoPython/chromedriver_062026/chromedriver-linux64$ ls -ltr
total 23952
    
-rw-r--r-- 1 fabiene fabiene  1582815 set  7 12:29 THIRD_PARTY_NOTICES.chromedriver
-rw-r--r-- 1 fabiene fabiene     1536 set  7 12:29 LICENSE.chromedriver
-rwxr-xr-x 1 fabiene fabiene 22936152 set  7 12:29 chromedriver
    
(base) fabiene@notebook:~/Documentos/Fabiene/PYTHON_CURSO_LIRA_C2/instalacao_chromedriver_parabaixarnoPython/chromedriver_062026/chromedriver-linux64$ conda activate Maq2

(Maq2) fabiene@notebook:~/Documentos/Fabiene/PYTHON_CURSO_LIRA_C2/instalacao_chromedriver_parabaixarnoPython/chromedriver_062026/chromedriver-linux64$ sudo cp chromedriver /usr/local/bin/
[sudo] senha para fabiene: 
    
(Maq2) fabiene@notebook:~/Documentos/Fabiene/PYTHON_CURSO_LIRA_C2/instalacao_chromedriver_parabaixarnoPython/chromedriver_062026/chromedriver-linux64$ 


(Maq2) fabiene@notebook:~/Documentos/Fabiene/PYTHON_CURSO_LIRA_C2/instalacao_chromedriver_parabaixarnoPython/chromedriver_062026/chromedriver-linux64$ sudo rm /usr/local/bin/chromedriver

(Maq2)
 fabiene@notebook:~/Documentos/Fabiene/PYTHON_CURSO_LIRA_C2/instalacao_chromedriver_parabaixarnoPython/chromedriver_062026/chromedriver-linux64$ which chromedriver

(Maq2) fabiene@notebook:~/Documentos/Fabiene/PYTHON_CURSO_LIRA_C2/instalacao_chromedriver_parabaixarnoPython/chromedriver_062026/chromedriver-linux64$ python -m pip install -U seleni


(Maq2)fabiene@notebook:~/Documentos/Fabiene/PYTHON_CURSO_LIRA_C2/instalacao_chromedriver_parabaixarnoPython/chromedriver_062026/chromedriver-linux64$ cd chromedriver-linux64/

(Maq2) fabiene@notebook:~/Documentos/Fabiene/PYTHON_CURSO_LIRA_C2/instalacao_chromedriver_parabaixarnoPython/chromedriver_062026/chromedriver-linux64/chromedriver-linux64$ sudo cp chromedriver /usr/local/bin/

(Maq2) fabiene@notebook:~/Documentos/Fabiene/PYTHON_CURSO_LIRA_C2/instalacao_chromedriver_parabaixarnoPython/chromedriver_062026/chromedriver-linux64$ wget https://storage.googleapis.com/chrome-for-testing-public/152.0.7977.82/linux64/chromedriver-linux64.zip



(Maq2) fabiene@notebook:~/Documentos/Fabiene/PYTHON_CURSO_LIRA_C2/instalacao_chromedriver_parabaixarnoPython/chromedriver_062026/chromedriver-linux64$ unzip chromedriver-linux64.zip

(Maq2) fabiene@notebook:~/Documentos/Fabiene/PYTHON_CURSO_LIRA_C2/instalacao_chromedriver_parabaixarnoPython/chromedriver_062026/chromedriver-linux64$ 
m(Maq2) fabiene@notebook:~/Documentos/Fabiene/PYTHON_CURSO_LIRA_C2/instalacao_chromedriver_parabaixarnoPython/chromedriver_062026/chromedriver-linux64$ cd chromedriver-linux64/


(Maq2) fabiene@notebook:~/Documentos/Fabiene/PYTHON_CURSO_LIRA_C2/instalacao_chromedriver_parabaixarnoPython/chromedriver_062026/chromedriver-linux64/chromedriver-linux64$ sudo cp chromedriver /usr/local/bin/

In [2]:
from selenium.webdriver.common.keys import Keys
from selenium import webdriver
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By
from selenium.webdriver.support.wait import WebDriverWait
from time import sleep
import os
#import wget

from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By

import requests
import pandas as pd
from bs4 import BeautifulSoup
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
import json

import time

#site geral
#http://www2.cemaden.gov.br/mapainterativo/

#SP
#SUDESTE
site_SP='http://resources.cemaden.gov.br/graficos/interativo/grafico_CEMADEN.php?idpcd=13654&uf=SP'
#site_SP ='http://resources.cemaden.gov.br/graficos/interativo/grafico_CEMADEN.php?idpcd=9857&uf=SP'
site_RJ = 'http://resources.cemaden.gov.br/graficos/interativo/grafico_CEMADEN.php?idpcd=3537&uf=RJ'
site_MG='http://resources.cemaden.gov.br/graficos/interativo/grafico_CEMADEN.php?idpcd=9427&uf=MG'
site_ES='http://resources.cemaden.gov.br/graficos/interativo/grafico_CEMADEN.php?idpcd=9839&uf=ES'

#CENTRO_OESTE


site_MS= 'http://resources.cemaden.gov.br/graficos/interativo/grafico_CEMADEN.php?idpcd=7922&uf=MS'
site_MT='http://resources.cemaden.gov.br/graficos/interativo/grafico_CEMADEN.php?idpcd=7902&uf=MT'
site_GO ='http://resources.cemaden.gov.br/graficos/interativo/grafico_CEMADEN.php?idpcd=7881&uf=GO'
site_DF= 'http://resources.cemaden.gov.br/graficos/interativo/grafico_CEMADEN.php?idpcd=7878&uf=DF'

#SUL
site_PR='http://resources.cemaden.gov.br/graficos/interativo/grafico_CEMADEN.php?idpcd=8475&uf=PR'
#site_PR = 'http://resources.cemaden.gov.br/graficos/interativo/grafico_CEMADEN.php?idpcd=8905&uf=PR'
site_SC='http://resources.cemaden.gov.br/graficos/interativo/grafico_CEMADEN.php?idpcd=8911&uf=SC'
site_RS='http://resources.cemaden.gov.br/graficos/interativo/grafico_CEMADEN.php?idpcd=7366&uf=RS'
#site_RS='http://resources.cemaden.gov.br/graficos/interativo/grafico_CEMADEN.php?idpcd=7371&uf=RS'

#NORDESTE
#site_BA = 'http://resources.cemaden.gov.br/graficos/interativo/grafico_CEMADEN.php?idpcd=8859&uf=BA'
site_BA= 'http://resources.cemaden.gov.br/graficos/interativo/grafico_CEMADEN.php?idpcd=8249&uf=BA'
site_PI='http://resources.cemaden.gov.br/graficos/interativo/grafico_CEMADEN.php?idpcd=9496&uf=PI'
site_RN='http://resources.cemaden.gov.br/graficos/interativo/grafico_CEMADEN.php?idpcd=9510&uf=RN'
site_MA='http://resources.cemaden.gov.br/graficos/interativo/grafico_CEMADEN.php?idpcd=7994&uf=MA'
site_AL= 'http://resources.cemaden.gov.br/graficos/interativo/grafico_CEMADEN.php?idpcd=8830&uf=AL'
site_PE='http://resources.cemaden.gov.br/graficos/interativo/grafico_CEMADEN.php?idpcd=9052&uf=PE'
site_SE='http://resources.cemaden.gov.br/graficos/interativo/grafico_CEMADEN.php?idpcd=7102&uf=SE'
site_CE='http://resources.cemaden.gov.br/graficos/interativo/grafico_CEMADEN.php?idpcd=8447&uf=CE'
site_PB='http://resources.cemaden.gov.br/graficos/interativo/grafico_CEMADEN.php?idpcd=8368&uf=PB'

#NORTE
site_PA='http://resources.cemaden.gov.br/graficos/interativo/grafico_CEMADEN.php?idpcd=9115&uf=PA'
site_AM='http://resources.cemaden.gov.br/graficos/interativo/grafico_CEMADEN.php?idpcd=9680&uf=AM'
site_AP='http://resources.cemaden.gov.br/graficos/interativo/grafico_CEMADEN.php?idpcd=9122&uf=AP'
site_TO='http://resources.cemaden.gov.br/graficos/interativo/grafico_CEMADEN.php?idpcd=9486&uf=TO'
site_AC='http://resources.cemaden.gov.br/graficos/interativo/grafico_CEMADEN.php?idpcd=9674&uf=AC'
site_RR='http://resources.cemaden.gov.br/graficos/interativo/grafico_CEMADEN.php?idpcd=9741&uf=RR'
site_RO='http://resources.cemaden.gov.br/graficos/interativo/grafico_CEMADEN.php?idpcd=3014&uf=RO'

estado_quero_ver = 'Nao'

while(estado_quero_ver != 'SP' or estado_quero_ver != 'RJ'or estado_quero_ver != 'PR' or estado_quero_ver != 'MS' or estado_quero_ver != 'BA'):
    estado_quero_ver = input('Digite a sigla dos Estados que eu quero verificar a chuva: ')
    print(estado_quero_ver)
    estado_quero_ver= estado_quero_ver.upper()
    if estado_quero_ver == 'SP':
        print(site_SP)
        site_desejado=site_SP
        break
    elif estado_quero_ver == 'RJ':
        print(site_RJ)
        site_desejado=site_RJ
        break
    elif estado_quero_ver == 'MG':
        print(site_MG)
        site_desejado=site_MG
        break
    elif estado_quero_ver == 'ES':
        print(site_ES)
        site_desejado=site_ES
        break

    
    elif estado_quero_ver == 'PR':
        print(site_PR)
        site_desejado=site_PR
        break 
    elif estado_quero_ver == 'SC':
        print(site_SC)
        site_desejado=site_SC
        break 
    elif estado_quero_ver == 'RS':
        print(site_RS)
        site_desejado=site_RS
        break 
        
    elif estado_quero_ver == 'MS':
        print(site_MS)
        site_desejado=site_MS
        break 
    elif estado_quero_ver == 'MT':
        print(site_MT)
        site_desejado=site_MT
        break         
    elif estado_quero_ver == 'GO':
        print(site_GO)
        site_desejado=site_GO
        break         
    elif estado_quero_ver == 'DF':
        print(site_DF)
        site_desejado=site_DF
        break         

    
    elif estado_quero_ver == 'BA':
        print(site_BA)
        site_desejado= site_BA
        break 
    elif estado_quero_ver == 'PI':
        print(site_PI)
        site_desejado= site_PI
        break 
    elif estado_quero_ver == 'RN':
        print(site_RN)
        site_desejado= site_RN
        break         
    elif estado_quero_ver == 'MA':
        print(site_MA)
        site_desejado= site_MA
        break  
    elif estado_quero_ver == 'AL':
        print(site_AL)
        site_desejado= site_AL
        break  
    elif estado_quero_ver == 'PE':
        print(site_PE)
        site_desejado= site_PE
        break  
    elif estado_quero_ver == 'SE':
        print(site_SE)
        site_desejado= site_SE
        break      
    elif estado_quero_ver == 'CE':
        print(site_CE)
        site_desejado= site_CE
        break          
    elif estado_quero_ver == 'PB':
        print(site_PB)
        site_desejado= site_PB
        break   


    
    
    
    elif estado_quero_ver == 'PA':
        print(site_PA)
        site_desejado= site_PA
        break 
    elif estado_quero_ver == 'AM':
        print(site_AM)
        site_desejado= site_AM
        break     
    elif estado_quero_ver == 'AP':
        print(site_AP)
        site_desejado= site_AP
        break     
    elif estado_quero_ver == 'TO':
        print(site_TO)
        site_desejado= site_TO
        break     
    elif estado_quero_ver == 'AC':
        print(site_AC)
        site_desejado= site_AC
        break    
    elif estado_quero_ver == 'RR':
        print(site_RR)
        site_desejado= site_RR
        break  
    elif estado_quero_ver == 'RO':
        print(site_RO)
        site_desejado= site_RO
        break  

    
    
    else:
        print('digitar a sigla do estado correto')

Digite a sigla dos Estados que eu quero verificar a chuva:  SP

SP
http://resources.cemaden.gov.br/graficos/interativo/grafico_CEMADEN.php?idpcd=13654&uf=SP

# coletando os dados do site

In [3]:
#browser = webdriver.Chrome("./chromedriver")
browser = webdriver.Chrome()

browser.get(site_desejado)

time.sleep(5)


#browser.set_page_load_timeout(30)  # Increase timeout to 30 seconds (or any desired value)

In [4]:
import pandas as pd
import requests
from bs4 import BeautifulSoup



element = browser.find_element(By.XPATH, '//*[@id="infopcds"]')
html_content = element.get_attribute('outerHTML')  
soup = BeautifulSoup(html_content, 'html.parser')
table = soup.find_all('table')

In [5]:
df_table = pd.read_html(str(table))    
Base_dados = pd.DataFrame(df_table[0])
display(Base_dados)

/tmp/ipykernel_18222/2159559448.py:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df_table = pd.read_html(str(table))

Empty DataFrame
Columns: [(Carregando..., UF, SP, SP, SP, SP, SP, SP, SP, SP, SP, SP, SP, SP, SP, SP, SP, SP, SP, SP, SP, SP, SP, SP, SP, SP, SP, SP, SP, SP, SP, SP, SP, SP, SP, SP, SP, SP, SP, SP, SP, SP, SP, SP, SP, SP, SP, SP, SP, SP, SP, SP, SP, SP, SP, SP, SP, SP, SP, SP, SP, SP, SP, SP, SP, SP, SP, SP, SP, SP, SP, SP, SP, SP, SP, SP, SP, SP, SP, SP, SP, SP, SP, SP, SP, SP, SP, SP, SP, SP, SP, SP, SP, SP, SP, SP, SP, SP, SP, SP, ...), (Carregando..., Cidade, SÃO BERNARDO DO CAMPO, CACHOEIRA PAULISTA, DIADEMA, SANTOS, PIRACAIA, UBATUBA, GUARUJÁ, LORENA, SÃO PAULO, CAMPOS DO JORDÃO, SANTO ANDRÉ, ILHA COMPRIDA, CAJAMAR, ARARAQUARA, SÃO PAULO, PARIQUERA-AÇU, AVARÉ, SANTOS, ELDORADO, FRANCISCO MORATO, OSASCO, UBATUBA, MAIRIPORÃ, CAJATI, CUBATÃO, JUQUITIBA, SÃO PAULO, CAMPINAS, SÃO PAULO, SÃO SEBASTIÃO, GUARUJÁ, UBATUBA, ESPÍRITO SANTO DO PINHAL, ITARIRI, ITUPEVA, CHARQUEADA, CUBATÃO, CAMPINAS, SÃO PAULO, MONGAGUÁ, SANTOS, SANTO ANDRÉ, GUARUJÁ, RIO GRANDE DA SERRA, EMBU-GUAÇU, GUARUJÁ, REGISTRO, SOROCABA, RIBEIRÃO PIRES, VINHEDO, MAIRIPORÃ, GUARUJÁ, CAMPOS DO JORDÃO, SANTA MARIA DA SERRA, CAJATI, SÃO PAULO, JUNDIAÍ, CACHOEIRA PAULISTA, VARGEM GRANDE DO SUL, CAIEIRAS, GUARUJÁ, UBATUBA, SÃO PEDRO, SANTANA DE PARNAÍBA, NOVA ODESSA, CAIEIRAS, CARAPICUÍBA, RIO GRANDE DA SERRA, ITAQUAQUECETUBA, SÃO PAULO, SÃO PAULO, ITANHAÉM, SÃO PAULO, COTIA, CAJAMAR, UBATUBA, ROSEIRA, SÃO VICENTE, PORTO FELIZ, PEREIRAS, CAMPOS DO JORDÃO, SÃO BERNARDO DO CAMPO, JUMIRIM, SANTOS, TORRE DE PEDRA, MOMBUCA, HORTOLÂNDIA, IBIÚNA, CARAGUATATUBA, ARARAQUARA, SÃO JOSÉ DO RIO PRETO, PERUÍBE, LINS, ALUMÍNIO, UBATUBA, UBATUBA, DIADEMA, SÃO PAULO, ...), (Unnamed: 2_level_0, Nome, Brazilia Tondi de Lima, LIM/INPE (TESTES), Elias Costa, Morro de São Bento, Garagem da PM, Figueira, Cachoeira, Rio Mandi, CEU São Rafael, Vila Albertina Torre Vanguarda, João Dias, Balneário Meu Recanto, Ponunduva, Jardim Brasil, São Mateus, Centro, Jurumirim, Nicho VI - Monte Serrat, Centro, Jardim Vassouras, Quitauna, Estufa II, Estrada da Roseira, Centro, EE Duarte Caetano - Cota 200, Centro, Penha3, Rio Capivari, Vila Maria, Enseada, Forte dos Andradas, Tenório, Ribeirão dos Porcos, Ana Dias, Guacuri, Base da GCM, Vila Esperança, Barão Geraldo, Itaquera2, Agua Branca, Caminho - Monte Serrat, Vila João Ramalho, Pereque, Vila Lopes, Jardim Flórida, Vila Baiana, Vila São Francisco, Éden, Pilar Velho, Centro, Vila Nova Juqueri, Jardim São Miguel, Nova Suiça, Centro, Jacupiranguinha, Jardim Paraná, Jardim Florestal, HIDRO CAMPBELL (TESTES), Centro, Vila Angelica, Jardim Helena Maria, Picinguaba, Portal das Flores, Refugio dos Bandeirantes, Centro, Jardim Vera Tereza, Altos da Santa Lúcia, Vila São João, Vila Bartira, Jardim Santa Lucrécia, Vila Rubi, Centro, Cangaíba, Caucaia do Alto, São Benedito, Poruba, Delegacia de Policia, Morro Voturuá, Centro, Centro, Sabesp - Vila Britânia, Vila São Pedro, Centro, HUVET - Morro Marapé, Centro, Centro, Jardim Santa Esmeralda, Rio do Una, Rio Claro, Vila Independência, São Francisco, Jardim Veneza, Corrego Campestre, Rio Pirajibu, Ipiranguinha, Almada, Jardim Novo Lar, Perus, ...), (ACUMULADOS [ HR ], Data (Horário UTC), 01/11/25 06:10, 15/01/25 14:10, 30/04/23 01:10, 04/09/23 07:50, 07/02/26 14:00, 04/04/26 23:50, 15/03/24 03:20, 14/09/26 20:10, 09/05/25 16:10, 09/02/26 12:50, 12/06/26 12:10, 12/09/26 18:20, 14/09/26 20:00, 21/08/24 10:40, 14/09/26 01:50, 09/05/25 16:20, 28/03/25 15:00, 14/09/26 20:10, 17/10/23 14:10, 13/08/26 12:20, 24/11/23 16:00, 04/04/26 16:30, 15/03/26 16:00, 23/07/26 08:30, 21/05/25 14:00, 14/03/25 13:30, 07/04/24 22:30, 12/02/22 07:30, 19/07/26 00:10, 12/09/26 14:50, 02/09/26 10:30, 22/07/26 12:10, 14/09/26 20:10, 14/09/26 20:00, 05/08/26 16:00, 24/07/26 21:30, 11/12/24 05:20, 13/09/26 20:10, 11/09/26 15:10, 08/10/22 18:30, 29/07/23 20:40, 17/04/26 19:00, 11/09/26 21:10, 14/09/26 20:00, 14/09/26 19:50, 12/09/26 00:10, 04/09/26 01:10, 20/05/26 01:40, 14/09/26 16:00, 14/09/26 20:30, 14/06/25 21:50, 14/09/26 20:40, 06/05/22 14:30, 20/05/25 14:10, 16/04/24 02:50, 14/09/26 20:00, 01/02/26 15:30, 14/07/26 14:00, 23/06/24 14:00, 18/02/25 11:20, 14/09/26 19:50, 14/09/26 19:30, 25/07/26 08:00, 20/10/24 14:00, 14/09/26 18:50, 08/02/26 01:50, 10/12/25 14:10, 25/06/22 09:10, 19/02/24 12:00, 02/05/23 12:00, 31/07/25 21:20, 17/08/26 13:40, 14/09/26 20:30, 09/09/26 13:50, 28/11/23 15:10, 17/06/26 03:10, 19/03/25 16:40, 29/11/25 14:00, 04/09/26 15:50, 11/10/23 00:50, 04/09/26 17:40, 23/04/25 20:30, 27/11/24 11:00, 15/10/23 14:10, 10/06/24 17:10, 29/05/24 19:00, 14/05/26 16:10, 17/01/26 04:20, 11/09/26 23:40, 19/03/26 10:20, 12/09/26 18:20, 23/12/22 13:40, 31/12/16 23:00, 14/09/26 20:10, 09/03/26 23:30, 11/03/26 15:20, 31/08/22 18:00, 14/09/26 19:50, ...), (ACUMULADOS [ HR ], Último, 0, 0, 0, 0, 0, 0, 0.2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.2, 0, 6, 0, 0.4, 0.2, 0, 0.2, 0, 0.4, 0, 0, 0.2, 0, 0, 0, 0, 0.2, 0, 0, 0, 0, 0.2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1.2, 0.6, 0.2, 0, 0, 0, 0, 0, 0, 0, 0.42, 0, 0, 0.4, 0, 0, 0, 0, 0, 0, 0, 0.2, 0, 0.2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.2, 0, 0, 0, 0, 0, 0, 0.39, 0, 0, 0, ...), (ACUMULADOS [ HR ], 1, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, ...), (ACUMULADOS [ HR ], 6, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, ...), (ACUMULADOS [ HR ], 12, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, ...), (ACUMULADOS [ HR ], 24, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, ...), (ACUMULADOS [ HR ], 48, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, 1.59, 0.2, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, ...), (ACUMULADOS [ HR ], 72, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, 2.59, 2.4, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, ...), (ACUMULADOS [ HR ], 96, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, 0.2, -, -, -, -, -, -, -, -, 0.2, -, -, -, -, -, -, 7.8, -, -, 2.59, 16.18, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, -, 0.4, -, -, -, -, 1, -, -, -, -, ...), (ACUMULADOS [ HR ], Nível de Acumulado (mm/24h), Unnamed: 12_level_2, Unnamed: 12_level_3, Unnamed: 12_level_4, Unnamed: 12_level_5, Unnamed: 12_level_6, Unnamed: 12_level_7, Unnamed: 12_level_8, Unnamed: 12_level_9, Unnamed: 12_level_10, Unnamed: 12_level_11, Unnamed: 12_level_12, Unnamed: 12_level_13, Unnamed: 12_level_14, Unnamed: 12_level_15, Unnamed: 12_level_16, Unnamed: 12_level_17, Unnamed: 12_level_18, Unnamed: 12_level_19, Unnamed: 12_level_20, Unnamed: 12_level_21, Unnamed: 12_level_22, Unnamed: 12_level_23, Unnamed: 12_level_24, Unnamed: 12_level_25, Unnamed: 12_level_26, Unnamed: 12_level_27, Unnamed: 12_level_28, Unnamed: 12_level_29, Unnamed: 12_level_30, Unnamed: 12_level_31, Unnamed: 12_level_32, Unnamed: 12_level_33, Unnamed: 12_level_34, Unnamed: 12_level_35, Unnamed: 12_level_36, Unnamed: 12_level_37, Unnamed: 12_level_38, Unnamed: 12_level_39, Unnamed: 12_level_40, Unnamed: 12_level_41, Unnamed: 12_level_42, Unnamed: 12_level_43, Unnamed: 12_level_44, Unnamed: 12_level_45, Unnamed: 12_level_46, Unnamed: 12_level_47, Unnamed: 12_level_48, Unnamed: 12_level_49, Unnamed: 12_level_50, Unnamed: 12_level_51, Unnamed: 12_level_52, Unnamed: 12_level_53, Unnamed: 12_level_54, Unnamed: 12_level_55, Unnamed: 12_level_56, Unnamed: 12_level_57, Unnamed: 12_level_58, Unnamed: 12_level_59, Unnamed: 12_level_60, Unnamed: 12_level_61, Unnamed: 12_level_62, Unnamed: 12_level_63, Unnamed: 12_level_64, Unnamed: 12_level_65, Unnamed: 12_level_66, Unnamed: 12_level_67, Unnamed: 12_level_68, Unnamed: 12_level_69, Unnamed: 12_level_70, Unnamed: 12_level_71, Unnamed: 12_level_72, Unnamed: 12_level_73, Unnamed: 12_level_74, Unnamed: 12_level_75, Unnamed: 12_level_76, Unnamed: 12_level_77, Unnamed: 12_level_78, Unnamed: 12_level_79, Unnamed: 12_level_80, Unnamed: 12_level_81, Unnamed: 12_level_82, Unnamed: 12_level_83, Unnamed: 12_level_84, Unnamed: 12_level_85, Unnamed: 12_level_86, Unnamed: 12_level_87, Unnamed: 12_level_88, Unnamed: 12_level_89, Unnamed: 12_level_90, Unnamed: 12_level_91, Unnamed: 12_level_92, Unnamed: 12_level_93, Unnamed: 12_level_94, Unnamed: 12_level_95, Unnamed: 12_level_96, Unnamed: 12_level_97, Unnamed: 12_level_98, Unnamed: 12_level_99, ...), (ACUMULADOS [ HR ], Gráficos, Unnamed: 13_level_2, Unnamed: 13_level_3, Unnamed: 13_level_4, Unnamed: 13_level_5, Unnamed: 13_level_6, Unnamed: 13_level_7, Unnamed: 13_level_8, Unnamed: 13_level_9, Unnamed: 13_level_10, Unnamed: 13_level_11, Unnamed: 13_level_12, Unnamed: 13_level_13, Unnamed: 13_level_14, Unnamed: 13_level_15, Unnamed: 13_level_16, Unnamed: 13_level_17, Unnamed: 13_level_18, Unnamed: 13_level_19, Unnamed: 13_level_20, Unnamed: 13_level_21, Unnamed: 13_level_22, Unnamed: 13_level_23, Unnamed: 13_level_24, Unnamed: 13_level_25, Unnamed: 13_level_26, Unnamed: 13_level_27, Unnamed: 13_level_28, Unnamed: 13_level_29, Unnamed: 13_level_30, Unnamed: 13_level_31, Unnamed: 13_level_32, Unnamed: 13_level_33, Unnamed: 13_level_34, Unnamed: 13_level_35, Unnamed: 13_level_36, Unnamed: 13_level_37, Unnamed: 13_level_38, Unnamed: 13_level_39, Unnamed: 13_level_40, Unnamed: 13_level_41, Unnamed: 13_level_42, Unnamed: 13_level_43, Unnamed: 13_level_44, Unnamed: 13_level_45, Unnamed: 13_level_46, Unnamed: 13_level_47, Unnamed: 13_level_48, Unnamed: 13_level_49, Unnamed: 13_level_50, Unnamed: 13_level_51, Unnamed: 13_level_52, Unnamed: 13_level_53, Unnamed: 13_level_54, Unnamed: 13_level_55, Unnamed: 13_level_56, Unnamed: 13_level_57, Unnamed: 13_level_58, Unnamed: 13_level_59, Unnamed: 13_level_60, Unnamed: 13_level_61, Unnamed: 13_level_62, Unnamed: 13_level_63, Unnamed: 13_level_64, Unnamed: 13_level_65, Unnamed: 13_level_66, Unnamed: 13_level_67, Unnamed: 13_level_68, Unnamed: 13_level_69, Unnamed: 13_level_70, Unnamed: 13_level_71, Unnamed: 13_level_72, Unnamed: 13_level_73, Unnamed: 13_level_74, Unnamed: 13_level_75, Unnamed: 13_level_76, Unnamed: 13_level_77, Unnamed: 13_level_78, Unnamed: 13_level_79, Unnamed: 13_level_80, Unnamed: 13_level_81, Unnamed: 13_level_82, Unnamed: 13_level_83, Unnamed: 13_level_84, Unnamed: 13_level_85, Unnamed: 13_level_86, Unnamed: 13_level_87, Unnamed: 13_level_88, Unnamed: 13_level_89, Unnamed: 13_level_90, Unnamed: 13_level_91, Unnamed: 13_level_92, Unnamed: 13_level_93, Unnamed: 13_level_94, Unnamed: 13_level_95, Unnamed: 13_level_96, Unnamed: 13_level_97, Unnamed: 13_level_98, Unnamed: 13_level_99, ...), (Unnamed: 14_level_0, Tabelas, Unnamed: 14_level_2, Unnamed: 14_level_3, Unnamed: 14_level_4, Unnamed: 14_level_5, Unnamed: 14_level_6, Unnamed: 14_level_7, Unnamed: 14_level_8, Unnamed: 14_level_9, Unnamed: 14_level_10, Unnamed: 14_level_11, Unnamed: 14_level_12, Unnamed: 14_level_13, Unnamed: 14_level_14, Unnamed: 14_level_15, Unnamed: 14_level_16, Unnamed: 14_level_17, Unnamed: 14_level_18, Unnamed: 14_level_19, Unnamed: 14_level_20, Unnamed: 14_level_21, Unnamed: 14_level_22, Unnamed: 14_level_23, Unnamed: 14_level_24, Unnamed: 14_level_25, Unnamed: 14_level_26, Unnamed: 14_level_27, Unnamed: 14_level_28, Unnamed: 14_level_29, Unnamed: 14_level_30, Unnamed: 14_level_31, Unnamed: 14_level_32, Unnamed: 14_level_33, Unnamed: 14_level_34, Unnamed: 14_level_35, Unnamed: 14_level_36, Unnamed: 14_level_37, Unnamed: 14_level_38, Unnamed: 14_level_39, Unnamed: 14_level_40, Unnamed: 14_level_41, Unnamed: 14_level_42, Unnamed: 14_level_43, Unnamed: 14_level_44, Unnamed: 14_level_45, Unnamed: 14_level_46, Unnamed: 14_level_47, Unnamed: 14_level_48, Unnamed: 14_level_49, Unnamed: 14_level_50, Unnamed: 14_level_51, Unnamed: 14_level_52, Unnamed: 14_level_53, Unnamed: 14_level_54, Unnamed: 14_level_55, Unnamed: 14_level_56, Unnamed: 14_level_57, Unnamed: 14_level_58, Unnamed: 14_level_59, Unnamed: 14_level_60, Unnamed: 14_level_61, Unnamed: 14_level_62, Unnamed: 14_level_63, Unnamed: 14_level_64, Unnamed: 14_level_65, Unnamed: 14_level_66, Unnamed: 14_level_67, Unnamed: 14_level_68, Unnamed: 14_level_69, Unnamed: 14_level_70, Unnamed: 14_level_71, Unnamed: 14_level_72, Unnamed: 14_level_73, Unnamed: 14_level_74, Unnamed: 14_level_75, Unnamed: 14_level_76, Unnamed: 14_level_77, Unnamed: 14_level_78, Unnamed: 14_level_79, Unnamed: 14_level_80, Unnamed: 14_level_81, Unnamed: 14_level_82, Unnamed: 14_level_83, Unnamed: 14_level_84, Unnamed: 14_level_85, Unnamed: 14_level_86, Unnamed: 14_level_87, Unnamed: 14_level_88, Unnamed: 14_level_89, Unnamed: 14_level_90, Unnamed: 14_level_91, Unnamed: 14_level_92, Unnamed: 14_level_93, Unnamed: 14_level_94, Unnamed: 14_level_95, Unnamed: 14_level_96, Unnamed: 14_level_97, Unnamed: 14_level_98, Unnamed: 14_level_99, ...)]
Index: []

In [6]:
#python -m pip install html5lib beautifulsoup4
#!pip install html5lib beautifulsoup4

In [7]:
import html5lib
import bs4

print(html5lib.__version__)
print(bs4.__version__)

1.1
4.15.0

In [8]:
# (Maq2) fabiene@:~/Documentos/Fabiene/PYTHON_CURSO_LIRA_C2/instalacao_chromedriver_parabaixarnoPython/chromedriver_062026/chromedriver-linux64/chromedriver-linux64$ conda install -c conda-forge html5lib beautifulsoup4
#y

In [9]:
import html5lib
import bs4

print("html5lib:", html5lib.__version__)
print("html5lib path:", html5lib.__file__)

print("BeautifulSoup:", bs4.__version__)
print("BeautifulSoup path:", bs4.__file__)

print("\nTestando parser...")
soup = bs4.BeautifulSoup("<html><body><p>Teste</p></body></html>", "html5lib")

print(soup.get_text())

html5lib: 1.1
html5lib path: /home/fabiene/anaconda3/envs/Maq2/lib/python3.12/site-packages/html5lib/__init__.py
BeautifulSoup: 4.15.0
BeautifulSoup path: /home/fabiene/anaconda3/envs/Maq2/lib/python3.12/site-packages/bs4/__init__.py

Testando parser...
Teste

In [10]:
# Lê a tabela HTML especificando o cabeçalho na primeira linha
# DEU CERTO
#df_correto = pd.read_html(html_content, flavor='html5lib', header=0)[0]

from io import StringIO

df_correto = pd.read_html(
    StringIO(html_content),
    flavor='html5lib',
    header=0
)[0]

# Exibe o DataFrame
display(df_correto)

,Carregando...,Carregando....1,Unnamed: 2,ACUMULADOS [ HR ],ACUMULADOS [ HR ].1,ACUMULADOS [ HR ].2,ACUMULADOS [ HR ].3,ACUMULADOS [ HR ].4,ACUMULADOS [ HR ].5,ACUMULADOS [ HR ].6,ACUMULADOS [ HR ].7,ACUMULADOS [ HR ].8,ACUMULADOS [ HR ].9,ACUMULADOS [ HR ].10,Unnamed: 14
0,UF,Cidade,Nome,Data (Horário UTC),Último,1,6,12,24,48,72,96,Nível de Acumulado (mm/24h),Gráficos,Tabelas
1,SP,SÃO BERNARDO DO CAMPO,Brazilia Tondi de Lima,01/11/25 06:10,0,-,-,-,-,-,-,-,NaN,NaN,NaN
2,SP,CACHOEIRA PAULISTA,LIM/INPE (TESTES),15/01/25 14:10,0,-,-,-,-,-,-,-,NaN,NaN,NaN
3,SP,DIADEMA,Elias Costa,30/04/23 01:10,0,-,-,-,-,-,-,-,NaN,NaN,NaN
4,SP,SANTOS,Morro de São Bento,04/09/23 07:50,0,-,-,-,-,-,-,-,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
719,SP,ATIBAIA,Jd. do Alvinópolis,14/09/26 13:00,0.2,-,-,0.2,0.2,0.2,0.4,0.8,NaN,NaN,NaN
720,SP,JUNDIAÍ,Rio Jundiai,14/09/26 14:10,0,-,-,0.2,0.2,0.2,0.4,0.8,NaN,NaN,NaN
721,SP,BOM SUCESSO DE ITARARÉ,Centro,14/09/26 20:10,0,-,-,-,0.2,1,6.4,7.4,NaN,NaN,NaN
722,SP,FRANCO DA ROCHA,Rio Jundiai,14/09/26 20:10,0,-,0.2,0.2,0.2,0.2,0.2,0.2,NaN,NaN,NaN
723,SP,JANDIRA,Parque das Iglesias,14/09/26 19:50,0,-,-,-,0.2,0.6,1.2,6.8,NaN,NaN,NaN

In [11]:
list(df_correto.columns)

['Carregando...',
 'Carregando....1',
 'Unnamed: 2',
 'ACUMULADOS [ HR ]',
 'ACUMULADOS [ HR ].1',
 'ACUMULADOS [ HR ].2',
 'ACUMULADOS [ HR ].3',
 'ACUMULADOS [ HR ].4',
 'ACUMULADOS [ HR ].5',
 'ACUMULADOS [ HR ].6',
 'ACUMULADOS [ HR ].7',
 'ACUMULADOS [ HR ].8',
 'ACUMULADOS [ HR ].9',
 'ACUMULADOS [ HR ].10',
 'Unnamed: 14']

In [12]:
nomes_colunas = df_correto.iloc[0] # Obtém os nomes das colunas da primeira linha
df_correto = df_correto[1:]  # Remove a primeira linha dos dados
df_correto.columns = nomes_colunas  # Define os nomes das colunas

df_correto_oficial = df_correto.replace('-', 0.0)
df_correto_oficial

/tmp/ipykernel_18222/851472075.py:5: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_correto_oficial = df_correto.replace('-', 0.0)

,UF,Cidade,Nome,Data (Horário UTC),Último,1,6,12,24,48,72,96,Nível de Acumulado (mm/24h),Gráficos,Tabelas
1,SP,SÃO BERNARDO DO CAMPO,Brazilia Tondi de Lima,01/11/25 06:10,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
2,SP,CACHOEIRA PAULISTA,LIM/INPE (TESTES),15/01/25 14:10,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
3,SP,DIADEMA,Elias Costa,30/04/23 01:10,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
4,SP,SANTOS,Morro de São Bento,04/09/23 07:50,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
5,SP,PIRACAIA,Garagem da PM,07/02/26 14:00,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
719,SP,ATIBAIA,Jd. do Alvinópolis,14/09/26 13:00,0.2,0.0,0.0,0.2,0.2,0.2,0.4,0.8,NaN,NaN,NaN
720,SP,JUNDIAÍ,Rio Jundiai,14/09/26 14:10,0,0.0,0.0,0.2,0.2,0.2,0.4,0.8,NaN,NaN,NaN
721,SP,BOM SUCESSO DE ITARARÉ,Centro,14/09/26 20:10,0,0.0,0.0,0.0,0.2,1,6.4,7.4,NaN,NaN,NaN
722,SP,FRANCO DA ROCHA,Rio Jundiai,14/09/26 20:10,0,0.0,0.2,0.2,0.2,0.2,0.2,0.2,NaN,NaN,NaN
723,SP,JANDIRA,Parque das Iglesias,14/09/26 19:50,0,0.0,0.0,0.0,0.2,0.6,1.2,6.8,NaN,NaN,NaN

In [13]:
list(df_correto_oficial.columns)

['UF',
 'Cidade',
 'Nome',
 'Data (Horário UTC)',
 'Último',
 '1',
 '6',
 '12',
 '24',
 '48',
 '72',
 '96',
 'Nível de Acumulado (mm/24h)',
 'Gráficos',
 'Tabelas']

In [14]:
df_correto_oficial['Último']= df_correto_oficial['Último'].astype(float)
df_correto_oficial['1']= df_correto_oficial['1'].astype(float)
df_correto_oficial['6']= df_correto_oficial['6'].astype(float)
df_correto_oficial['12']= df_correto_oficial['12'].astype(float)

df_correto_oficial['24']= df_correto_oficial['24'].astype(float)
df_correto_oficial['96']= df_correto_oficial['96'].astype(float)
                                                          
df_correto_oficial['48']= df_correto_oficial['48'].astype(float)
df_correto_oficial['72']= df_correto_oficial['72'].astype(float)

df_correto_oficial=df_correto_oficial[['UF', 'Cidade', 'Nome', 'Data (Horário UTC)', 'Último', '1', '6', '12', '24', '48', '72', '96',]]
df_correto_oficial

,UF,Cidade,Nome,Data (Horário UTC),Último,1,6,12,24,48,72,96
1,SP,SÃO BERNARDO DO CAMPO,Brazilia Tondi de Lima,01/11/25 06:10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,SP,CACHOEIRA PAULISTA,LIM/INPE (TESTES),15/01/25 14:10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,SP,DIADEMA,Elias Costa,30/04/23 01:10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,SP,SANTOS,Morro de São Bento,04/09/23 07:50,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,SP,PIRACAIA,Garagem da PM,07/02/26 14:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
719,SP,ATIBAIA,Jd. do Alvinópolis,14/09/26 13:00,0.2,0.0,0.0,0.2,0.2,0.2,0.4,0.8
720,SP,JUNDIAÍ,Rio Jundiai,14/09/26 14:10,0.0,0.0,0.0,0.2,0.2,0.2,0.4,0.8
721,SP,BOM SUCESSO DE ITARARÉ,Centro,14/09/26 20:10,0.0,0.0,0.0,0.0,0.2,1.0,6.4,7.4
722,SP,FRANCO DA ROCHA,Rio Jundiai,14/09/26 20:10,0.0,0.0,0.2,0.2,0.2,0.2,0.2,0.2
723,SP,JANDIRA,Parque das Iglesias,14/09/26 19:50,0.0,0.0,0.0,0.0,0.2,0.6,1.2,6.8

In [15]:
print('digite os acumulados em horários que eu desejo saber, como:')
print( " Último, 1, 6, 12, 24, 48, 72, 96")
tabela_pesquisa= ['Último', '1', '6', '12', '24', '48', '72', '96']

Entrou= False
while(Entrou== False):
    coluna_desejo = input('digitar o acumulado que desejo saber')
    coluna_desejo_i = f'{coluna_desejo}'
    if coluna_desejo_i in tabela_pesquisa:
        sorted_data = df_correto_oficial.sort_values(by=f'{coluna_desejo_i}', ascending=False)
        display(sorted_data.head(40))
        Pesquisa = input('Desejo mais alguma pesquisa? Sim (S) ou Não (N):')
        if Pesquisa == 'S':
            Entrou= False
        elif Pesquisa == 'N':
            Entrou= True    
    else:
        print('digite o valor certo')

digite os acumulados em horários que eu desejo saber, como:
 Último, 1, 6, 12, 24, 48, 72, 96

digitar o acumulado que desejo saber 96

,UF,Cidade,Nome,Data (Horário UTC),Último,1,6,12,24,48,72,96
293,SP,GUARUJÁ,Enseada,14/09/26 20:30,0.59,4.32,11.01,37.52,72.95,118.58,169.50,178.59
615,SP,ITAÓCA,Centro,14/09/26 20:20,0.00,0.80,6.40,6.40,11.60,111.80,160.80,178.40
297,SP,BERTIOGA,Jardim Lido,14/09/26 20:30,0.20,2.75,9.24,32.44,64.72,89.81,157.13,170.35
295,SP,GUARUJÁ,Pereque2,14/09/26 20:30,0.39,3.14,9.04,36.74,69.81,104.51,160.16,169.26
292,SP,PRAIA GRANDE,Xixová Geotec,14/09/26 19:10,0.20,0.00,12.60,27.80,73.40,105.40,162.20,168.80
294,SP,GUARUJÁ,Morrinhos,14/09/26 20:50,0.20,4.32,8.10,36.18,71.60,109.51,159.08,167.00
317,SP,POÁ,Vila Julia,14/09/26 20:20,0.20,1.60,19.40,20.80,39.20,44.20,129.00,164.80
300,SP,SANTOS,Saboó,14/09/26 20:30,0.00,2.95,10.25,24.81,60.99,92.36,152.94,161.04
296,SP,GUARUJÁ,Vila Santo Antonio,14/09/26 20:20,0.39,2.75,9.44,32.03,66.83,97.80,150.49,158.61
338,SP,DIADEMA,Jardim Inamar,14/09/26 20:40,0.20,3.35,14.93,15.73,33.71,40.28,130.73,157.10
379,SP,SANTANA DE PARNAÍBA,Jardim Nina (Fazendinha),14/09/26 20:20,0.80,2.80,15.80,16.40,30.20,31.60,126.00,154.00
322,SP,MOGI DAS CRUZES,Jd Santos Dummond,14/09/26 20:30,0.00,1.60,18.20,19.40,37.80,42.40,119.00,153.80
298,SP,GUARUJÁ,Jardim das Palmas,14/09/26 20:40,0.59,4.13,11.40,31.23,63.49,95.03,145.16,153.64
308,SP,CUBATÃO,Parque Fernando Jorge,14/09/26 20:20,0.20,2.75,10.45,17.98,54.93,73.19,139.72,151.15
301,SP,CUBATÃO,Cota-200,14/09/26 20:20,0.39,3.53,9.45,14.61,59.80,79.03,141.02,150.32
305,SP,SANTOS,Vila Mathias,14/09/26 20:40,0.39,3.54,9.07,23.83,57.07,86.51,140.59,149.68
426,SP,SUMARÉ,Rio Quilombo,14/09/26 20:20,0.40,2.40,13.80,15.00,26.80,27.00,79.60,149.60
381,SP,SANTO ANDRÉ,Vila Príncipe de Gales,14/09/26 20:20,0.20,2.17,11.22,11.82,30.00,34.57,127.14,148.79
346,SP,MAUÁ,Vila Carlina,14/09/26 20:20,0.39,2.55,11.59,12.58,32.53,39.09,125.42,148.63
329,SP,ATIBAIA,Jardim Maracana,14/09/26 20:30,0.20,2.20,18.20,19.00,35.00,37.40,101.20,147.80
316,SP,BRAGANÇA PAULISTA,Água Comprida,14/09/26 20:30,0.40,2.00,18.20,19.40,39.60,40.20,99.00,147.80
394,SP,SÃO SEBASTIÃO,Juquehy2,14/09/26 19:40,0.39,0.59,3.96,6.15,28.46,66.14,126.27,147.40
461,SP,SUMARÉ,Vila Miranda,14/09/26 20:30,0.20,2.20,12.80,14.00,25.20,25.40,74.80,147.00
401,SP,COTIA,Morro Grande,14/09/26 20:20,0.20,2.60,11.20,11.20,28.20,31.40,123.40,146.80
549,SP,ITARARÉ,G2-352320602A,14/09/26 20:00,0.60,1.60,12.40,13.20,18.80,58.60,114.80,146.80
336,SP,SÃO BERNARDO DO CAMPO,Jardim Silvina,14/09/26 21:00,0.20,3.93,13.17,14.57,34.29,40.47,123.81,146.25
311,SP,SANTO ANDRÉ,Paranapiacaba,14/09/26 20:30,0.20,2.17,12.99,23.49,48.70,74.87,128.79,145.52
309,SP,GUARUJÁ,Corpo de Bombeiros,14/09/26 20:40,0.20,3.74,7.69,23.83,54.36,83.99,136.67,145.18
555,SP,ITARARÉ,G2-352320601A,14/09/26 20:00,0.20,1.60,11.80,12.40,18.00,58.40,113.40,144.80
304,SP,SÃO VICENTE,Parque Prainha,14/09/26 20:20,0.20,2.36,10.65,21.69,57.09,86.71,136.65,143.57
392,SP,BRAGANÇA PAULISTA,Jardim Cedro,14/09/26 20:20,0.40,1.40,13.00,14.00,28.60,29.00,94.20,142.80
595,SP,APIAÍ,Sitio Dois Irmãos,14/09/26 20:10,0.20,0.60,7.20,7.40,13.80,66.00,129.20,142.80
351,SP,SÃO PAULO,C.E.U Parelheiros,14/09/26 20:20,0.20,2.75,8.67,9.07,32.32,38.27,127.22,142.62
587,SP,APIAÍ,Centro,14/09/26 20:10,0.40,0.80,7.60,7.80,14.60,63.20,128.00,142.40
360,SP,SANTO ANDRÉ,Borda do Campo,14/09/26 20:30,0.20,2.36,10.62,12.02,31.76,39.53,118.50,141.13
331,SP,FERRAZ DE VASCONCELOS,Jardim Renata,14/09/26 20:20,0.60,1.60,16.00,17.40,34.80,37.60,111.60,140.80
319,SP,SANTO ANDRÉ,Parque Andreense,14/09/26 20:30,0.20,2.76,13.18,15.99,38.28,49.84,121.94,140.66
342,SP,MOGI DAS CRUZES,Jundiapeba,14/09/26 20:20,0.20,1.20,16.20,17.20,32.80,36.80,109.40,138.80
369,SP,SÃO SEBASTIÃO,Camburi,14/09/26 20:30,0.20,3.35,12.97,15.55,31.01,59.84,116.68,138.34
372,SP,VALINHOS,Vila São Sebastião,14/09/26 20:20,0.20,1.80,18.00,18.80,30.80,31.60,102.40,138.20

Desejo mais alguma pesquisa? Sim (S) ou Não (N): S
digitar o acumulado que desejo saber 24

,UF,Cidade,Nome,Data (Horário UTC),Último,1,6,12,24,48,72,96
292,SP,PRAIA GRANDE,Xixová Geotec,14/09/26 19:10,0.20,0.00,12.60,27.80,73.40,105.40,162.20,168.80
293,SP,GUARUJÁ,Enseada,14/09/26 20:30,0.59,4.32,11.01,37.52,72.95,118.58,169.50,178.59
294,SP,GUARUJÁ,Morrinhos,14/09/26 20:50,0.20,4.32,8.10,36.18,71.60,109.51,159.08,167.00
295,SP,GUARUJÁ,Pereque2,14/09/26 20:30,0.39,3.14,9.04,36.74,69.81,104.51,160.16,169.26
296,SP,GUARUJÁ,Vila Santo Antonio,14/09/26 20:20,0.39,2.75,9.44,32.03,66.83,97.80,150.49,158.61
297,SP,BERTIOGA,Jardim Lido,14/09/26 20:30,0.20,2.75,9.24,32.44,64.72,89.81,157.13,170.35
298,SP,GUARUJÁ,Jardim das Palmas,14/09/26 20:40,0.59,4.13,11.40,31.23,63.49,95.03,145.16,153.64
299,SP,CARAGUATATUBA,Indaiá,14/09/26 20:50,0.59,2.96,12.41,26.75,62.48,76.25,77.85,78.85
300,SP,SANTOS,Saboó,14/09/26 20:30,0.00,2.95,10.25,24.81,60.99,92.36,152.94,161.04
301,SP,CUBATÃO,Cota-200,14/09/26 20:20,0.39,3.53,9.45,14.61,59.80,79.03,141.02,150.32
302,SP,MONGAGUÁ,Jardim Praia Grande,14/09/26 20:20,0.39,2.55,16.31,20.49,59.59,79.14,127.90,134.62
303,SP,PRAIA GRANDE,Alice,14/09/26 20:20,0.20,1.20,11.20,18.20,58.40,73.40,100.60,105.20
304,SP,SÃO VICENTE,Parque Prainha,14/09/26 20:20,0.20,2.36,10.65,21.69,57.09,86.71,136.65,143.57
305,SP,SANTOS,Vila Mathias,14/09/26 20:40,0.39,3.54,9.07,23.83,57.07,86.51,140.59,149.68
306,SP,SÃO VICENTE,Paranapuã,14/09/26 20:20,0.60,2.60,10.80,21.20,56.20,84.40,137.20,137.20
307,SP,GUARUJÁ,Jardim Albamar,14/09/26 20:20,0.40,3.00,8.20,29.60,56.00,88.00,131.00,137.80
308,SP,CUBATÃO,Parque Fernando Jorge,14/09/26 20:20,0.20,2.75,10.45,17.98,54.93,73.19,139.72,151.15
309,SP,GUARUJÁ,Corpo de Bombeiros,14/09/26 20:40,0.20,3.74,7.69,23.83,54.36,83.99,136.67,145.18
310,SP,CAFELÂNDIA,Av. Jacob Zucchi,14/09/26 20:30,0.00,5.20,30.40,47.20,53.40,54.00,61.80,66.20
311,SP,SANTO ANDRÉ,Paranapiacaba,14/09/26 20:30,0.20,2.17,12.99,23.49,48.70,74.87,128.79,145.52
312,SP,SANTOS,Caruara,14/09/26 12:50,0.39,0.00,0.00,3.34,46.77,69.82,90.46,94.81
313,SP,UBATUBA,Parque dos Ministérios,14/09/26 20:20,0.20,1.59,5.36,7.75,45.70,58.57,78.47,96.20
314,SP,PARAPUÃ,Rua Sergipe,14/09/26 20:20,0.20,2.00,14.20,24.80,45.00,47.60,62.20,69.00
315,SP,CARAGUATATUBA,Martim de Sá,14/09/26 20:20,0.00,0.00,2.40,17.74,43.16,71.83,82.43,116.37
316,SP,BRAGANÇA PAULISTA,Água Comprida,14/09/26 20:30,0.40,2.00,18.20,19.40,39.60,40.20,99.00,147.80
317,SP,POÁ,Vila Julia,14/09/26 20:20,0.20,1.60,19.40,20.80,39.20,44.20,129.00,164.80
318,SP,JUNDIAÍ,Roseira,14/09/26 20:50,0.40,3.00,22.40,24.20,38.60,41.60,99.20,132.80
319,SP,SANTO ANDRÉ,Parque Andreense,14/09/26 20:30,0.20,2.76,13.18,15.99,38.28,49.84,121.94,140.66
320,SP,GUARULHOS,Cidade Aracília,14/09/26 21:00,0.60,3.80,19.40,21.80,38.00,43.40,104.40,135.00
321,SP,MARÍLIA,Realengo,14/09/26 20:20,0.20,0.80,14.80,22.20,37.80,40.00,53.00,59.40
322,SP,MOGI DAS CRUZES,Jd Santos Dummond,14/09/26 20:30,0.00,1.60,18.20,19.40,37.80,42.40,119.00,153.80
323,SP,UBATUBA,Centro 2,14/09/26 20:40,0.20,1.59,4.56,7.35,37.27,47.34,63.08,79.62
324,SP,PIRACAIA,Caras,14/09/26 20:10,0.20,1.02,17.79,18.61,37.15,37.55,88.88,131.62
325,SP,UBATUBA,Centro,14/09/26 20:40,0.00,1.60,4.38,7.38,36.52,46.27,61.44,78.82
326,SP,CARAGUATATUBA,Getuba,14/09/26 21:00,0.20,2.18,5.54,6.14,36.28,43.27,108.06,127.33
327,SP,GUARULHOS,Vila Nova Bonsucesso,14/09/26 21:20,0.20,4.40,18.40,20.60,36.00,40.00,92.40,124.80
328,SP,CAMPO LIMPO PAULISTA,Jardim São José,14/09/26 20:20,0.60,2.60,19.60,21.60,35.80,39.00,87.20,122.40
329,SP,ATIBAIA,Jardim Maracana,14/09/26 20:30,0.20,2.20,18.20,19.00,35.00,37.40,101.20,147.80
330,SP,UBATUBA,Praia Dura,14/09/26 20:50,0.00,0.40,1.60,8.53,34.91,40.91,65.18,94.18
331,SP,FERRAZ DE VASCONCELOS,Jardim Renata,14/09/26 20:20,0.60,1.60,16.00,17.40,34.80,37.60,111.60,140.80

Desejo mais alguma pesquisa? Sim (S) ou Não (N): S
digitar o acumulado que desejo saber 72

,UF,Cidade,Nome,Data (Horário UTC),Último,1,6,12,24,48,72,96
293,SP,GUARUJÁ,Enseada,14/09/26 20:30,0.59,4.32,11.01,37.52,72.95,118.58,169.50,178.59
292,SP,PRAIA GRANDE,Xixová Geotec,14/09/26 19:10,0.20,0.00,12.60,27.80,73.40,105.40,162.20,168.80
615,SP,ITAÓCA,Centro,14/09/26 20:20,0.00,0.80,6.40,6.40,11.60,111.80,160.80,178.40
295,SP,GUARUJÁ,Pereque2,14/09/26 20:30,0.39,3.14,9.04,36.74,69.81,104.51,160.16,169.26
294,SP,GUARUJÁ,Morrinhos,14/09/26 20:50,0.20,4.32,8.10,36.18,71.60,109.51,159.08,167.00
297,SP,BERTIOGA,Jardim Lido,14/09/26 20:30,0.20,2.75,9.24,32.44,64.72,89.81,157.13,170.35
300,SP,SANTOS,Saboó,14/09/26 20:30,0.00,2.95,10.25,24.81,60.99,92.36,152.94,161.04
296,SP,GUARUJÁ,Vila Santo Antonio,14/09/26 20:20,0.39,2.75,9.44,32.03,66.83,97.80,150.49,158.61
298,SP,GUARUJÁ,Jardim das Palmas,14/09/26 20:40,0.59,4.13,11.40,31.23,63.49,95.03,145.16,153.64
301,SP,CUBATÃO,Cota-200,14/09/26 20:20,0.39,3.53,9.45,14.61,59.80,79.03,141.02,150.32
305,SP,SANTOS,Vila Mathias,14/09/26 20:40,0.39,3.54,9.07,23.83,57.07,86.51,140.59,149.68
308,SP,CUBATÃO,Parque Fernando Jorge,14/09/26 20:20,0.20,2.75,10.45,17.98,54.93,73.19,139.72,151.15
306,SP,SÃO VICENTE,Paranapuã,14/09/26 20:20,0.60,2.60,10.80,21.20,56.20,84.40,137.20,137.20
309,SP,GUARUJÁ,Corpo de Bombeiros,14/09/26 20:40,0.20,3.74,7.69,23.83,54.36,83.99,136.67,145.18
304,SP,SÃO VICENTE,Parque Prainha,14/09/26 20:20,0.20,2.36,10.65,21.69,57.09,86.71,136.65,143.57
307,SP,GUARUJÁ,Jardim Albamar,14/09/26 20:20,0.40,3.00,8.20,29.60,56.00,88.00,131.00,137.80
338,SP,DIADEMA,Jardim Inamar,14/09/26 20:40,0.20,3.35,14.93,15.73,33.71,40.28,130.73,157.10
595,SP,APIAÍ,Sitio Dois Irmãos,14/09/26 20:10,0.20,0.60,7.20,7.40,13.80,66.00,129.20,142.80
317,SP,POÁ,Vila Julia,14/09/26 20:20,0.20,1.60,19.40,20.80,39.20,44.20,129.00,164.80
311,SP,SANTO ANDRÉ,Paranapiacaba,14/09/26 20:30,0.20,2.17,12.99,23.49,48.70,74.87,128.79,145.52
587,SP,APIAÍ,Centro,14/09/26 20:10,0.40,0.80,7.60,7.80,14.60,63.20,128.00,142.40
302,SP,MONGAGUÁ,Jardim Praia Grande,14/09/26 20:20,0.39,2.55,16.31,20.49,59.59,79.14,127.90,134.62
351,SP,SÃO PAULO,C.E.U Parelheiros,14/09/26 20:20,0.20,2.75,8.67,9.07,32.32,38.27,127.22,142.62
381,SP,SANTO ANDRÉ,Vila Príncipe de Gales,14/09/26 20:20,0.20,2.17,11.22,11.82,30.00,34.57,127.14,148.79
394,SP,SÃO SEBASTIÃO,Juquehy2,14/09/26 19:40,0.39,0.59,3.96,6.15,28.46,66.14,126.27,147.40
379,SP,SANTANA DE PARNAÍBA,Jardim Nina (Fazendinha),14/09/26 20:20,0.80,2.80,15.80,16.40,30.20,31.60,126.00,154.00
346,SP,MAUÁ,Vila Carlina,14/09/26 20:20,0.39,2.55,11.59,12.58,32.53,39.09,125.42,148.63
336,SP,SÃO BERNARDO DO CAMPO,Jardim Silvina,14/09/26 21:00,0.20,3.93,13.17,14.57,34.29,40.47,123.81,146.25
401,SP,COTIA,Morro Grande,14/09/26 20:20,0.20,2.60,11.20,11.20,28.20,31.40,123.40,146.80
319,SP,SANTO ANDRÉ,Parque Andreense,14/09/26 20:30,0.20,2.76,13.18,15.99,38.28,49.84,121.94,140.66
322,SP,MOGI DAS CRUZES,Jd Santos Dummond,14/09/26 20:30,0.00,1.60,18.20,19.40,37.80,42.40,119.00,153.80
360,SP,SANTO ANDRÉ,Borda do Campo,14/09/26 20:30,0.20,2.36,10.62,12.02,31.76,39.53,118.50,141.13
383,SP,EMBU-GUAÇU,Parque São Lucas,14/09/26 20:30,0.20,3.40,9.40,9.60,29.80,35.00,118.40,134.40
369,SP,SÃO SEBASTIÃO,Camburi,14/09/26 20:30,0.20,3.35,12.97,15.55,31.01,59.84,116.68,138.34
549,SP,ITARARÉ,G2-352320602A,14/09/26 20:00,0.60,1.60,12.40,13.20,18.80,58.60,114.80,146.80
600,SP,BARRA DO CHAPÉU,Centro,14/09/26 20:30,0.00,0.80,7.20,7.40,13.20,71.00,114.20,131.40
555,SP,ITARARÉ,G2-352320601A,14/09/26 20:00,0.20,1.60,11.80,12.40,18.00,58.40,113.40,144.80
425,SP,SÃO SEBASTIÃO,Juquehy,14/09/26 19:50,0.39,1.77,10.61,12.60,26.86,60.78,112.71,133.38
331,SP,FERRAZ DE VASCONCELOS,Jardim Renata,14/09/26 20:20,0.60,1.60,16.00,17.40,34.80,37.60,111.60,140.80
371,SP,RIBEIRÃO PIRES,Represa,14/09/26 20:20,0.39,1.97,10.02,11.42,30.80,38.18,110.85,130.76

Desejo mais alguma pesquisa? Sim (S) ou Não (N): N

In [16]:
browser.quit()