# 21.4) ECLAT

In [1]:
import pandas as pd

dados = {
    1: {
        "leite": "não",
        "café": "sim",
        "cerveja": "não",
        "pão": "sim",
        "manteiga": "sim",
        "arroz": "não",
        "feijão": "não"
    },
    2: {
        "leite": "sim",
        "café": "não",
        "cerveja": "sim",
        "pão": "sim",
        "manteiga": "sim",
        "arroz": "não",
        "feijão": "não"
    },
    3: {
        "leite": "não",
        "café": "sim",
        "cerveja": "não",
        "pão": "sim",
        "manteiga": "sim",
        "arroz": "não",
        "feijão": "não"
    },
    4: {
        "leite": "sim",
        "café": "sim",
        "cerveja": "não",
        "pão": "sim",
        "manteiga": "sim",
        "arroz": "não",
        "feijão": "não"
    }  ,  
    5: {
        "leite": "não",
        "café": "não",
        "cerveja": "sim",
        "pão": "não",
        "manteiga": "não",
        "arroz": "não",
        "feijão": "não"
    }  ,          
    6: {
        "leite": "não",
        "café": "não",
        "cerveja": "não",
        "pão": "não",
        "manteiga": "sim",
        "arroz": "não",
        "feijão": "não"
    }  ,     
    7: {
        "leite": "não",
        "café": "não",
        "cerveja": "não",
        "pão": "sim",
        "manteiga": "não",
        "arroz": "não",
        "feijão": "não"
    }  ,     
    8: {
        "leite": "não",
        "café": "não",
        "cerveja": "não",
        "pão": "não",
        "manteiga": "não",
        "arroz": "não",
        "feijão": "sim"
    }  ,           
    9: {
        "leite": "não",
        "café": "não",
        "cerveja": "não",
        "pão": "não",
        "manteiga": "não",
        "arroz": "sim",
        "feijão": "sim"
    }  ,  
    10: {
        "leite": "não",
        "café": "não",
        "cerveja": "não",
        "pão": "não",
        "manteiga": "não",
        "arroz": "sim",
        "feijão": "não"
    }  ,             
           
}

In [2]:
df_dados = pd.DataFrame(dados)
df_dados

           1    2    3    4    5    6    7    8    9    10
leite     não  sim  não  sim  não  não  não  não  não  não
café      sim  não  sim  sim  não  não  não  não  não  não
cerveja   não  sim  não  não  sim  não  não  não  não  não
pão       sim  sim  sim  sim  não  não  sim  não  não  não
manteiga  sim  sim  sim  sim  não  sim  não  não  não  não
arroz     não  não  não  não  não  não  não  não  sim  sim
feijão    não  não  não  não  não  não  não  sim  sim  não

In [3]:
df_transposto = df_dados.T
print("\n Tabela Transposto:")
display(df_transposto)

 Tabela Transposto:

   leite café cerveja  pão manteiga arroz feijão
1    não  sim     não  sim      sim   não    não
2    sim  não     sim  sim      sim   não    não
3    não  sim     não  sim      sim   não    não
4    sim  sim     não  sim      sim   não    não
5    não  não     sim  não      não   não    não
6    não  não     não  não      sim   não    não
7    não  não     não  sim      não   não    não
8    não  não     não  não      não   não    sim
9    não  não     não  não      não   sim    sim
10   não  não     não  não      não   sim    não

## Suporte = Número de registros com X e Y / Número total de registros

In [4]:
colunas = list(df_transposto.columns)

for col in colunas:
    suporte = len(df_transposto.loc[df_transposto[col]=='sim'])/len(df_transposto)
    Aparecer = len(df_transposto.loc[df_transposto[col]=='sim'])
    print(f'{col} aparece nas compras {Aparecer} vezes')
    print(f'suporte para o {col}: {suporte*100} %')
    print()

leite aparece nas compras 2 vezes
suporte para o leite: 20.0 %

café aparece nas compras 3 vezes
suporte para o café: 30.0 %

cerveja aparece nas compras 2 vezes
suporte para o cerveja: 20.0 %

pão aparece nas compras 5 vezes
suporte para o pão: 50.0 %

manteiga aparece nas compras 5 vezes
suporte para o manteiga: 50.0 %

arroz aparece nas compras 2 vezes
suporte para o arroz: 20.0 %

feijão aparece nas compras 2 vezes
suporte para o feijão: 20.0 %

In [5]:
# o quanto são vendidos em conjuntos os produtos:
from itertools import combinations

for col1, col2 in combinations(colunas, 2):
    #print(f'{col1} e {col2}')
    suporte = len(df_transposto.loc[ (df_transposto[col1]=='sim') & (df_transposto[col2]=='sim') ] )/len(df_transposto)
    Aparecer = len(df_transposto.loc[(df_transposto[col1]=='sim') & (df_transposto[col2]=='sim') ])
    if 0.0 < Aparecer:
        print(f'{col1} e {col2} aparecem nas compras {Aparecer} vezes')
        print(f'suporte para o {col1} e {col2}: {suporte*100} %')
        print()

leite e café aparecem nas compras 1 vezes
suporte para o leite e café: 10.0 %

leite e cerveja aparecem nas compras 1 vezes
suporte para o leite e cerveja: 10.0 %

leite e pão aparecem nas compras 2 vezes
suporte para o leite e pão: 20.0 %

leite e manteiga aparecem nas compras 2 vezes
suporte para o leite e manteiga: 20.0 %

café e pão aparecem nas compras 3 vezes
suporte para o café e pão: 30.0 %

café e manteiga aparecem nas compras 3 vezes
suporte para o café e manteiga: 30.0 %

cerveja e pão aparecem nas compras 1 vezes
suporte para o cerveja e pão: 10.0 %

cerveja e manteiga aparecem nas compras 1 vezes
suporte para o cerveja e manteiga: 10.0 %

pão e manteiga aparecem nas compras 4 vezes
suporte para o pão e manteiga: 40.0 %

arroz e feijão aparecem nas compras 1 vezes
suporte para o arroz e feijão: 10.0 %

# Suporte limitando os de interesse maior ou igual a 30%

# Calcular o suporte de conjuntos com 2 itens

In [6]:
# o quanto são vendidos em conjuntos os produtos de forma correta pelo suporte:
from itertools import combinations

for col1, col2 in combinations(colunas, 2):
    #print(f'{col1} e {col2}')
    suporte = len(df_transposto.loc[ (df_transposto[col1]=='sim') & (df_transposto[col2]=='sim') ] )/len(df_transposto)
    Aparecer = len(df_transposto.loc[(df_transposto[col1]=='sim') & (df_transposto[col2]=='sim') ])
    if 0.0 < Aparecer and suporte >=0.3:
        print(f'itemset: {col1} e {col2} aparecem nas compras {Aparecer} vezes')
        print(f'suporte para o {col1} e {col2}: {suporte*100} %')
        print()

itemset: café e pão aparecem nas compras 3 vezes
suporte para o café e pão: 30.0 %

itemset: café e manteiga aparecem nas compras 3 vezes
suporte para o café e manteiga: 30.0 %

itemset: pão e manteiga aparecem nas compras 4 vezes
suporte para o pão e manteiga: 40.0 %



# Calcular o suporte de conjunto com 3 itens

In [7]:
# o quanto são vendidos em conjuntos os produtos de forma correta pelo suporte:
from itertools import combinations
# suporte de 3 itens no exemplo
print('Suporte = Número de registros com X e Y / Número total de registros')
for col1, col2,col3 in combinations(colunas, 3):
    #print()
    #print(f'{col1}, {col2} e {col3}')
    suporte = len(df_transposto.loc[ (df_transposto[col1]=='sim') & (df_transposto[col2]=='sim') & (df_transposto[col3]=='sim') ] )/len(df_transposto)
    Aparecer = len(df_transposto.loc[(df_transposto[col1]=='sim') & (df_transposto[col2]=='sim')& (df_transposto[col3]=='sim') ])
    if 0.0 < Aparecer and suporte >=0.3:
       print(f'itemset: {col1}, {col2} e {col3} aparecem nas compras {Aparecer} vezes')
       print(f'suporte para o {col1}, {col2} e {col3}: {suporte*100} %')
       print()

Suporte = Número de registros com X e Y / Número total de registros
itemset: café, pão e manteiga aparecem nas compras 3 vezes
suporte para o café, pão e manteiga: 30.0 %

In [9]:
from itertools import combinations
# suporte de 3 itens no exemplo
print('Suporte = Número de registros com X e Y / Número total de registros')
for col1, col2,col3 in combinations(colunas, 3):
    #print()
    #print(f'{col1}, {col2} e {col3}')
    suporte = len(df_transposto.loc[ (df_transposto[col1]=='sim') & (df_transposto[col2]=='sim') & (df_transposto[col3]=='sim') ] )/len(df_transposto)
    Aparecer = len(df_transposto.loc[(df_transposto[col1]=='sim') & (df_transposto[col2]=='sim')& (df_transposto[col3]=='sim') ])
    if 0.0 < Aparecer and suporte >=0.03:
       if  Aparecer < 2:
           print(f'itemset: {col1}, {col2} e {col3} aparecem nas compras {Aparecer} vez')
       else:
           print(f'itemset: {col1}, {col2} e {col3} aparecem nas compras {Aparecer} vezes')
       print(f'suporte para o {col1}, {col2} e {col3}: {suporte*100} %')
       print()

Suporte = Número de registros com X e Y / Número total de registros
itemset: leite, café e pão aparecem nas compras 1 vez
suporte para o leite, café e pão: 10.0 %

itemset: leite, café e manteiga aparecem nas compras 1 vez
suporte para o leite, café e manteiga: 10.0 %

itemset: leite, cerveja e pão aparecem nas compras 1 vez
suporte para o leite, cerveja e pão: 10.0 %

itemset: leite, cerveja e manteiga aparecem nas compras 1 vez
suporte para o leite, cerveja e manteiga: 10.0 %

itemset: leite, pão e manteiga aparecem nas compras 2 vezes
suporte para o leite, pão e manteiga: 20.0 %

itemset: café, pão e manteiga aparecem nas compras 3 vezes
suporte para o café, pão e manteiga: 30.0 %

itemset: cerveja, pão e manteiga aparecem nas compras 1 vez
suporte para o cerveja, pão e manteiga: 10.0 %

### Eclat não gera regras, apenas gera itemsets

O elcat utiliza somente o suporte, semelhante ao apriori.

Montagem dos conjuntos dos itens.



algoritmo

1 - definir o suporte (mínimo que o usuário vai fazer).

2 - Extrair conjunto de itens que tenham o suporte mínimo

3 - Ordenar os dados de acordo com o suporte