# 21.5) Eclat

In [22]:
import pandas as pd

In [23]:
#!pip install pyECLAT

In [24]:
base_mercado1 = pd.read_csv('../15-Apriori/mercado.csv', header = None)
base_mercado1

          0        1         2         3
0     leite  cerveja       pao  manteiga
1      cafe      pao  manteiga       NaN
2      cafe      pao  manteiga       NaN
3     leite     cafe       pao  manteiga
4   cerveja      NaN       NaN       NaN
5  manteiga      NaN       NaN       NaN
6       pao      NaN       NaN       NaN
7    feijao      NaN       NaN       NaN
8     arroz   feijao       NaN       NaN
9     arroz      NaN       NaN       NaN

Gerar os dados dos itens mais frequentes

In [25]:
# retorno dos itens frequentes

In [26]:
from pyECLAT import ECLAT
eclat = ECLAT(data = base_mercado1)

In [27]:
eclat

In [28]:
# explorar os atributos

In [29]:
eclat.df_bin # dateframe com os dados binários

   cerveja  feijao  arroz  pao  manteiga  leite  cafe
0        1       0      0    1         1      1     0
1        0       0      0    1         1      0     1
2        0       0      0    1         1      0     1
3        0       0      0    1         1      1     1
4        1       0      0    0         0      0     0
5        0       0      0    0         1      0     0
6        0       0      0    1         0      0     0
7        0       1      0    0         0      0     0
8        0       1      1    0         0      0     0
9        0       0      1    0         0      0     0

In [30]:
# 1 comprou
# 0 não comprou

In [31]:
eclat.uniq_ # dados únicos dos produtos

['cerveja', 'feijao', 'arroz', 'pao', 'manteiga', 'leite', nan, 'cafe']

In [32]:
# verificar os indices frequentes

Combinação de no mínimo 1 produto min_combination

e combinação de no máximo 3 produtos max_combination

In [33]:
indices, suporte = eclat.fit(min_support=0.3, min_combination=1, max_combination=3)

Combination 1 by 1

3it [00:00, 182.68it/s]

Combination 2 by 2

3it [00:00, 266.69it/s]

Combination 3 by 3

1it [00:00, 261.56it/s]

In [34]:
indices

{'pao': [0, 1, 2, 3, 6],
 'manteiga': [0, 1, 2, 3, 5],
 'cafe': [1, 2, 3],
 'pao & manteiga': [0, 1, 2, 3],
 'pao & cafe': [1, 2, 3],
 'manteiga & cafe': [1, 2, 3],
 'pao & manteiga & cafe': [1, 2, 3]}

café aparece 3 vezes 'cafe': [1, 2, 3], aparece em 3 transações e os números são os locais das transações, no caso o indice do dataframe.

In [35]:
suporte

{'pao': 0.5,
 'manteiga': 0.5,
 'cafe': 0.3,
 'pao & manteiga': 0.4,
 'pao & cafe': 0.3,
 'manteiga & cafe': 0.3,
 'pao & manteiga & cafe': 0.3}

In [36]:
# ver a combinação de apenas 2 produtos, no mínimo, 
# suporte de 30% no mínimo (que é 3 transações, pois foram 10 transações nos totais

indices, suporte = eclat.fit(min_support=0.3, min_combination=2, max_combination=4)

indices

Combination 2 by 2

3it [00:00, 217.78it/s]

Combination 3 by 3

1it [00:00, 122.64it/s]

Combination 4 by 4

0it [00:00, ?it/s]

{'pao & manteiga': [0, 1, 2, 3],
 'pao & cafe': [1, 2, 3],
 'manteiga & cafe': [1, 2, 3],
 'pao & manteiga & cafe': [1, 2, 3]}

In [37]:
suporte

{'pao & manteiga': 0.4,
 'pao & cafe': 0.3,
 'manteiga & cafe': 0.3,
 'pao & manteiga & cafe': 0.3}

In [40]:
indices, suporte = eclat.fit(min_support=0.5, min_combination=1, max_combination=3)

indices,suporte

Combination 1 by 1

2it [00:00, 109.72it/s]

Combination 2 by 2

1it [00:00, 231.92it/s]

Combination 3 by 3

0it [00:00, ?it/s]

({'pao': [0, 1, 2, 3, 6], 'manteiga': [0, 1, 2, 3, 5]},
 {'pao': 0.5, 'manteiga': 0.5})

In [41]:
# contagem dos itens que mais aparecem